//>>built
define("dgrid/ColumnSet","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on dojo/aspect dojo/query dojo/has ./util/misc put-selector/put xstyle/has-class ./Grid dojo/_base/sniff xstyle/css!./css/columnset.css".split(" "),function(y,z,A,B,p,q,n,g,r,l,C,F){function x(a,b){function c(){n(".dgrid-column-set",b).forEach(function(c){c.scrollLeft=d[c.getAttribute(h)]})}var d=a._columnSetScrollLefts;8>g("ie")||g("quirks")?setTimeout(c,1):c()}g.add("event-mousewheel",function(a,
b,c){return"onmousewheel"in c});g.add("event-wheel",function(a,b,c){return"onwheel"in c});var h="data-dgrid-column-set-id";C("safari","ie-7");var D=g("event-mousewheel")||g("event-wheel")?function(a){return function(b,c){return p(b,g("event-mousewheel")?"mousewheel":"wheel",function(d){var e=d.target;1!==e.nodeType&&(e=e.parentNode);for(;!n.matches(e,".dgrid-column-set["+h+"]",b);)if(e===b||!(e=e.parentNode))return;(d=d.deltaX||-d.wheelDeltaX/3)&&c.call(null,a,e,d)})}}:function(a){return function(b,
c){return p(b,".dgrid-column-set["+h+"]:MozMousePixelScroll",function(b){1===b.axis&&c.call(null,a,this,b.detail)})}};return z(null,{postCreate:function(){var a=this;this.inherited(arguments);this.on(D(this),function(b,c,a){c=c.getAttribute(h);b=b._columnSetScrollers[c];a=b.scrollLeft+a;b.scrollLeft=0>a?0:a});this.on(".dgrid-column-set:dgrid-cellfocusin",function(b){a._onColumnSetCellFocus(b,this)})},columnSets:[],createRowCells:function(a,b,c,d){for(var e=l("table.dgrid-row-table"),g=l(e,"tbody tr"),
f=0,k=this.columnSets.length;f<k;f++){var E=l(g,a+".dgrid-column-set-cell.dgrid-column-set-"+f+" div.dgrid-column-set["+h+"\x3d"+f+"]"),m;m=c||this.subRows;if(!m||!m.length)m=void 0;else{for(var n=[],p=f+"-",s=0,q=m.length;s<q;s++){var t=m[s],u=[];u.className=t.className;for(var v=0,r=t.length;v<r;v++){var w=t[v];null!=w.id&&0===w.id.indexOf(p)&&u.push(w)}n.push(u)}m=n}E.appendChild(this.inherited(arguments,[a,b,m||this.columnSets[f],d]))}return e},renderArray:function(){var a=this,b=this.inherited(arguments);
B.when(b,function(c){for(var b=0;b<c.length;b++)x(a,c[b])});return b},insertRow:function(){var a=this.inherited(arguments);x(this,a);return a},renderHeader:function(){function a(){d._positionScrollers()}this.inherited(arguments);var b=this.columnSets,c=this._columnSetScrollers;this._columnSetScrollerContents={};this._columnSetScrollLefts={};var d=this,e;if(c)for(e in c)l(c[e],"!");else q.after(this,"resize",a,!0),q.after(this,"styleColumn",a,!0),this._columnSetScrollerNode=l(this.footerNode,"+div.dgrid-column-set-scroller-container");
c=this._columnSetScrollers={};e=0;for(c=b.length;e<c;e++)this._putScroller(b[e],e);this._positionScrollers()},styleColumnSet:function(a,b){var c=this.addCssRule("#"+r.escapeCssIdentifier(this.domNode.id)+" .dgrid-column-set-"+r.escapeCssIdentifier(a,"-"),b);this._positionScrollers();return c},_destroyColumns:function(){var a=this.columnSets.length,b,c,d,e,g,f,k,h;for(b=0;b<a;b++){f=this.columnSets[b];c=0;for(e=f.length;c<e;c++){k=f[c];d=0;for(g=k.length;d<g;d++)h=k[d],"function"===typeof h.destroy&&
h.destroy()}}this.inherited(arguments)},configStructure:function(){this.columns={};this.subRows=[];for(var a=0,b=this.columnSets.length;a<b;a++)for(var c=this.columnSets[a],d=0;d<c.length;d++)c[d]=this._configColumns(a+"-"+d+"-",c[d]);this.inherited(arguments)},_positionScrollers:function(){var a=this.domNode,b=this._columnSetScrollers,c=this._columnSetScrollerContents,d=this.columnSets,e=0,l=0,f,k;f=0;for(d=d.length;f<d;f++)k=n(".dgrid-column-set["+h+'\x3d"'+f+'"]',a)[0],e=k.offsetWidth,k=k.firstChild.offsetWidth,
c[f].style.width=k+"px",b[f].style.width=e+"px",9>g("ie")&&(b[f].style.overflowX=k>e?"scroll":"auto"),k>e&&l++;this._columnSetScrollerNode.style.bottom=this.showFooter?this.footerNode.offsetHeight+"px":"0";this.bodyNode.style.bottom=l?g("dom-scrollbar-height")+(g("ie")?1:0)+"px":"0"},_putScroller:function(a,b){var c=this._columnSetScrollers[b]=l(this._columnSetScrollerNode,"span"+(9>g("ie")||g("ff")?".dgrid-scrollbar-height":"")+".dgrid-column-set-scroller.dgrid-column-set-scroller-"+b+"["+h+"\x3d"+
b+"]");this._columnSetScrollerContents[b]=l(c,"div.dgrid-column-set-scroller-content");p(c,"scroll",A.hitch(this,"_onColumnSetScroll"))},_onColumnSetScroll:function(a){var b=a.target.scrollLeft;a=a.target.getAttribute(h);var c;this._columnSetScrollLefts[a]!=b&&(n(".dgrid-column-set["+h+'\x3d"'+a+'"],.dgrid-column-set-scroller['+h+'\x3d"'+a+'"]',this.domNode).forEach(function(a,e){a.scrollLeft=b;e||(c=a.scrollLeft)}),this._columnSetScrollLefts[a]=c)},_setColumnSets:function(a){this._destroyColumns();
this.columnSets=a;this._updateColumns()},setColumnSets:function(a){y.deprecated("setColumnSets(...)",'use set("columnSets", ...) instead',"dgrid 0.4");this.set("columnSets",a)},_scrollColumnSet:function(a,b){var c=a.tagName?a.getAttribute(h):a;this._columnSetScrollers[c].scrollLeft=0>b?0:b},_onColumnSetCellFocus:function(a,b){var c=a.target,d=b.getAttribute(h),d=this._columnSetScrollers[d];(c.offsetLeft-d.scrollLeft+c.offsetWidth>b.offsetWidth||d.scrollLeft>c.offsetLeft)&&this._scrollColumnSet(b,
c.offsetLeft)}})});
//# sourceMappingURL=ColumnSet.js.map