//>>built
define("dgrid/Keyboard","dojo/_base/declare dojo/aspect dojo/on dojo/_base/lang dojo/has put-selector/put ./util/misc dojo/_base/Deferred dojo/_base/sniff".split(" "),function(t,m,n,q,p,u,v,w){function x(a){a.preventDefault()}var F={checkbox:1,radio:1,button:1},y=/\bdgrid-cell\b/,z=/\bdgrid-row\b/,e=t(null,{pageSkip:10,tabIndex:0,keyMap:null,headerKeyMap:null,postMixInProperties:function(){this.inherited(arguments);this.keyMap||(this.keyMap=q.mixin({},e.defaultKeyMap));this.headerKeyMap||(this.headerKeyMap=
q.mixin({},e.defaultHeaderKeyMap))},postCreate:function(){function a(a){var b=a.target;return b.type&&(!F[b.type]||32==a.keyCode)}function c(c){function d(){b._focusedHeaderNode&&(b._focusedHeaderNode.tabIndex=-1);if(b.showHeader){if(e)for(var a=0,c,d=b.headerNode.getElementsByTagName("th");c=d[a];++a){if(k.test(c.className)){b._focusedHeaderNode=g=c;break}}else b._focusedHeaderNode=g=b.headerNode;g&&(g.tabIndex=b.tabIndex)}}var e=b.cellNavigation,k=e?y:z,f=c===b.headerNode,g=c;f?(d(),m.after(b,"renderHeader",
d,!0)):m.after(b,"renderArray",function(a){return w.when(a,function(a){var d=b._focusedNode||g;if(k.test(d.className)&&v.contains(c,d))return a;for(var e=0,f=c.getElementsByTagName("*"),l;l=f[e];++e)if(k.test(l.className)){d=b._focusedNode=l;break}d.tabIndex=b.tabIndex;return a})});b._listeners.push(n(c,"mousedown",function(c){a(c)||b._focusOnNode(c.target,f,c)}));b._listeners.push(n(c,"keydown",function(c){if(!c.metaKey&&!c.altKey){var d=b[f?"headerKeyMap":"keyMap"][c.keyCode];d&&!a(c)&&d.call(b,
c)}}))}this.inherited(arguments);var b=this;this.tabableHeader&&(c(this.headerNode),n(this.headerNode,"dgrid-cellfocusin",function(){b.scrollTo({x:this.scrollLeft})}));c(this.contentNode);this._debouncedEnsureRowScroll=v.debounce(this._ensureRowScroll,this)},removeRow:function(a){if(!this._focusedNode)return this.inherited(arguments);var c=this,b=document.activeElement===this._focusedNode,e=this[this.cellNavigation?"cell":"row"](this._focusedNode),d=e.row||e,h;a=a.element||a;if(a===d.element){h=this.down(d,
!0);if(!h||h.element===a)h=this.up(d,!0);this._removedFocus={active:b,rowId:d.id,columnId:e.column&&e.column.id,siblingId:!h||h.element===a?void 0:h.id};setTimeout(function(){c._removedFocus&&c._restoreFocus(d.id)},0);this._focusedNode=null}this.inherited(arguments)},insertRow:function(a){var c=this.inherited(arguments);this._removedFocus&&!this._removedFocus.wait&&this._restoreFocus(c);return c},_restoreFocus:function(a){var c=this._removedFocus,b;if((a=(a=a&&this.row(a))&&a.element&&a.id===c.rowId?
a:"undefined"!==typeof c.siblingId&&this.row(c.siblingId))&&a.element){if(!a.element.parentNode.parentNode){c.wait=!0;return}"undefined"!==typeof c.columnId&&(b=this.cell(a,c.columnId))&&b.element&&(a=b);c.active&&0!==a.element.offsetHeight?this._focusOnNode(a,!1,null):(u(a.element,".dgrid-focus"),a.element.tabIndex=this.tabIndex,this._focusedNode=a.element)}delete this._removedFocus},addKeyHandler:function(a,c,b){return m.after(this[b?"headerKeyMap":"keyMap"],a,c,!0)},_ensureRowScroll:function(a){var c=
this.getScrollPosition().y;c>a.offsetTop?this.scrollTo({y:a.offsetTop}):c+this.contentNode.offsetHeight<a.offsetTop+a.offsetHeight&&this.scrollTo({y:a.offsetTop-this.contentNode.offsetHeight+a.offsetHeight})},_focusOnNode:function(a,c,b){var e="_focused"+(c?"Header":"")+"Node",d=this[e],h=this.cellNavigation?"cell":"row",k=this[h](a),f,g,l,m,r;if(a=k&&k.element){if(this.cellNavigation){f=a.getElementsByTagName("input");r=0;for(l=f.length;r<l;r++)if(g=f[r],(-1!=g.tabIndex||"_dgridLastValue"in g)&&
!g.disabled){8>p("ie")&&(g.style.position="relative");g.focus();8>p("ie")&&(g.style.position="");m=!0;break}}null!==b&&(b=q.mixin({grid:this},b),b.type&&(b.parentType=b.type),b.bubbles||(b.bubbles=!0));d&&(u(d,"!dgrid-focus[!tabIndex]"),8>p("ie")&&(d.style.position=""),b&&(b[h]=this[h](d),n.emit(d,"dgrid-cellfocusout",b)));d=this[e]=a;b&&(b[h]=k);e=this.cellNavigation?y:z;!m&&e.test(a.className)&&(8>p("ie")&&(a.style.position="relative"),a.tabIndex=this.tabIndex,a.focus());u(a,".dgrid-focus");b&&
n.emit(d,"dgrid-cellfocusin",b);this.cellNavigation&&((this.columnSets||1<this.subRows.length)&&!c)&&this._debouncedEnsureRowScroll(k.row.element)}},focusHeader:function(a){this._focusOnNode(a||this._focusedHeaderNode,!0)},focus:function(a){(a=a||this._focusedNode)?this._focusOnNode(a,!1):this.contentNode.focus()}}),s=e.moveFocusVertical=function(a,c){var b=this.cellNavigation,e=this[b?"cell":"row"](a),e=b&&e.column.id,d=this.down(this._focusedNode,c,!0);b&&(d=this.cell(d,e));this._focusOnNode(d,
!1,a);a.preventDefault()};t=e.moveFocusUp=function(a){s.call(this,a,-1)};var G=e.moveFocusDown=function(a){s.call(this,a,1)},H=e.moveFocusPageUp=function(a){s.call(this,a,-this.pageSkip)},I=e.moveFocusPageDown=function(a){s.call(this,a,this.pageSkip)},A=e.moveFocusHorizontal=function(a,c){if(this.cellNavigation){var b=!this.row(a);this._focusOnNode(this.right(this["_focused"+(b?"Header":"")+"Node"],c),b,a);a.preventDefault()}},B=e.moveFocusLeft=function(a){A.call(this,a,-1)},C=e.moveFocusRight=function(a){A.call(this,
a,1)},D=e.moveHeaderFocusEnd=function(a,c){var b;this.cellNavigation&&(b=this.headerNode.getElementsByTagName("th"),this._focusOnNode(b[c?0:b.length-1],!0,a));a.preventDefault()},J=e.moveHeaderFocusHome=function(a){D.call(this,a,!0)},E=e.moveFocusEnd=function(a,c){var b=this,e=this.cellNavigation,d=this.contentNode,h=d.scrollTop+(c?0:d.scrollHeight),d=d[c?"firstChild":"lastChild"],k=-1<d.className.indexOf("dgrid-preload"),f=k?d[(c?"next":"previous")+"Sibling"]:d,g=f.offsetTop+(c?0:f.offsetHeight),
l;if(k){for(;f&&0>f.className.indexOf("dgrid-row");)f=f[(c?"next":"previous")+"Sibling"];if(!f)return}!k||1>d.offsetHeight?(e&&(f=this.cell(f,this.cell(a).column.id)),this._focusOnNode(f,!1,a)):(p("dom-addeventlistener")||(a=q.mixin({},a)),l=m.after(this,"renderArray",function(d){l.remove();return w.when(d,function(d){d=d[c?0:d.length-1];e&&(d=b.cell(d,b.cell(a).column.id));b._focusOnNode(d,!1,a)})}));h===g&&a.preventDefault()},K=e.moveFocusHome=function(a){E.call(this,a,!0)};e.defaultKeyMap={32:x,
33:H,34:I,35:E,36:K,37:B,38:t,39:C,40:G};e.defaultHeaderKeyMap={32:x,35:D,36:J,37:B,39:C};return e});
//# sourceMappingURL=Keyboard.js.map