//>>built
define("dgrid/Keyboard","dojo/_base/declare dojo/aspect dojo/on dojo/_base/lang dojo/has put-selector/put dojo/_base/Deferred dojo/_base/sniff".split(" "),function(t,p,k,q,m,u,v){function w(a){a.preventDefault()}var C={checkbox:1,radio:1,button:1},D=/\bdgrid-cell\b/,E=/\bdgrid-row\b/;m.add("dom-contains",function(a,e,c){return!!c.contains});var b=t(null,{pageSkip:10,tabIndex:0,keyMap:null,headerKeyMap:null,postMixInProperties:function(){this.inherited(arguments);this.keyMap||(this.keyMap=q.mixin({},
b.defaultKeyMap));this.headerKeyMap||(this.headerKeyMap=q.mixin({},b.defaultHeaderKeyMap))},postCreate:function(){function a(a){var c=a.target;return c.type&&(!C[c.type]||32==a.keyCode)}function e(e){function f(){if(c._focusedHeaderNode=l=b?c.headerNode.getElementsByTagName("th")[0]:c.headerNode)l.tabIndex=c.tabIndex}var b=c.cellNavigation,g=b?D:E,d=e===c.headerNode,l=e;d?(f(),p.after(c,"renderHeader",f,!0)):p.after(c,"renderArray",function(a){return v.when(a,function(a){var d=c._focusedNode||l,b;
if(b=g.test(d.className))b=d,b=m("dom-contains")?e.contains(b):e.compareDocumentPosition(b)&8;if(b)return a;b=0;for(var f=e.getElementsByTagName("*"),h;h=f[b];++b)if(g.test(h.className)){d=c._focusedNode=h;break}d.tabIndex=c.tabIndex;return a})});c._listeners.push(k(e,"mousedown",function(e){a(e)||c._focusOnNode(e.target,d,e)}));c._listeners.push(k(e,"keydown",function(e){if(!e.metaKey&&!e.altKey){var b=c[d?"headerKeyMap":"keyMap"][e.keyCode];b&&!a(e)&&b.call(c,e)}}))}this.inherited(arguments);var c=
this;this.tabableHeader&&(e(this.headerNode),k(this.headerNode,"dgrid-cellfocusin",function(){c.scrollTo({x:this.scrollLeft})}));e(this.contentNode)},addKeyHandler:function(a,e,c){return p.after(this[c?"headerKeyMap":"keyMap"],a,e,!0)},_focusOnNode:function(a,e,c){e="_focused"+(e?"Header":"")+"Node";var b=this[e],f=this.cellNavigation?"cell":"row",n=this[f](a),g,d,l,h,r;if(a=n&&n.element){if(this.cellNavigation){g=a.getElementsByTagName("input");r=0;for(l=g.length;r<l;r++)if(d=g[r],(-1!=d.tabIndex||
"lastValue"in d)&&!d.disabled){8>m("ie")&&(d.style.position="relative");d.focus();8>m("ie")&&(d.style.position="");h=!0;break}}c=q.mixin({grid:this},c);c.type&&(c.parentType=c.type);c.bubbles||(c.bubbles=!0);b&&(u(b,"!dgrid-focus[!tabIndex]"),8>m("ie")&&(b.style.position=""),c[f]=this[f](b),k.emit(a,"dgrid-cellfocusout",c));b=this[e]=a;c[f]=n;h||(8>m("ie")&&(a.style.position="relative"),a.tabIndex=this.tabIndex,a.focus());u(a,".dgrid-focus");k.emit(b,"dgrid-cellfocusin",c)}},focusHeader:function(a){this._focusOnNode(a||
this._focusedHeaderNode,!0)},focus:function(a){this._focusOnNode(a||this._focusedNode,!1)}}),s=b.moveFocusVertical=function(a,e){var c=this.cellNavigation,b=this[c?"cell":"row"](a),b=c&&b.column.id,f=this.down(this._focusedNode,e,!0);c&&(f=this.cell(f,b));this._focusOnNode(f,!1,a);a.preventDefault()};t=b.moveFocusUp=function(a){s.call(this,a,-1)};var F=b.moveFocusDown=function(a){s.call(this,a,1)},G=b.moveFocusPageUp=function(a){s.call(this,a,-this.pageSkip)},H=b.moveFocusPageDown=function(a){s.call(this,
a,this.pageSkip)},x=b.moveFocusHorizontal=function(a,b){if(this.cellNavigation){var c=!this.row(a);this._focusOnNode(this.right(this["_focused"+(c?"Header":"")+"Node"],b),c,a);a.preventDefault()}},y=b.moveFocusLeft=function(a){x.call(this,a,-1)},z=b.moveFocusRight=function(a){x.call(this,a,1)},A=b.moveHeaderFocusEnd=function(a,b){var c;this.cellNavigation&&(c=this.headerNode.getElementsByTagName("th"),this._focusOnNode(c[b?0:c.length-1],!0,a));a.preventDefault()},I=b.moveHeaderFocusHome=function(a){A.call(this,
a,!0)},B=b.moveFocusEnd=function(a,b){var c=this,k=this.cellNavigation,f=this.contentNode,n=f.scrollTop+(b?0:f.scrollHeight),f=f[b?"firstChild":"lastChild"],g=-1<f.className.indexOf("dgrid-preload"),d=g?f[(b?"next":"previous")+"Sibling"]:f,l=d.offsetTop+(b?0:d.offsetHeight),h;if(g){for(;d&&0>d.className.indexOf("dgrid-row");)d=d[(b?"next":"previous")+"Sibling"];if(!d)return}!g||1>f.offsetHeight?(k&&(d=this.cell(d,this.cell(a).column.id)),this._focusOnNode(d,!1,a)):(m("dom-addeventlistener")||(a=q.mixin({},
a)),h=p.after(this,"renderArray",function(d){h.remove();return v.when(d,function(d){d=d[b?0:d.length-1];k&&(d=c.cell(d,c.cell(a).column.id));c._focusOnNode(d,!1,a)})}));n===l&&a.preventDefault()},J=b.moveFocusHome=function(a){B.call(this,a,!0)};b.defaultKeyMap={32:w,33:G,34:H,35:B,36:J,37:y,38:t,39:z,40:F};b.defaultHeaderKeyMap={32:w,35:A,36:I,37:y,39:z};return b});
//@ sourceMappingURL=Keyboard.js.map