//>>built
define("dgrid/List","dojo/_base/kernel dojo/_base/declare dojo/dom dojo/on dojo/has ./util/misc dojo/has!touch?./TouchScroll xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),function(y,A,G,s,e,q,H,I,d){function B(a,b){d(document.body,a,".dgrid-scrollbar-measure");var c=a["offset"+b]-a["client"+b];a.className="";document.body.removeChild(a);return c}function v(a){var b=a?"."+a.replace(C,"."):"";this._class&&(b="!"+this._class.replace(C,"!")+b);d(this.domNode,
b);this._class=a}function D(){return this._class}function E(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}}function F(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)}I("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var r,u;e.add("dom-scrollbar-width",function(a,b,c){return B(c,"Width")});e.add("dom-scrollbar-height",function(a,b,c){return B(c,"Height")});e.add("dom-rtl-scrollbar-left",
function(a,b,c){a=d("div");d(document.body,c,".dgrid-scrollbar-measure[dir\x3drtl]");d(c,a);b=!!e("ie")||!!e("trident")||a.offsetLeft>=e("dom-scrollbar-width");c.className="";document.body.removeChild(c);d(a,"!");c.removeAttribute("dir");return b});var J=0,C=/ +/g,K=7>e("ie")&&!e("quirks")?function(){var a,b,c;if(this._started&&(a=document.documentElement,b=a.clientWidth,a=a.clientHeight,c=this._prevWinDims||[],c[0]!==b||c[1]!==a))this.resize(),this._prevWinDims=[b,a]}:function(){this._started&&this.resize()};
return A(e("touch")?H:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,cleanAddedRules:!0,useTouchScroll:null,addUiClasses:!0,shouldObserveStore:!0,cleanEmptyObservers:!0,highlightDuration:250,postscript:function(a,b){var c=this;(this._Row=function(a,b,c){this.id=a;this.data=b;this.element=c}).prototype.remove=function(){c.removeRow(this.element)};b&&(this.srcNodeRef=b=b.nodeType?b:document.getElementById(b));this.create(a,b)},listType:"list",create:function(a,b){var c=this.domNode=
b||d("div"),h;a?(this.params=a,A.safeMixin(this,a),h=a["class"]||a.className||c.className,this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._numObservers=0;this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=c.id=c.id||this.id||"dgrid_"+J++;null===this.useTouchScroll&&(this.useTouchScroll=!e("dom-scrollbar-width"));this.buildRendering();h&&v.call(this,h);this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&
this.startup()},buildRendering:function(){var a=this.domNode,b=this.addUiClasses,c=this,h,n,f,g;g=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";d(a,"[role\x3dgrid].dgrid.dgrid-"+this.listType+(b?".ui-widget":""));h=this.headerNode=d(a,"div.dgrid-header.dgrid-header-row"+(b?".ui-widget-header":"")+(this.showHeader?"":".dgrid-header-hidden"));(e("quirks")||8>e("ie"))&&d(a,"div.dgrid-spacer");n=this.bodyNode=d(a,"div.dgrid-scroller");
e("ff")&&(n.tabIndex=-1);this.headerScrollNode=d(a,"div.dgrid-header.dgrid-header-scroll.dgrid-scrollbar-width"+(b?".ui-widget-header":""));f=this.footerNode=d("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));d(a,f);g&&(a.className+=" dgrid-rtl"+(e("dom-rtl-scrollbar-left")?" dgrid-rtl-swap":""));s(n,"scroll",function(b){c.showHeader&&(h.scrollLeft=b.scrollLeft||n.scrollLeft);b.stopPropagation();s.emit(a,"scroll",{scrollTarget:n})});this.configStructure();this.renderHeader();this.contentNode=
this.touchNode=d(this.bodyNode,"div.dgrid-content"+(b?".ui-widget-content":""));this._listeners.push(this._resizeHandle=s(window,"resize",q.throttleDelayed(K,this)))},postCreate:e("touch")?function(){this.useTouchScroll&&this.inherited(arguments)}:function(){},startup:function(){this._started||(this.inherited(arguments),this._started=!0,this.resize(),this.set("sort",this._sort))},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,c=this.footerNode,h=b.offsetHeight,
n=this.showFooter?c.offsetHeight:0,f=e("quirks")||7>e("ie");this.headerScrollNode.style.height=a.style.marginTop=h+"px";a.style.marginBottom=n+"px";f&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-h-n,0)+"px",n&&(c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0)));r||(r=e("dom-scrollbar-width"),u=e("dom-scrollbar-height"),e("ie")&&(r++,u++),q.addCssRule(".dgrid-scrollbar-width","width: "+r+"px"),q.addCssRule(".dgrid-scrollbar-height","height: "+u+"px"),17!=r&&
!f&&(q.addCssRule(".dgrid-header-row","right: "+r+"px"),q.addCssRule(".dgrid-rtl-swap .dgrid-header-row","left: "+r+"px")));f&&(b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0))},addCssRule:function(a,b){var c=q.addCssRule(a,b);this.cleanAddedRules&&this._listeners.push(c);return c},on:function(a,b){var c=s(this.domNode,a,b);e("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){var a=this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=
this.columns){var c=document.getElementById(b);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this._numObservers=0;this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this._started=!1;this.cleanup();d(this.domNode,"!");this.useTouchScroll&&this.inherited(arguments)},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";
this.scrollTo({x:0,y:0})},newRow:function(a,b,c,h,n){if(b){var f=this.insertRow(a,b,c,h,n);d(f,".dgrid-highlight"+(this.addUiClasses?".ui-state-highlight":""));setTimeout(function(){d(f,"!dgrid-highlight!ui-state-highlight")},this.highlightDuration);return f}},adjustRowIndices:function(a){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(this.maintainOddEven&&-1<(a.className+" ").indexOf("dgrid-row ")&&d(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=
b++);while((a=a.nextSibling)&&a.rowIndex!=b)}},renderArray:function(a,b,c){function h(){var b=arguments;if(-1<t)for(var f=0;f<b.length;f++){var e=b[f],h=l[e?0:l.length-1];if(h=h&&n(h)){var m=h[e?"previousSibling":"nextSibling"];m&&(m=d.row(m));m&&m.element!=h&&(e=e?"unshift":"push",a[e](m.data),l[e](m.element),c.count++)}}}function n(a){return!G.isDescendant(a,d.domNode)&&document.getElementById(a.id)?d.row(a.id.slice(d.id.length+5)).element:a}function f(a){x=d.insertRow(a,v,null,r++,c);x.observerIndex=
t;return x}function e(a){u=a.slice(0);(w=b?b.parentNode:d.contentNode)&&w.parentNode&&(w!==d.contentNode||a.length)?(w.insertBefore(v,b||null),(x=a[a.length-1])&&d.adjustRowIndices(x)):q[t]&&d.cleanEmptyObservers&&"undefined"!==typeof t&&(q[t].cancel(),q[t]=0,d._numObservers--);l=a;s&&(s.rows=l)}c=c||{};var d=this,r=c.start||0,q=this.observers,l,w,t;b||(this._lastCollection=a);if(a.observe&&this.shouldObserveStore){d._numObservers++;var s=a.observe(function(e,f,g){var p,m,k;-1<f&&l[f]&&(p=l.splice(f,
1)[0],p.parentNode==w&&((m=p.nextSibling)&&f!=g&&m.rowIndex--,d.removeRow(p)),c.count--,d._processScroll&&d._processScroll());if(-1<g){if(l.length)if(0===g)k=(k=l[g])&&n(k);else{if(k=l[g-1])k=n(k),k=(k.connected||k).nextSibling}else k=d._getFirstRowSibling&&d._getFirstRowSibling(w);p&&(k&&p.id===k.id)&&(k=(k.connected||k).nextSibling);k&&!k.parentNode&&(k=document.getElementById(k.id));p=b&&b.parentNode||k&&k.parentNode||d.contentNode;if(p=d.newRow(e,p,k,c.start+g,c))if(p.observerIndex=t,l.splice(g,
0,p),!m||g<f)m=p.previousSibling,m=!m||m.rowIndex+1==p.rowIndex||0==p.rowIndex?p:m;c.count++}0===f?h(1,1):f===a.length-(-1===g?0:1)&&h(0,0);f!=g&&m&&d.adjustRowIndices(m);d._onNotification(l,e,f,g)},!0);t=q.push(s)-1}var v=document.createDocumentFragment(),x,u;if(a.map){if(l=a.map(f,console.error),l.then)return a.then(function(b){a=b;return l.then(function(a){e(a);h(1,1,0,0);return u})})}else{l=[];for(var z=0,y=a.length;z<y;z++)l[z]=f(a[z])}e(l);h(1,1,0,0);return u},_onNotification:function(a,b,c,
d){},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,d,e){var f=e.parentId,f=this.id+"-row-"+(f?f+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),g=document.getElementById(f),q=g&&g.previousSibling;g&&(g===c&&(c=(c.connected||c).nextSibling),this.removeRow(g));g=this.renderRow(a,e);g.className=(g.className||"")+" dgrid-row "+(1==d%2?"dgrid-row-odd":"dgrid-row-even")+(this.addUiClasses?" ui-state-default":"");this._rowIdToObject[g.id=f]=a;b.insertBefore(g,
c||null);q&&this.adjustRowIndices(q);g.rowIndex=d;return g},renderRow:function(a,b){return d("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||d(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):
(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,d){var e,f;f=e=a.element;b=b||1;do if(a=e[0>b?"previousSibling":"nextSibling"]){do if((e=a)&&-1<(e.className+" ").indexOf(c+" ")){f=e;b+=0>b?1:-1;break}while(a=(!d||!e.hidden)&&e[0>b?"lastChild":"firstChild"])}else if(e=e.parentNode,!e||e===this.bodyNode||e===this.headerNode)break;while(b);return f},up:function(a,b,c){a.element||
(a=this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:e("touch")?function(a){return this.useTouchScroll?this.inherited(arguments):F.call(this,a)}:F,getScrollPosition:e("touch")?function(){return this.useTouchScroll?this.inherited(arguments):E.call(this)}:E,get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,
1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:D,_setClass:v,_getClassName:D,_setClassName:v,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,descending:b}];this.refresh();this._lastCollection&&(a.length&&("string"!=typeof a&&(b=a[0].descending,a=a[0].attribute),this._lastCollection.sort(function(c,
e){var d=c[a],f=e[a];void 0===d&&(d="");void 0===f&&(f="");return d==f?0:d>f==!b?1:-1})),this.renderArray(this._lastCollection))},sort:function(a,b){y.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 0.4");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=a;d(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},setShowHeader:function(a){y.deprecated("setShowHeader(...)",
'use set("showHeader", ...) instead',"dgrid 0.4");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;d(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})});
//# sourceMappingURL=List.js.map