//>>built
define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on ./util/misc put-selector/put".split(" "),function(G,H,I,D,t,x,u,p){return I([G,H],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:1,pagingMethod:"debounce",pagingDelay:u.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;x(this.bodyNode,"scroll",u[this.pagingMethod](function(g){c._processScroll(g)},
null,this.pagingDelay))},renderQuery:function(c,g,d){function f(c){p(b,"!");if(c)throw a._refreshDeferred&&(a._refreshDeferred.reject(c),delete a._refreshDeferred),c;}var a=this,l={query:c,count:0,node:g,options:d},n=this.preload,q;if(!g){var e={node:p(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:l,options:d};e.node.style.height="0";l.node=g=p(this.contentNode,"div.dgrid-preload");l.previous=e}g.rowIndex=this.minRowsPerPage;n?((l.next=n.next)&&this.bodyNode.scrollTop>=n.node.offsetTop?
l.previous=n:(l.next=n,l.previous=n.previous),l.previous.next=l,l.next.previous=l):this.preload=l;var b=p(g,"-div.dgrid-loading");p(b,"div.dgrid-below").innerHTML=this.loadingMessage;d=D.mixin(this.get("queryOptions"),d,{start:0,count:this.minRowsPerPage,query:c});this._trackError(function(){return q=c(d)});if("undefined"===typeof q)f();else return t.when(a.renderArray(q,g,d),function(c){return t.when("undefined"===typeof q.total?q.length:q.total,function(d){var f=c.length,e=g.parentNode,m=a.noDataNode;
p(b,"!");a._total=d;0===d&&(m&&(p(m,"!"),delete a.noDataNode),a.noDataNode=m=p("div.dgrid-no-data"),e.insertBefore(m,a._getFirstRowSibling(e)),m.innerHTML=a.noDataMessage);for(m=e=0;m<f;m++)e+=a._calcRowHeight(c[m]);f&&e&&(a.rowHeight=e/f);d-=f;l.count=d;g.rowIndex=f;d?g.style.height=Math.min(d*a.rowHeight,a.maxEmptySpace)+"px":g.style.display="none";a._previousScrollPosition&&(a.scrollTo(a._previousScrollPosition),delete a._previousScrollPosition);a._processScroll();a._refreshDeferred&&(a._refreshDeferred.resolve(q),
delete a._refreshDeferred);return c},f)},f),q},refresh:function(c){var g=this,d=c&&c.keepScrollPosition,f;"undefined"===typeof d&&(d=this.keepScrollPosition);d&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this.store)return d=this._refreshDeferred=new t,f=g.renderQuery(function(a){return g.store.query(g.query,a)}),"undefined"===typeof f&&d.reject(),d.then(function(a){setTimeout(function(){x.emit(g.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:g,
results:a})},0);delete g._refreshDeferred;return a},function(a){delete g._refreshDeferred;throw a;})},resize:function(){this.inherited(arguments);this._processScroll()},_getFirstRowSibling:function(c){return c.lastChild},_calcRowHeight:function(c){var g=c.previousSibling;return g&&g.offsetTop!=c.offsetTop?c.offsetHeight:0},lastScrollTop:0,_processScroll:function(c){function g(b,c,e,g){var f=a.farOffRemoval,h=b.node;if(c>2*f){for(var k,l=h[e],m=0,n=0,q=[];k=l;){var r=a._calcRowHeight(k);if(m+r+f>c||
0>l.className.indexOf("dgrid-row")&&0>l.className.indexOf("dgrid-loading"))break;l=k[e];m+=r;n+=k.count||1;a.removeRow(k,!0);q.push(k)}b.count+=n;g?(h.rowIndex-=n,d(b)):h.style.height=h.offsetHeight+m+"px";var s=p("div",q);setTimeout(function(){p(s,"!")},1)}}function d(b,c){b.node.style.height=Math.min(b.count*a.rowHeight,c?Infinity:a.maxEmptySpace)+"px"}function f(a,b){do a=b?a.next:a.previous;while(a&&!a.node.offsetWidth);return a}var a=this,l=a.bodyNode;c=c&&c.scrollTop||this.getScrollPosition().y;
var n=l.offsetHeight+c,q,e,b=a.preload,x=a.lastScrollTop,A=a.bufferRows*a.rowHeight,u=A-a.rowHeight,E,m,B,C=!0;for(a.lastScrollTop=c;b&&!b.node.offsetWidth;)b=b.previous;for(;b&&b!=q;){q=a.preload;a.preload=b;e=b.node;var h=e.offsetTop;if(n+1+u<h)b=f(b,C=!1);else if(c-1-u>h+e.offsetHeight)b=f(b,C=!0);else{var k=((e.rowIndex?c-A:n)-h)/a.rowHeight,h=(n-c+2*A)/a.rowHeight,y=Math.max(Math.min((c-x)*a.rowHeight,a.maxRowsPerPage/2),a.maxRowsPerPage/-2),h=h+Math.min(Math.abs(y),10);0==e.rowIndex&&(k-=h);
k=Math.max(k,0);10>k&&(0<k&&h+k<a.maxRowsPerPage)&&(h+=Math.max(0,k),k=0);h=Math.min(Math.max(h,a.minRowsPerPage),a.maxRowsPerPage,b.count);if(0==h)b=f(b,C);else{var h=Math.ceil(h),k=Math.min(Math.floor(k),b.count-h),r=D.mixin(a.get("queryOptions"),b.options);b.count-=h;var s=e,z,v=a.queryRowsOverlap;if(y=0<e.rowIndex&&b){var w=b.previous;w&&(g(w,c-(w.node.offsetTop+w.node.offsetHeight),"nextSibling"),0<k&&w.node==e.previousSibling?(k=Math.min(b.count,k),b.previous.count+=k,d(b.previous,!0),e.rowIndex+=
k,v=0):h+=k,b.count-=k);r.start=e.rowIndex-v;r.count=Math.min(h+v,a.maxRowsPerPage);e.rowIndex=r.start+r.count}else b.next&&(g(b.next,b.next.node.offsetTop-n,"previousSibling",!0),s=e.nextSibling,s==b.next.node?(b.next.count+=b.count-k,b.next.node.rowIndex=k+h,d(b.next),b.count=k,v=0):z=!0),r.start=b.count,r.count=Math.min(h+v,a.maxRowsPerPage);z&&(s&&s.offsetWidth)&&(z=s.offsetTop);d(b);e=p(s,"-div.dgrid-loading[style\x3dheight:"+h*a.rowHeight+"px]");p(e,"div.dgrid-"+(y?"below":"above")).innerHTML=
a.loadingMessage;e.count=h;r.query=b.query;if(!(r.start>a._total||0>r.count)){var F=b.query(r);if(void 0===a._trackError(function(){return F})){p(e,"!");return}(function(b,c,e,g,f){B=t.when(a.renderArray(f,b,r),function(c){m=f;s=b.nextSibling;p(b,"!");if(g&&s&&s.offsetWidth){var h=a.getScrollPosition();a.scrollTo({x:h.x,y:h.y+s.offsetTop-g,preserveMomentum:!0})}t.when(f.total||f.length,function(b){a._total=b;e&&(e.count=b-e.node.rowIndex,d(e))});a._processScroll();return c},function(a){p(b,"!");throw a;
})}).call(this,e,l,y,z,F);b=b.previous}}}}if(B&&(E=this._refreshDeferred))delete this._refreshDeferred,t.when(B,function(){E.resolve(m)})},removeRow:function(c,g){if(c){var d=c.previousSibling,f=c.nextSibling,d=d&&(null!=d.observerIndex?d.observerIndex:d.previousObserverIndex),a=f&&(null!=f.observerIndex?f.observerIndex:f.nextObserverIndex),f=c.observerIndex;c.observerIndex=void 0;g&&(c.nextObserverIndex=a,c.previousObserverIndex=d);if(-1<f&&(f!==d&&f!==a)&&(d=this.observers,a=d[f]))a.cancel(),this._numObservers--,
d[f]=0}this.inherited(arguments)}})});
//@ sourceMappingURL=OnDemandList.js.map