//>>built
define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/dom dojo/on ./util/misc put-selector/put".split(" "),function(F,G,H,C,t,I,u,v,q){return H([F,G],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:0,pagingMethod:"debounce",pagingDelay:v.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;u(this.bodyNode,"scroll",v[this.pagingMethod](function(f){c._processScroll(f)},
null,this.pagingDelay))},destroy:function(){this.inherited(arguments);this._refreshTimeout&&clearTimeout(this._refreshTimeout)},renderQuery:function(c,f){function h(a){q(s,"!");if(a)throw d._refreshDeferred&&(d._refreshDeferred.reject(a),delete d._refreshDeferred),a;}var d=this,b=f&&f.container||this.contentNode,k={query:c,count:0,options:f},m,e=this.preload,a,y={node:q(b,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:k,options:f};y.node.style.height="0";k.node=m=q(b,"div.dgrid-preload");
k.previous=y;m.rowIndex=this.minRowsPerPage;e?((k.next=e.next)&&m.offsetTop>=e.node.offsetTop?k.previous=e:(k.next=e,k.previous=e.previous),k.previous.next=k,k.next.previous=k):this.preload=k;var s=q(m,"-div.dgrid-loading");q(s,"div.dgrid-below").innerHTML=this.loadingMessage;f=C.mixin(this.get("queryOptions"),f,{start:0,count:this.minRowsPerPage},"level"in c?{queryLevel:c.level}:null);this._trackError(function(){return a=c(f)});if("undefined"===typeof a)h();else return t.when(d.renderArray(a,m,f),
function(b){return t.when("undefined"===typeof a.total?a.length:a.total,function(c){var h=b.length,e=m.parentNode,p=d.noDataNode;q(s,"!");"queryLevel"in f||(d._total=c);0===c&&e&&(p&&(q(p,"!"),delete d.noDataNode),d.noDataNode=p=q("div.dgrid-no-data"),e.insertBefore(p,d._getFirstRowSibling(e)),p.innerHTML=d.noDataMessage);for(p=e=0;p<h;p++)e+=d._calcRowHeight(b[p]);h&&e&&(d.rowHeight=e/h);c-=h;k.count=c;m.rowIndex=h;c?m.style.height=Math.min(c*d.rowHeight,d.maxEmptySpace)+"px":(m.style.display="none",
f.count++);d._previousScrollPosition&&(d.scrollTo(d._previousScrollPosition),delete d._previousScrollPosition);d._processScroll();d._refreshDeferred&&(d._refreshDeferred.resolve(a),delete d._refreshDeferred);return b},h)},h),a},refresh:function(c){var f=this,h=c&&c.keepScrollPosition,d;"undefined"===typeof h&&(h=this.keepScrollPosition);h&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this.store)return h=this._refreshDeferred=new t,d=f.renderQuery(function(b){return f.store.query(f.query,
b)}),"undefined"===typeof d&&h.reject(),h.then(function(b){f._refreshTimeout=setTimeout(function(){u.emit(f.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:f,results:b});f._refreshTimeout=null},0);delete f._refreshDeferred;return b},function(b){delete f._refreshDeferred;throw b;})},resize:function(){this.inherited(arguments);this._processScroll()},_getFirstRowSibling:function(c){return c.lastChild},_calcRowHeight:function(c){var f=c.nextSibling;return f&&!/\bdgrid-preload\b/.test(f.className)?
f.offsetTop-c.offsetTop:c.offsetHeight},lastScrollTop:0,_processScroll:function(c){function f(a,c,d,e){var f=b.farOffRemoval,k=a.node;if(c>2*f){for(var g,l=k[d],m=0,n=0,p=[];g=l;){var r=b._calcRowHeight(g);if(m+r+f>c||0>l.className.indexOf("dgrid-row")&&0>l.className.indexOf("dgrid-loading"))break;l=g[d];m+=r;n+=g.count||1;b.removeRow(g,!0);p.push(g)}a.count+=n;e?(k.rowIndex-=n,h(a)):k.style.height=k.offsetHeight+m+"px";var s=q("div",p);setTimeout(function(){q(s,"!")},1)}}function h(a,c){a.node.style.height=
Math.min(a.count*b.rowHeight,c?Infinity:b.maxEmptySpace)+"px"}function d(a,b){do a=b?a.next:a.previous;while(a&&!a.node.offsetWidth);return a}var b=this,k=b.bodyNode;c=c&&c.scrollTop||this.getScrollPosition().y;var k=k.offsetHeight+c,m,e,a=b.preload,y=b.lastScrollTop,s=b.bufferRows*b.rowHeight,u=s-b.rowHeight,v,D,B,p=!0;for(b.lastScrollTop=c;a&&!a.node.offsetWidth;)a=a.previous;for(;a&&a!=m;){m=b.preload;b.preload=a;e=a.node;var g=e.offsetTop;if(k+1+u<g)a=d(a,p=!1);else if(c-1-u>g+e.offsetHeight)a=
d(a,p=!0);else{var l=((e.rowIndex?c-s:k)-g)/b.rowHeight,g=(k-c+2*s)/b.rowHeight,z=Math.max(Math.min((c-y)*b.rowHeight,b.maxRowsPerPage/2),b.maxRowsPerPage/-2),g=g+Math.min(Math.abs(z),10);0==e.rowIndex&&(l-=g);l=Math.max(l,0);10>l&&(0<l&&g+l<b.maxRowsPerPage)&&(g+=Math.max(0,l),l=0);g=Math.min(Math.max(g,b.minRowsPerPage),b.maxRowsPerPage,a.count);if(0==g)a=d(a,p);else{var g=Math.ceil(g),l=Math.min(Math.floor(l),a.count-g),n=C.mixin(b.get("queryOptions"),a.options);a.count-=g;var r=e,A,w=b.queryRowsOverlap;
if(z=(0<e.rowIndex||e.offsetTop>c)&&a){var x=a.previous;x&&(f(x,c-(x.node.offsetTop+x.node.offsetHeight),"nextSibling"),0<l&&x.node==e.previousSibling?(l=Math.min(a.count,l),a.previous.count+=l,h(a.previous,!0),e.rowIndex+=l,w=0):g+=l,a.count-=l);n.start=e.rowIndex-w;n.count=Math.min(g+w,b.maxRowsPerPage);e.rowIndex=n.start+n.count}else a.next&&(f(a.next,a.next.node.offsetTop-k,"previousSibling",!0),r=e.nextSibling,r==a.next.node?(a.next.count+=a.count-l,a.next.node.rowIndex=l+g,h(a.next),a.count=
l,w=0):A=!0),n.start=a.count,n.count=Math.min(g+w,b.maxRowsPerPage);A&&(r&&r.offsetWidth)&&(A=r.offsetTop);h(a);"level"in a.query&&(n.queryLevel=a.query.level);if("queryLevel"in n||!(n.start>b._total||0>n.count)){e=q(r,"-div.dgrid-loading[style\x3dheight:"+g*b.rowHeight+"px]");q(e,"div.dgrid-"+(z?"below":"above")).innerHTML=b.loadingMessage;e.count=g;var E=a.query(n);if(void 0===b._trackError(function(){return E})){q(e,"!");return}(function(a,c,d,e){B=t.when(b.renderArray(e,a,n),function(f){D=e;r=
a.nextSibling;q(a,"!");if(d&&r&&r.offsetWidth){var g=b.getScrollPosition();b.scrollTo({x:g.x,y:g.y+r.offsetTop-d,preserveMomentum:!0})}t.when(e.total||e.length,function(a){"queryLevel"in n||(b._total=a);c&&(c.count=a-c.node.rowIndex,0===c.count&&n.count++,h(c))});b._processScroll();return f},function(b){q(a,"!");throw b;})}).call(this,e,z,A,E);a=a.previous}}}}if(B&&(v=this._refreshDeferred))delete this._refreshDeferred,t.when(B,function(){v.resolve(D)})},removeRow:function(c,f){if(c){var h=c.previousSibling,
d=c.nextSibling,h=h&&(null!=h.observerIndex?h.observerIndex:h.previousObserverIndex),b=d&&(null!=d.observerIndex?d.observerIndex:d.nextObserverIndex),d=c.observerIndex;c.observerIndex=void 0;f&&(c.nextObserverIndex=b,c.previousObserverIndex=h);if(this.cleanEmptyObservers&&(-1<d&&d!==h&&d!==b)&&(h=this.observers,b=h[d])){if(!f)for(var k=b.rows,m=0;m<k.length;m++)if(k[m]!=c&&I.isDescendant(k[m],this.domNode))return this.inherited(arguments);b.cancel();this._numObservers--;h[d]=0}}this.inherited(arguments)}})});
//# sourceMappingURL=OnDemandList.js.map