//>>built
define("dgrid/TouchScroll","dojo/_base/declare dojo/on ./util/touch ./util/has-css3 put-selector/put xstyle/css!./css/TouchScroll.css".split(" "),function(H,s,v,q,h){function w(c,a,d,e){e=c.touchNode;var b=n[c.id],m,f,k;if("object"!==typeof a)k=a,a=d,d=f=!0;else{d="x"in a;f="y"in a;if(!d||!f)m=c.getScrollPosition();k=d?a.x:m.x;a=f?a.y:m.y}e.style[g]=l+-k+"px,"+-a+"px"+p;b&&(d&&c._scrollbarXNode)&&(c._scrollbarXNode.style[g]=l+k*b.parentWidth/b.scrollWidth+"px,0"+p);b&&(f&&c._scrollbarYNode)&&(c._scrollbarYNode.style[g]=
l+"0,"+a*b.parentHeight/b.scrollHeight+"px"+p);s.emit(c.touchNode.parentNode,"scroll",{scrollLeft:k,scrollTop:a})}function z(c){return n[c.id]?I.exec(window.getComputedStyle(c.touchNode)[g]):x.exec(c.touchNode.style[g])}function J(c){var a=this.widget,a=[this.node,a._scrollbarXNode,a._scrollbarYNode],d=a.length;this.timer&&(clearTimeout(this.timer),this.timer=null);for(this.transitionHandler&&this.transitionHandler.remove();d--;)a[d]&&(a[d].style[r+"Duration"]="0");(!c||!c.preserveScrollbars)&&h(this.node.parentNode,
".touchscroll-fadeout");delete this.resetEffects}function K(c){var a=c.widget,d=a.touchNode,e=a.id,b=0,m=0,f;if(v.countCurrentTouches(c,d)===a.touchesToScroll){if(f=z(a))b=+f[1],m=+f[2];if(f=n[e])f.resetEffects&&f.resetEffects({preserveScrollbars:!0}),d.style[g]=l+b+"px,"+m+"px"+p,t[e]=f;c=c.targetTouches[0];f=n[e]={widget:a,node:d,startX:b-c.pageX,startY:m-c.pageY,lastX:b,lastY:m,pageX:c.pageX,pageY:c.pageY,tickFunc:function(){var a=n[e],c,b;a&&(c=a.node,(b=x.exec(c.style[g]))?(c=+b[1],b=+b[2],a.velX=
c-a.lastX,a.velY=b-a.lastY,a.lastX=c,a.lastY=b):a.lastX=a.lastY=0,a.timer=setTimeout(a.tickFunc,A))}};f.timer=setTimeout(f.tickFunc,A)}}function L(c){var a=c.widget,d=a.id,e=a.touchesToScroll,b=n[d],m,f;if(!b||(m=v.countCurrentTouches(c,a.touchNode))!==e)m>e&&a.cancelTouchScroll();else{m=c.targetTouches;e=m[0];if(!b.scrollbarsShown&&(t[d]||Math.abs(e.pageX-b.pageX)>a.scrollThreshold||Math.abs(e.pageY-b.pageY)>a.scrollThreshold)){var d=a.touchNode,k=d.parentNode,g=k.offsetWidth-B,l=k.offsetHeight-
B,p=b.scrollWidth=d.scrollWidth,C=b.scrollHeight=d.scrollHeight,q=b.parentWidth=k.offsetWidth,r=b.parentHeight=k.offsetHeight;p>q?(a._scrollbarXNode||(f=h(k,"div.touchscroll-x")),f=a._scrollbarXNode=a._scrollbarXNode||h(f,"div.touchscroll-bar"),f.style.width=g*g/p+"px",f.style.left=d.offsetLeft+"px",h(k,".touchscroll-scrollable-x"),b.scrollableX=!0):h(k,"!touchscroll-scrollable-x");C>r?(a._scrollbarYNode||(f=h(k,"div.touchscroll-y")),f=a._scrollbarYNode=a._scrollbarYNode||h(f,"div.touchscroll-bar"),
f.style.height=l*l/C+"px",f.style.top=d.offsetTop+"px",h(k,".touchscroll-scrollable-y"),b.scrollableY=!0):h(k,"!touchscroll-scrollable-y");h(k,"!touchscroll-fadeout");b.scrollbarsShown=!0;for(f=m.length;f--;)m[f].touchScrolled=!0}if(b.scrollbarsShown&&(b.scrollableX||b.scrollableY))c.preventDefault(),c=b.scrollableX?b.startX+e.pageX:0,e=b.scrollableY?b.startY+e.pageY:0,f=b.scrollableX?-(b.scrollWidth-b.parentWidth):0,b=b.scrollableY?-(b.scrollHeight-b.parentHeight):0,0<c?c/=2:c<f&&(c=f-(f-c)/2),0<
e?e/=2:e<b&&(e=b-(b-e)/2),w(a,-c,-e)}}function M(c){var a=c.widget,d=a.id;n[d]&&v.countCurrentTouches(c,a.touchNode)==a.touchesToScroll-1&&N(d)}function D(c,a,d){function e(){delete b.transitionHandler;b.resetEffects();delete n[c]}var b=n[c],m=b.widget,f=b.node,k=b.scrollableX?Math.max(Math.min(0,a),-(b.scrollWidth-b.parentWidth)):a,h=b.scrollableY?Math.max(Math.min(0,d),-(b.scrollHeight-b.parentHeight)):d;delete b.timer;k!=a||h!=d?(b.transitionHandler=s.once(f,O,e),f.style[r+"Duration"]=m.bounceDuration+
"ms",f.style[g]=l+k+"px,"+h+"px"+p,k!=a&&b.scrollableX&&(f=b.widget._scrollbarXNode,f.style[r+"Duration"]=m.bounceDuration+"ms",f.style[g]=a>k?l+"0,0"+p:l+(f.parentNode.offsetWidth-f.offsetWidth)+"px,0"+p),h!=d&&b.scrollableY&&(f=b.widget._scrollbarYNode,f.style[r+"Duration"]=m.bounceDuration+"ms",f.style[g]=d>h?l+"0,0"+p:l+"0,"+(f.parentNode.offsetHeight-f.offsetHeight)+"px"+p)):e()}function N(c){var a=n[c],d=t[c],e,b;delete t[c];a.timer&&clearTimeout(a.timer);a.resetEffects=J;(e=x.exec(a.node.style[g]))?
(b=+e[1],e=+e[2]):b=e=0;if(!a.velX&&!a.velY||(0<=b||b<=-(a.scrollWidth-a.parentWidth))&&(0<=e||e<=-(a.scrollHeight-a.parentHeight)))D(c,b,e);else{if(d&&(d.velX||d.velY)&&(0>=a.velX&&0>=d.velX||0<=a.velX&&0<=d.velX)&&(0>=a.velY&&0>=d.velY||0<=a.velY&&0<=d.velY))a.velX=1.15*(a.velX+d.velX),a.velY=1.15*(a.velY+d.velY);a.lastX=b;a.lastY=e;a.calcFunc=function(){var a=n[c],b,d,e,g,h,l;if(a)if(b=a.widget,h=b.glideDecel(a.velX),l=b.glideDecel(a.velY),Math.abs(h)>=E||Math.abs(l)>=E){e=a.lastX+h;g=a.lastY+
l;if(0<e||e<-(a.scrollWidth-a.parentWidth))for(d=6;d--;)h=b.glideDecel(h);if(0<g||g<-(a.scrollHeight-a.parentHeight))for(d=6;d--;)l=b.glideDecel(l);w(b,-e,-g);a.lastX=e;a.lastY=g;a.velX=h;a.velY=l;a.timer=setTimeout(a.calcFunc,F)}else D(c,a.lastX,a.lastY)};a.timer=setTimeout(a.calcFunc,F)}}var A=50,F=30,n={},t={},E=1,B=8,x=/^translate(?:3d)?\((-?\d+)(?:\.\d*)?(?:px)?, (-?\d+)/,I=/^matrix\(1, 0, 0, 1, (-?\d+)(?:\.\d*)?(?:px)?, (-?\d+)/,y=q("css-transitions"),O=q("transitionend"),u=q("css-transforms");
q=q("css-transforms3d");var G,r,g,l,p;q?(l="translate3d(",p=",0)"):u&&(l="translate(",p=")");if(!y||!l)return function(){};g=q||u;g=!0===g?"transform":g+"Transform";r=!0===y?"transition":y+"Transition";G=!0===u?"":"-"+u.toLowerCase()+"-";return H(null,{touchesToScroll:1,touchNode:null,scrollThreshold:10,bounceDuration:300,postCreate:function(){this._initTouch();this.inherited(arguments)},_initTouch:function(){function c(){e.cancelTouchScroll()}function a(a){return function(b){b.widget=e;b.cancelTouchScroll=
c;a.call(this,b)}}var d=this.touchNode=this.touchNode||this.containerNode,e=this,b;d&&d.parentNode&&(b=d.parentNode,b.style.overflow="hidden",d.style[r+"Property"]=G+"transform",d.style[r+"TimingFunction"]="cubic-bezier(0.33, 0.66, 0.66, 1)",this._touchScrollListeners=[s(b,"touchstart",a(K)),s(b,"touchmove",a(L)),s(b,"touchend,touchcancel",a(M))])},destroy:function(){for(var c=this._touchScrollListeners.length;c--;)this._touchScrollListeners[c].remove();delete n[this.id];this.inherited(arguments)},
scrollTo:function(c){var a=n[this.id],d=this.touchNode,e=d.parentNode;!c.preserveMomentum&&(a&&a.resetEffects)&&a.resetEffects();c.x&&(c.x=Math.max(0,Math.min(c.x,d.scrollWidth-e.offsetWidth)));c.y&&(c.y=Math.max(0,Math.min(c.y,d.scrollHeight-e.offsetHeight)));w(this,c)},getScrollPosition:function(){var c=z(this);return c?{x:-c[1],y:-c[2]}:{x:0,y:0}},cancelTouchScroll:function(){var c=n[this.id];c&&(c.resetEffects?c.resetEffects():(c.timer&&clearTimeout(c.timer),h(c.node.parentNode,".touchscroll-fadeout")),
delete n[this.id])},glideDecel:function(c){return 0.9*c}})});
//@ sourceMappingURL=TouchScroll.js.map