//>>built
define("dgrid/tree","dojo/_base/declare dojo/_base/array dojo/_base/Deferred dojo/query dojo/on dojo/aspect ./util/has-css3 ./Grid dojo/has!touch?./util/touch put-selector/put".split(" "),function(C,z,r,u,A,e,v,B,w,g){function x(c,e,h,f){f=this.grid.isRTL?"right":"left";var b=".dgrid-expando-icon";e&&(b+=".ui-icon.ui-icon-triangle-1-"+(h?"se":"e"));c=g("div"+b+"[style\x3dmargin-"+f+": "+c*(this.indentWidth||9)+"px; float: "+f+"]");c.innerHTML="\x26nbsp;";return c}function y(c){var e=this,h=this.style.height;
h&&(this.style.display="0px"==h?"none":"block");c&&(g(this,".dgrid-tree-resetting"),setTimeout(function(){g(e,"!dgrid-tree-resetting")}));this.style.height=""}function m(c){var m=c.renderCell||B.defaultRenderCell,h,f;c||(c={});c.shouldExpand=c.shouldExpand||function(b,c,d){return d};e.after(c,"init",function(){var b=c.grid,n=".dgrid-content .dgrid-column-"+c.id,d=[];b.cleanEmptyObservers=!1;if(!b.store)throw Error("dgrid tree column plugin requires a store to operate.");c.renderExpando||(c.renderExpando=
x);d.push(b.on(c.expandOn||".dgrid-expando-icon:click,"+n+":dblclick,"+n+":keydown",function(a){var c=b.row(a);(!b.store.mayHaveChildren||b.store.mayHaveChildren(c.data))&&(("keydown"!=a.type||32==a.keyCode)&&!("dblclick"==a.type&&f&&1<f.count&&c.id==f.id&&-1<a.target.className.indexOf("dgrid-expando-icon")))&&b.expand(c);-1<a.target.className.indexOf("dgrid-expando-icon")&&(f&&f.id==b.row(a).id?f.count++:f={id:b.row(a).id,count:1})}));v("touch")&&d.push(b.on(w.selector(n,w.dbltap),function(){b.expand(this)}));
b._expanded||(b._expanded={});d.push(e.after(b,"insertRow",function(a){var b=this.row(a);c.shouldExpand(b,h,this._expanded[b.id])&&this.expand(a,!0,!0);return a}));d.push(e.before(b,"removeRow",function(a,c){var d=a.connected;d&&(u("\x3e.dgrid-row",d).forEach(function(a){b.removeRow(a,!0)}),c||g(d,"!"))}));c.collapseOnRefresh&&d.push(e.after(b,"cleanup",function(){this._expanded={}}));b._calcRowHeight=function(a){var b=a.connected;return a.offsetHeight+(b?b.offsetHeight:0)};b.expand=function(a,d,
f){var k=a.element?a:b.row(a),e=v("transitionend");a=new r;var h=a.promise;a.resolve();a=k.element;a=-1<a.className.indexOf("dgrid-expando-icon")?a:u(".dgrid-expando-icon",a)[0];f=f||!1===c.enableTransitions;if(a&&a.mayHaveChildren&&(f||d!==!!this._expanded[k.id])){var p=void 0===d?!this._expanded[k.id]:d;g(a,".ui-icon-triangle-1-"+(p?"se":"e")+"!ui-icon-triangle-1-"+(p?"e":"se"));d=k.element;var l=d.connected,q,n,m={originalQuery:this.query};if(!l){var l=m.container=d.connected=g(d,"+div.dgrid-tree-container"),
t=function(a){return b.store.getChildren(k.data,a)};c.allowDuplicates&&(m.parentId=k.id);"level"in a&&(t.level=a.level);h=h.then(function(){if(b.renderQuery)return b.renderQuery(t,m);var a=g(l,"div"),c=b.renderArray(t(m),a,"level"in t?{queryLevel:t.level}:{});r.when(c,function(){g(a,"!")});return c});e?A(l,e,y):y.call(l)}l.hidden=!p;q=l.style;!e||f?(q.display=p?"block":"none",q.height=""):(p?(q.display="block",n=l.scrollHeight,q.height="0px"):(g(l,".dgrid-tree-resetting"),q.height=l.scrollHeight+
"px"),setTimeout(function(){g(l,"!dgrid-tree-resetting");q.height=p?n?n+"px":"auto":"0px"}));p?this._expanded[k.id]=!0:delete this._expanded[k.id]}return h};e.after(c,"destroy",function(){z.forEach(d,function(a){a.remove()});delete b.expand;delete b._calcRowHeight})});c.renderCell=function(b,f,d,a){var e=c.grid,s=Number(a&&a.queryLevel)+1,k=!e.store.mayHaveChildren||e.store.mayHaveChildren(b),r=a.parentId,s=h=isNaN(s)?0:s,e=c.renderExpando(s,k,e._expanded[(r?r+"-":"")+e.store.getIdentity(b)],b);e.level=
s;e.mayHaveChildren=k;(b=m.call(c,b,f,d,a))&&b.nodeType?(g(d,e),g(d,b)):d.insertBefore(e,d.firstChild)};return c}m.defaultRenderExpando=x;return m});
//# sourceMappingURL=tree.js.map