//>>built
define("xstyle/core/base","xstyle/core/elemental xstyle/core/expression xstyle/core/Definition xstyle/core/utils put-selector/put xstyle/core/Rule dojo/Deferred".split(" "),function(m,g,r,k,v,h,z){function l(b,a,e){function c(a){return{selectElement:function(d){e.newElement&&(d=d.parentNode);if(a&&a.selector)for(;!s(d,a);)if(d=d.parentNode,!d)throw Error("Rule not found");if(e.inherit)for(;!(b in d);)if(d=d.parentNode,!d)throw Error(b?b+" not found":"Property was never defined");return d},forElement:function(d){var c=
d;d=this.selectElement(d);e.newElement&&(d["_"+b+"Node"]=c);d=e.get?e.get(d,b):d[b];return void 0===d&&a?n(b).valueOf().forRule(a):d},forRule:e.inherit&&function(b){return c(b)}}}var f=new r(function(){return c(a)});f.define=function(a,d){return l(b||d,a,e)};f.keepCSSValue=!0;f.put=e.inherit?function(a,e){return n(b).put(a,e,b)}:function(c){return{forElement:function(d){if(a&&a.selector)for(;!s(d,a);)if(d=d.parentNode,!d)throw Error("Rule not found");e.set?e.set(d,b,c):d[b]=c;f.invalidate({elements:[d]})}}};
return f}function A(b,a,e,c){return k.when(g.evaluate(b,e),function(a){a.forElement?m.addRenderer(b,function(b){c(a.forElement(b),b)}):c(a)})}function t(b,a){return{apply:function(e,c,f){A(e,f,c[0],function(c,d){c.observe(function(c){c=c?b:a;value.toString().replace(RegExp(b+"\\([^)]+\\)","g"),c);d?d.style[f]=c:e.setStyle(f,c)})})}}}function w(b,a){var e=b.variables;if(e&&a in e)return e[a];if(e=b.bases)for(var c=0;c<e.length;c++){var f=w(e[c],a);if(void 0!==f)return f}}function n(b){var a=x[b];a||
(a=x[b]=new r(function(){return{forRule:function(a){a:{do{var c=w(a,b);if(void 0!==c){a=c;break a}a=a.parent}while(a);a=void 0}return a}}}),a.put=function(b,c,f){return{forRule:function(c){function d(a){g.push(a);for(var b in a.rules)d(a.rules[b])}(c.variables||(c.variables={}))[f]=b;for(var g=[];c;)d(c),c=c.parent;a.invalidate({rules:g})}}});return a}var u=v("div"),p=navigator.userAgent,y=-1<p.indexOf("WebKit")?"-webkit-":-1<p.indexOf("Firefox")?"-moz-":-1<p.indexOf("MSIE")?"-ms-":-1<p.indexOf("Opera")?
"-o-":"",q;h=new h;var s=m.matchesRule;h.root=!0;var x={};h.definitions={Math:Math,window:window,global:window,module:g.selfResolving(function(b,a){b[0].value&&(b=b[0].value);a||require([b]);return{then:function(a){var c=new z;require([b],function(b){c.resolve(a(b))});return c.promise}}}),item:l("item",null,{inherit:!0}),pageContent:new r,content:l("content",null,{inherit:!0,newElement:function(){return this.element}}),elementProperty:l(null,null,{}),elementClass:l(null,null,{get:function(b,a){return-1<
(" "+b.className+" ").indexOf(" "+a+" ")},set:function(b,a,e){this.get(b,a)!=e&&(b.className=e?b.className+(" "+a):(" "+b.className+" ").replace(" "+a+" ","").replace(/^ +| +$/g,""))}}),element:{forElement:function(b){return b},define:function(b){return{forElement:function(a){for(;!s(a,b);)if(a=a.parentNode,!a)throw Error("Rule not found");return a}}}},event:{observe:function(b){b(q)},valueOf:function(){return q}},each:{put:function(b){return{forRule:function(a){a.each=b}}}},prefix:{put:function(b,
a,e){return{forRule:function(a){if("string"==typeof u.style[y+e])return a._setStyleFromValue(y+e,b),!0}}}},"var":{define:function(b,a){return n(a)},selfResolving:!0,apply:function(b,a){return n(k.convertCssNameToJs(a[0]))}},inline:t("inline","none"),block:t("block","none"),visible:t("visible","hidden"),"extends":{apply:function(b,a){for(;0<a.length;)return k.extend(b,a[0],console.error)}},set:{selfExecuting:!0,apply:function(b,a){return a[0].put(a[1].valueOf())}},get:{apply:function(b,a){return a[0]},
put:function(b,a){g.evaluate(a,b)}},toggle:{selfExecuting:!0,apply:function(b,a){return a[0].put(!a[0].valueOf())}},on:{put:function(b,a,e){return{forRule:function(a){m.on(document,m.on.selector(a.selector,e.charAt(2).toLowerCase()+e.slice(3)),function(e){q=e;try{k.when(g.evaluate(a,b).valueOf(),function(b){b&&b.forRule&&(b=b.forRule(a));b&&b.forElement&&b.forElement(e.target);q=null},function(a){})}catch(h){}})}}}},title:{put:function(b){return{forRule:function(a){g.observe(g.evaluate(a,b),function(a){document.title=
a})}}}},"@supports":{selector:function(b){function a(b){var c;if(c=b.match(/^\s*not(.*)/))return!a(c[1]);if(c=b.match(/\((.*)\)/))return a(c[1]);if(c=b.match(/([^:]*):(.*)/))return b=k.convertCssNameToJs(c[1]),c=u.style[b]=c[2],u.style[b]==c;if(c=b.match(/\w+\[(.*)=(.*)\]/))return v(c[0])[c[1]]==c[2];if(c=b.match(/\w+/))return k.isTagSupported(c);throw Error("can't parse @supports string");}a(b.selector.slice(10))?b.selector="":b.disabled=!0}},"true":!0,"false":!1,"null":null};h.elementProperty=l;
return h});
//# sourceMappingURL=base.js.map