//>>built
define("xstyle/core/generate",["xstyle/core/elemental","put-selector/put","xstyle/core/utils","xstyle/core/expression","xstyle/core/base"],function(z,q,D,A,I){function n(a,d){a=a.sort?a:[a];return function(c,k,f){var b=c,w;"content"in c||(c.content=void 0);if(void 0===f){var e=(c._contentNode||c).childNodes||0,g=e[0];if(g){var s=p.createDocumentFragment();do s.appendChild(g);while(g=e[0]);c.content=s}if(c._contentNode){c._contentNode=void 0;try{c.innerHTML=""}catch(B){}}}for(var E=0,F=[c],x=[],e=
0,g=a.length;e<g;e++){var G=h,h=a[e];try{if(h.eachProperty)if(h.args)if("("==h.operator){var n=a[e+1];H(h,n,b,function(a,b,c){J(a,b,c,d)})}else{var r=h.args[0];if("string"===typeof r){var t=r.split("\x3d");try{b.setAttribute(t[0],t[1])}catch(C){}}else{var m=r[0].replace(/=$/,""),u=r[1];"("==u.operator?H(r[1],m,b,function(a,b,c){K(a,b,c,d)}):b.setAttribute(m,u.value)}}else q(b,h.selector),x.push(h.selector,b);else if("string"==typeof h){"\x3d"==h.charAt(0)&&(h=h.slice(1));var l=b,n=a[e+1],t=[];h.replace(/([,\n]+)?([\t ]*)?(\.|#)?([-\w%$|\.\#]+)(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,
function(){t.push(arguments)});for(var y=0;y<t.length;y++)(function(a,g,h,e,s,p,B){function r(){var a=l._contentNode;a&&(a.innerHTML="",l=a)}g?(a=h?h.length:0,a>E?(r(),F[a]=l):l=F[a]||l,E=a):r();var m;if(e)m=(G&&G.args?"":"span")+e+s;else{e=s.match(/^[-\w]+/)[0];var v=d.getDefinition(e);v&&(v.then||v.newElement)?l=function(a,b,c,f){var d,e;D.when(v&&v.newElement&&v.newElement(),function(a){(d=a)?(c=c.slice(f.length))&&q(d,c):d=q(c);if(e){e.parentNode.replaceChild(d,e);a=e.childNodes;var b;for(d=d._contentNode||
d;b=a[0];)d.appendChild(b)}});if(d)return a.insertBefore(d,b||null);e=q("span");return a.insertBefore(e,b||null)}(l,f,s,e):m=s}m&&(l=q(f||l,(f?"-":"")+m));f=null;p&&l.setAttribute(p,""===B?p:B);k&&(l.item=k);w=w||l;(y<t.length-1||l!=b&&l!=c&&(!n||!n.base))&&x.push(null,l);b=l}).apply(this,t[y])}else b.appendChild(p.createTextNode(h.value))}catch(A){b.innerHTML&&(b.innerHTML=""),b.appendChild(p.createTextNode(A))}}for(;h=x.pop();)z.update(h,x.pop());return w}}function H(a,d,c,k){var f,b;d&&d.eachProperty?
(q(c,f=d.selector),b=d):(q(c,f=a.selector||(a.selector=".-xbind-"+L++)),b=a);var w=a.getArgs()[0],e=a.expressionResult,g=a.expressionDefinition;g||(g=a.expressionDefinition=A.evaluate(a.parent,w),e=g.valueOf(),z.addInputConnector(b,g),function(c,d,f){a.expressionResult=e;f.depend&&f.depend({invalidate:function(a){a=a?z.matchesRule(a.elements[0],b)?a.elements:a.elements[0].querySelectorAll(d):document.querySelectorAll(d);for(var e=0,g=a.length;e<g;e++)k(a[e],c,f.valueOf())}})}(d,f,g));k(c,d,e)}function C(a,
d,c,k){return D.when(a,function(a){a&&a.forRule&&(a=a.forRule(d));a&&a.forElement&&(a=a.forElement(c));k(a)})}function K(a,d,c,k){C(c,k,a,function(c){a.setAttribute(d,c)})}function J(a,d,c,k){a._defaultBinding=!0;if(c&&c.then&&"INPUT"!==a.tagName)try{a.appendChild(p.createTextNode("Loading"))}catch(f){}C(c,k,a,function(b){if(a._defaultBinding)if(m(a),a.childNodes.length&&(a.innerHTML=""),b&&b.sort)if(b.isSequence)n(b,k)(a);else{var c=d&&d.eachProperty&&d.each,e=k.newRule(),c=c?n(c,e):function(a,b,
c){return q(c||a,(c?"-":"")+(M[a.tagName]||"span"),""+b)},g=[],f;b.track&&(b=b.track(),f=b.tracking);b.forEach(function(b){g.push(c(a,b,null))});if(b.on)var u=b.on("add,delete,update",function(b){var d=b.target,e=b.previousIndex;b=b.index;if(-1<e){var f=g[e];m(f,!0);f.parentNode.removeChild(f);g.splice(e,1)}-1<b&&g.splice(b,0,c(a,d,g[b]||null))});if(f=f||u)a.xcleanup=function(){f.remove()}}else b&&b.nodeType?a.appendChild(b):(b=void 0===b?"":b,a.tagName in N?"checkbox"===a.type?a.checked=b:a.value=
b:a.appendChild(p.createTextNode(b)))})}function m(a,d){a.xcleanup&&a.xcleanup(d);for(var c=a.getElementsByTagName("*"),k=0,f=c.length;k<f;k++){var b=c[k];b.xcleanup&&b.xcleanup(!0)}}function u(a,d){return n(d,I)(a)}var M={TABLE:"tr",TBODY:"tr",TR:"td",UL:"li",OL:"li",SELECT:"option"},N={INPUT:1,TEXTAREA:1,SELECT:1},p=document,L=1;u.forSelector=n;return u});
//# sourceMappingURL=generate.js.map