//>>built
define("xstyle/core/parser",["xstyle/core/utils"],function(Q){function M(){this.push.apply(this,arguments)}function G(c){this.value=c}function R(){var c,h=this.args[0];if("string"==typeof h)c=h.split(/\s*,\s*/);else if(h){c=[];for(var q=0,r=0;r<h.length+1;r++){var s=h[r];if("string"==typeof s||void 0===s)if(s=s&&s.split(/\s*,\s*/),1<c.length||void 0===s){var l=h.slice(q,r);0<q&&l.unshift(c.pop());q=r+1;c.push(l);s&&c.push.apply(c,s.slice(1))}}}else return[];return c}function N(c,h,q){function r(h,
u){function q(a){B=!1;var c=l.lastIndex;a.then(function(){B=!0;e&&(l.lastIndex=c,A())});var e=!0}function A(){function c(a){a&&("string"==typeof a&&O)&&(a=O+a);b?b.push?"string"==typeof b[b.length-1]&&"string"==typeof a?b[b.length-1]+=a:a&&b.push(a):"string"==typeof b&&"string"==typeof a?b+=a:b=new M(b,a):b=a}for(B=!0;B;){var v=l.exec(h);if(!v)break;var e=v[5],O=v[1],d=v[2],n=v[3],g=v[4],k,p,b,H,g=g&&I(g),d=d&&I(d);z?(n?(p=d,k=n.charAt(0),H="?"==n.charAt(1),-1<n.indexOf("\n")&&(g=n.slice(1))):g=d,
b=g,z=!1):(g=n?d+n:d,c(g));"{"!=e&&(m+=v[0]);switch(e){case "'":case '"':var C="'"==e?S:T;C.lastIndex=l.lastIndex;(e=C.exec(h))||w("unterminated string");d=e[1].replace(/\\([a-fA-F\d]{0,5}[ a-fA-F\d]?)/g,function(a,b){if(b)return String.fromCharCode(parseInt(b,16))});l.lastIndex=C.lastIndex;c(new G(d));m+=e[0];continue;case "\\":e=C.lastIndex++;c(h.charAt(e));continue;case "(":case "{":case "[":var f,J=!1;if("{"==e){z=!0;":"==k&&n&&(d+=n);m=I((m+d).replace(/\s+/g," "));c(f=a.newRule(m));"\x3d"==k&&
(D=!1,b.creating=!0,g&&g.match(/^\w/)&&(J=!0));":"==k&&!a.root&&(b.creating=!0);var x=null,L=E;if(v[6]&&(n=u.cssRules||u.rules,f.cssRule=x=n[v[6].slice(1)]))m=x.selectorText;if(a.root&&D)for(n=u.cssRules||u.rules;x=n[E++];)if(x.selectorText==m||x.selectorText&&x.selectorText.replace(/::/g,":").replace(/'/g,'"')==m.replace(/::/g,":").replace(/'/g,'"')){f.cssRule=x;break}x||(f.ruleIndex=E=L);f.styleSheet=u;b.creating?(f.selector="."+("\x3d"==k?d.match(/[\w-]*$/g,"")[0]:"")+"-x-"+U++,J=f.creating=!0):
f.selector=a.root?m:a.selector+" "+m;m=""}else d=g.match(/(.*?)([\w-]*)$/),c(f=a.newCall(d[2],b,a)),f.ref=a.getDefinition(d[2]),f.getArgs=R,(b.calls||(b.calls=[])).push(f);J&&g.replace(/(?:^|\s+)([\w-\.]+)\s*$/g,function(a,b){var c=Q.extend(f,b,w);c&&c.then&&q(c)});a.currentName=p;a.currentSequence=b;a.assignmentOperator=k;var F;if("{"==e&&(F=f.selector.match(/[@:]\w+/)))F=F[0],(p=a.getDefinition(F))&&p.selector&&p.selector(f);t.push(a=f);a.operator=e;a.start=l.lastIndex;b=p=null;continue}if(b)if(d=
"string"==typeof b?b:b[0],d.charAt&&"@"==d.charAt(0))if(g=d.match(/\w+/)[0],"import"==g)d=N.getStyleSheet((u.cssRules||u.imports)[E++],b,u),g=l.lastIndex,r(d.localSource,d),l.lastIndex=g;else{if("xstyle"==g){if("start"==d.slice(8,13))f=a?a.newRule(""):P,f.root=a.root,t.push(a=f);else{var P=a||P;t.pop();a=t[t.length-1]}l=a?s:/(@[\w\s])/g}}else if(k)try{var y=a[":"==k?"setValue":"declareDefinition"](p,b,H);y&&y.then&&q(y)}catch(V){w(V)}switch(e){case ":":"\x3d"==k?(z=!0,k=":"):c(":");break;case "}":case ")":case "]":W[a.operator]!=
e&&w("Incorrect opening operator "+a.operator+" with closing operator "+e);p=null;p=h.slice(a.start,l.lastIndex-1);a.cssText=a.cssText?a.cssText+";"+p:p;if("}"==e){"}"==K&&(K=a.parent.selector)&&"@"==!K.charAt(0)&&w("A nested rule must end with a semicolon");if(a.root)w("Unmatched "+e);else{try{a.onRule(a.selector,a)}catch(X){w(X)}D=!0}m=""}if(")"==e&&!k){a.args=[b];try{y=t[t.length-2].onArguments(a)}catch(Y){w(Y)}y&&y.then&&q(y)}t.pop();a=t[t.length-1];b=a.currentSequence;p=a.currentName;k=a.assignmentOperator;
if(a.root&&"}"==e){if(k)try{a[":"==k?"setValue":"declareDefinition"](p,b[1]||b,H)}catch(Z){w(Z)}z=!0;k=!1}break;case "":case void 0:return;case ";":b=null,z=!0,k=D=!1,m=""}var K=e}}function w(a){var c=(u.href||"in-page stylesheet")+":"+h.slice(0,l.lastIndex).split("\n").length;if(r.onerror)r.onerror(a,c)}h=h.replace(L,function(a){return a.replace(/[^\n]/g,"")});var a=c;l.lastIndex=0;var B,E=0,D=!0,m="",z=!0;A()}q=q||{addRule:function(){},cssRules:[]};var s,l=s=/(\s*)((?:[^{\}\[\]\(\)\\'":=;]|\[(?:[^\]'"]|'(?:\\.|[^'])*'|"(?:\\.|[^"])*")\])*)([=:]\??\s*([^{\}\[\]\(\)\\'":;]*))?(?:([{\}\[\]\(\)\\'":;])(\/\d+)?|$)/g,
t=[c];c.parse=r;r(h,q)}var S=/((?:\\.|[^'])*)'/g,T=/((?:\\.|[^"])*)"/g,L=/\/\*[\w\W]*?\*\//g,W={"{":"}","[":"]","(":")"},U=0,I="".trim?function(c){return c.trim()}:function(c){return c.replace(/^\s+|\s+$/g,"")},A=M.prototype=[];A.toString=function(){return this.join("")};A.isSequence=!0;G.prototype.toString=function(){return'"'+this.value.replace(/["\\\n\r]/g,"\\$\x26")+'"'};G.prototype.isLiteralString=!0;return N});
//# sourceMappingURL=parser.js.map