//>>built
define("dstore/Trackable","dojo/_base/lang dojo/_base/declare dojo/aspect dojo/when dojo/promise/all dojo/_base/array dojo/on".split(" "),function(B,x,F,z,p,C,G){function D(g,l,s){for(var q=g.length-1;0<=q;--q){var m=g[q],w=m.start,m=w+m.count;if(l>m){g.splice(q+1,0,{start:l,count:s-l});return}s>=w&&(l=Math.min(l,w),s=Math.max(s,m),g.splice(q,1))}g.unshift({start:l,count:s-l})}var H=0,A={track:function(){function g(){return function(){var c=this,a=this.inherited(arguments);z(a,function(a){a=c._results=
a.slice();c._partialResults&&(c._partialResults=null);c._ranges=[];D(c._ranges,0,a.length)});return a}}function l(){return function(c){var a=this,d=c.start,e=c.end,b=this.inherited(arguments);this._results||z(b,function(b){return z(b.totalLength,function(c){var h=a._partialResults||(a._partialResults=[]);e=Math.min(e,d+b.length);h.length=c;c=[d,e-d].concat(b);h.splice.apply(h,c);D(a._ranges,d,e);return b})});return b}}function s(c,a){H++;var d=a.target;a=B.delegate(a,A[c]);z(r._results||r._partialResults,
function(e){if(e){var b,f,g,h=r._ranges,k,l="id"in a?a.id:q.getIdentity(d),m=-1,t=-1,n=-1,u=-1;if("delete"===c||"update"===c)for(b=0;-1===m&&b<h.length;++b){k=h[b];f=k.start;for(g=f+k.count;f<g;++f)if(q.getIdentity(e[f])==l){m=a.previousIndex=f;t=b;e.splice(m,1);k.count--;for(f=b+1;f<h.length;++f)h[f].start--;break}}if("add"===c||"update"===c){if(y){if(y([d]).length){var v=0;g=h.length-1;f=-1;for(var p;v<=g&&-1===n;)b=v+Math.round((g-v)/2),k=h[b],t=e.slice(k.start,k.start+k.count),"beforeId"in a&&
(f=null===a.beforeId?t.length:E(t,a.beforeId)),-1===f&&(f=m>=Math.max(0,k.start-1)&&m<=k.start+k.count?m:q.defaultNewToStart?0:t.length),t.splice(f,0,d),l=C.indexOf(y(t),d),p=k.start+l,0===l&&0!==k.start?g=b-1:l>=t.length-1&&p<e.length?v=b+1:(n=p,u=b);if(-1===n&&0<v&&v<h.length)var s=!0}}else{f=-1;if("beforeId"in a)if(null===a.beforeId)n=e.length,f=h.length-1;else{b=0;for(g=h.length;-1===u&&b<g;++b)k=h[b],n=E(e,a.beforeId,k.start,k.start+k.count),-1!==n&&(u=b)}else"update"===c?(n=m,u=t):q.defaultNewToStart?
f=n=0:(n=e.length,f=h.length-1);-1!==f&&-1===u&&(k=h[f])&&(k.start<=n&&n<=k.start+k.count)&&(u=f)}if(-1<n&&-1<u){a.index=n;e.splice(n,0,d);h[u].count++;for(b=u+1;b<h.length;++b)h[b].start++}else if(s){a.beforeIndex=h[v].start;for(b=v;b<h.length;++b)h[b].start++}}a.totalLength=e.length}(e=r["on_tracked"+c])&&e.call(r,a)})}var q=this.store||this,m=[],w={add:1,update:1,"delete":1},p;for(p in w)m.push(this.on(p,function(c){return function(a){s(c,a)}}(p)));var r=x.safeMixin(B.delegate(this),{_ranges:[],
fetch:g(),fetchRange:l(),releaseRange:function(c,a){if(this._partialResults){a:for(var d=this._ranges,e=0,b;b=d[e];++e){var f=b.start,g=f+b.count;if(c<=f)if(a>=g)d.splice(e,1);else{b.start=a;b.count=g-b.start;break a}else if(c<g)if(a>f){d.splice(e,1,{start:f,count:c-f},{start:a,count:g-a});break a}else b.count=c-b.start}for(d=c;d<a;++d)delete this._partialResults[d]}},on:function(c,a){var d=this,e=this.getInherited(arguments);return G.parse(r,c,a,function(b,c){return c in w?F.after(r,"on_tracked"+
c,a,!0):e.call(d,c,a)})},tracking:{remove:function(){for(;0<m.length;)m.pop().remove();this.remove=function(){}}},track:null});this.fetchSync&&(x.safeMixin(r,{fetchSync:g(),fetchRangeSync:l()}),r.fetchSync());var y;C.forEach(this.queryLog,function(c){var a=y,d=c.querier;d&&(y=a?function(c){return d(a(c))}:d)});var A={add:{index:void 0},update:{previousIndex:void 0,index:void 0},"delete":{previousIndex:void 0}},E=function(c,a,d,e){e=void 0!==e?e:c.length;for(d=void 0!==d?d:0;d<e;++d)if(q.getIdentity(c[d])===
a)return d;return-1};return r}};p=x(null,A);p.create=function(g,l){g=x.safeMixin(B.delegate(g),A);x.safeMixin(g,l);return g};return p});
//# sourceMappingURL=Trackable.js.map