//>>built
define("dojo/i18n","./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),function(n,k,q,w,C,r,z,D,E){q.add("dojo-preload-i18n-Api",1);var u=n.i18n={},F=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,G=function(a,c,b,d){var e=[b+d];c=c.split("-");for(var s="",h=0;h<c.length;h++)if(s+=(s?"-":"")+c[h],!a||a[s])e.push(b+s+"/"+d),e.specificity=s;return e},l={},A=function(a,c,b){b=b?b.toLowerCase():n.locale;a=a.replace(/\./g,"/");c=c.replace(/\./g,"/");
return/root/i.test(b)?a+"/nls/"+c:a+"/nls/"+b+"/"+c},H=n.getL10nName=function(a,c,b){return E.id+"!"+A(a,c,b)},I=function(a,c,b,d,e,s){a([c],function(h){var f=r.clone(h.root||h.ROOT),v=G(!h._v1x&&h,e,b,d);a(v,function(){for(var a=1;a<v.length;a++)f=r.mixin(r.clone(f),arguments[a]);l[c+"/"+e]=f;f.$locale=v.specificity;s()})})},J=function(a){var c=C.extraLocale||[],c=r.isArray(c)?c:[c];c.push(a);return c},y=function(a,c,b){if(q("dojo-preload-i18n-Api")){var d=a.split("*"),e="preload"==d[1];e&&(l[a]||
(l[a]=1,K(d[2],D.parse(d[3]),1,c)),b(1));if(!(d=e))t&&x.push([a,c,b]),d=t;if(d)return}a=F.exec(a);var f=a[1]+"/",h=a[5]||a[4],k=f+h,d=(a=a[5]&&a[4])||n.locale||"",v=k+"/"+d;a=a?[d]:J(d);var p=a.length,g=function(){--p||b(r.delegate(l[v]))};w.forEach(a,function(a){var b=k+"/"+a;q("dojo-preload-i18n-Api")&&m(b);l[b]?g():I(c,k,f,h,a,g)})};if(q("dojo-unit-tests"))var L=u.unitTests=[];q("dojo-preload-i18n-Api");var M=u.normalizeLocale=function(a){a=a?a.toLowerCase():n.locale;return"root"==a?"ROOT":a},
t=0,x=[],K=u._preloadLocalizations=function(a,c,b,d){function e(a,c){d.isXdUrl(k.toUrl(a+".js"))||b?d([a],c):B([a],c,d)}function f(a,c){for(var b=a.split("-");b.length;){if(c(b.join("-")))return;b.pop()}c("ROOT")}function h(){for(--t;!t&&x.length;)y.apply(null,x.shift())}function g(b){b=M(b);f(b,function(p){if(0<=w.indexOf(c,p)){var g=a.replace(/\./g,"/")+"_"+p;t++;e(g,function(a){for(var c in a){var e=a[c],g=c.match(/(.+)\/([^\/]+)$/),m;if(g){m=g[2];g=g[1]+"/";e._localized=e._localized||{};var n;
if("ROOT"===p){var q=n=e._localized;delete e._localized;q.root=e;l[k.toAbsMid(c)]=q}else n=e._localized,l[k.toAbsMid(g+m+"/"+p)]=e;p!==b&&function(a,c,e,g){var p=[],m=[];f(b,function(b){g[b]&&(p.push(k.toAbsMid(a+b+"/"+c)),m.push(k.toAbsMid(a+c+"/"+b)))});p.length?(t++,d(p,function(){for(var d=0;d<p.length;d++)e=r.mixin(r.clone(e),arguments[d]),l[m[d]]=e;l[k.toAbsMid(a+c+"/"+b)]=r.clone(e);h()})):l[k.toAbsMid(a+c+"/"+b)]=e}(g,m,e,n)}}h()});return!0}return!1})}d=d||k;g();w.forEach(n.config.extraLocale,
g)},m=function(){},f={},g=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),B=
function(a,c,b){var d=[];w.forEach(a,function(a){function c(b){b=g(b,m,a,f);b===f?d.push(l[h]=f.result):(b instanceof Error&&(b={}),d.push(l[h]=/nls\/[^\/]+\/[^\/]+$/.test(h)?b:{root:b,_v1x:1}))}var h=b.toUrl(a+".js");if(l[h])d.push(l[h]);else{var k=b.syncLoadNls(a);if(k)d.push(k);else if(z)z.get({url:h,sync:!0,load:c,error:function(){d.push(l[h]={})}});else try{b.getText(h,!0,c)}catch(n){d.push(l[h]={})}}});c&&c.apply(null,d)},m=function(a){for(var c,b=a.split("/"),d=n.global[b[0]],e=1;d&&e<b.length-
1;d=d[b[e++]]);d&&((c=d[b[e]])||(c=d[b[e].replace(/-/g,"_")]),c&&(l[a]=c));return c};u.getLocalization=function(a,c,b){var d;a=A(a,c,b);y(a,!k.isXdUrl(k.toUrl(a+".js"))?function(a,b){B(a,b,k)}:k,function(a){d=a});return d};q("dojo-unit-tests")&&L.push(function(a){a.register("tests.i18n.unit",function(a){var b;b=g("{prop:1}",m,"nonsense",f);a.is({prop:1},b);a.is(void 0,b[1]);b=g("({prop:1})",m,"nonsense",f);a.is({prop:1},b);a.is(void 0,b[1]);b=g("{'prop-x':1}",m,"nonsense",f);a.is({"prop-x":1},b);
a.is(void 0,b[1]);b=g("({'prop-x':1})",m,"nonsense",f);a.is({"prop-x":1},b);a.is(void 0,b[1]);b=g("define({'prop-x':1})",m,"nonsense",f);a.is(f,b);a.is({"prop-x":1},f.result);b=g("define('some/module', {'prop-x':1})",m,"nonsense",f);a.is(f,b);a.is({"prop-x":1},f.result);b=g("this is total nonsense and should throw an error",m,"nonsense",f);a.is(b instanceof Error,!0)})});return r.mixin(u,{dynamic:!0,normalize:function(a,c){return/^\./.test(a)?c(a):a},load:y,cache:l,getL10nName:H})});
//# sourceMappingURL=i18n.js.map