//>>built
define("dojox/editor/plugins/BidiSupport","dojo/_base/declare dojo/_base/array dojo/aspect dojo/_base/lang dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/i18n dojo/NodeList-dom dojo/NodeList-traverse dojo/dom-style dojo/sniff dojo/query dijit dojox dijit/_editor/_Plugin dijit/_editor/range dijit/_editor/plugins/EnterKeyHandling dijit/_editor/plugins/FontChoice ./NormalizeIndentOutdent dijit/form/ToggleButton dojo/i18n!./nls/BidiSupport".split(" "),function(z,q,t,p,l,A,n,B,F,G,h,m,r,H,I,v,s,
w,C,D,E){var y=z("dojox.editor.plugins.BidiSupport",v,{useDefaultCommand:!1,buttonClass:null,iconClassPrefix:"dijitAdditionalEditorIcon",command:"bidiSupport",blockMode:"DIV",shortcutonly:!1,bogusHtmlContent:"\x26nbsp;",buttonLtr:null,buttonRtl:null,_indentBy:40,_lineTextArray:"DIV P LI H1 H2 H3 H4 H5 H6 ADDRESS PRE DT DE TD".split(" "),_lineStyledTextArray:"H1 H2 H3 H4 H5 H6 ADDRESS PRE P".split(" "),_tableContainers:["TABLE","THEAD","TBODY","TR"],_blockContainers:["TABLE","OL","UL","BLOCKQUOTE"],
_initButton:function(){this.shortcutonly||(this.buttonLtr||(this.buttonLtr=this._createButton("ltr")),this.buttonRtl||(this.buttonRtl=this._createButton("rtl")))},_createButton:function(a){return E(p.mixin({label:B.getLocalization("dojox.editor.plugins","BidiSupport")[a],dir:this.editor.dir,lang:this.editor.lang,showLabel:!1,iconClass:this.iconClassPrefix+" "+this.iconClassPrefix+("ltr"==a?"ParaLeftToRight":"ParaRightToLeft"),onClick:p.hitch(this,"_changeState",[a])},this.params||{}))},setToolbar:function(a){this.shortcutonly||
(this.editor.isLeftToRight()?(a.addChild(this.buttonLtr),a.addChild(this.buttonRtl)):(a.addChild(this.buttonRtl),a.addChild(this.buttonLtr)))},updateState:function(){if(this.editor&&(this.editor.isLoaded&&!this.shortcutonly)&&(this.buttonLtr.set("disabled",!!this.disabled),this.buttonRtl.set("disabled",!!this.disabled),!this.disabled)){var a=s.getSelection(this.editor.window);if(a&&0!=a.rangeCount){var b=a.getRangeAt(0);if(b.startContainer===this.editor.editNode&&!b.startContainer.hasChildNodes())a=
b.startContainer;else{a=b.startContainer;b=b.startOffset;if(this._isBlockElement(a))for(;a.hasChildNodes();)b==a.childNodes.length&&b--,a=a.childNodes[b],b=0;a=this._getBlockAncestor(a)}a=h.get(a,"direction");this.buttonLtr.set("checked","ltr"==a);this.buttonRtl.set("checked","rtl"==a)}}},setEditor:function(a){this.editor=a;"P"!=this.blockMode&&"DIV"!=this.blockMode&&(this.blockMode="DIV");this._initButton();this.editor.contentPreFilters.push(this._preFilterNewLines);a=p.hitch(this,function(b){if(this.disabled||
!b.hasChildNodes())return b;this._changeStateOfBlocks(this.editor.editNode,this.editor.editNode,this.editor.editNode,"explicitdir",null);return this.editor.editNode});this.editor.contentDomPostFilters.push(a);this.editor._justifyleftImpl=p.hitch(this,function(){this._changeState("left");return!0});this.editor._justifyrightImpl=p.hitch(this,function(){this._changeState("right");return!0});this.editor._justifycenterImpl=p.hitch(this,function(){this._changeState("center");return!0});this.editor._insertorderedlistImpl=
p.hitch(this,"_insertLists","insertorderedlist");this.editor._insertunorderedlistImpl=p.hitch(this,"_insertLists","insertunorderedlist");this.editor._indentImpl=p.hitch(this,"_indentAndOutdent","indent");this.editor._outdentImpl=p.hitch(this,"_indentAndOutdent","outdent");this.editor._formatblockImpl=p.hitch(this,"_formatBlocks");this.editor.onLoadDeferred.addCallback(p.hitch(this,function(){var b=this.editor._plugins,c,a,e=b.length;c=p.hitch(this,"_changeState","mirror");a=p.hitch(this,"_changeState",
"ltr");var d=p.hitch(this,"_changeState","rtl");this.editor.addKeyHandler("9",1,0,c);this.editor.addKeyHandler("8",1,0,a);this.editor.addKeyHandler("0",1,0,d);for(c=0;c<b.length;c++)if(a=b[c])a.constructor===w?(a.destroy(),e=c):a.constructor===D?(this.editor._normalizeIndentOutdent=!0,this.editor._indentImpl=p.hitch(this,"_indentAndOutdent","indent"),this.editor._outdentImpl=p.hitch(this,"_indentAndOutdent","outdent")):a.constructor===C&&"formatBlock"===a.command&&this.own(t.before(a.button,"_execCommand",
p.hitch(this,"_handleNoFormat")));this.editor.addPlugin({ctor:w,blockNodeForEnter:this.blockMode,blockNodes:/^(?:P|H1|H2|H3|H4|H5|H6|LI|DIV)$/},e);a=this.editor._plugins[e];this.own(t.after(a,"handleEnterKey",p.hitch(this,"_checkNewLine"),!0))}));this.own(t.after(this.editor,"onNormalizedDisplayChanged",p.hitch(this,"updateState"),!0))},_checkNewLine:function(){var a=s.getSelection(this.editor.window).getRangeAt(0),a=s.getBlockAncestor(a.startContainer,null,this.editor.editNode).blockNode;a.innerHTML===
this.bogusHtmlContent&&a.previousSibling?a.style.cssText=a.previousSibling.style.cssText:a.innerHTML!==this.bogusHtmlContent&&(a.previousSibling&&a.previousSibling.innerHTML===this.bogusHtmlContent)&&(a.previousSibling.style.cssText=a.style.cssText)},_handleNoFormat:function(a,b,c){return"noFormat"===c?[a,b,"DIV"]:arguments},_execNativeCmd:function(a,b,c){if(this._isSimpleInfo(c))return a=this.editor.document.execCommand(a,!1,b),m("webkit")&&r("table",this.editor.editNode).prev().forEach(function(b,
c,a){this._hasTag(b,"BR")&&b.parentNode.removeChild(b)},this),a;var f=s.getSelection(this.editor.window);if(!f||0==f.rangeCount)return!1;for(var e=f.getRangeAt(0),d=e.cloneRange(),k=e.startContainer,g=e.startOffset,h=e.endContainer,e=e.endOffset,l=0;l<c.groups.length;l++){var n=c.groups[l],p=n[n.length-1].childNodes.length;d.setStart(n[0],0);d.setEnd(n[n.length-1],p);f.removeAllRanges();f.addRange(d);p=this.editor.selection.getParentOfType(n[0],["TABLE"]);n=this.editor.document.execCommand(a,!1,b);
m("webkit")&&(p&&this._hasTag(p.previousSibling,"BR")&&p.parentNode.removeChild(p.previousSibling),this.editor.focus(),f=s.getSelection(this.editor.window),p=f.getRangeAt(0),0==l?(k=p.endContainer,g=p.endOffset):l==c.groups.length-1&&(h=p.endContainer,e=p.endOffset));if(!n)break;m("webkit")&&this._changeState(a)}f.removeAllRanges();try{d.setStart(k,g),d.setEnd(h,e),f.addRange(d)}catch(q){}return!0},_insertLists:function(a){var b=this._changeState("preparelists",a);if(!this._execNativeCmd(a,null,b))return!1;
(!m("webkit")||this._isSimpleInfo(b))&&this._changeState(a);this._cleanLists();this._mergeLists();return!0},_indentAndOutdent:function(a){if(this.editor._normalizeIndentOutdent)return this._changeState("normalize"+a),!0;var b=this._changeState("prepare"+a);if(m("mozilla")){var c;try{c=this.editor.document.queryCommandValue("styleWithCSS")}catch(f){c=!1}this.editor.document.execCommand("styleWithCSS",!1,!0)}b=this._execNativeCmd(a,null,b);m("mozilla")&&this.editor.document.execCommand("styleWithCSS",
!1,c);if(!b)return!1;this._changeState(a);this._mergeLists();return!0},_formatBlocks:function(a){var b;if(m("mozilla")||m("webkit"))b=this._changeState("prepareformat",a);m("ie")&&(a&&"\x3c"!=a.charAt(0))&&(a="\x3c"+a+"\x3e");if(!this._execNativeCmd("formatblock",a,b))return!1;(!m("webkit")||this._isSimpleInfo(b))&&this._changeState("formatblock",a);this._mergeLists();return!0},_changeState:function(a,b){if(this.editor.window){this.editor.focus();var c=s.getSelection(this.editor.window);if(c&&0!=
c.rangeCount){var f=c.getRangeAt(0),e=f.cloneRange(),d,k,g;d=f.startContainer;c=f.startOffset;k=f.endContainer;g=f.endOffset;f=d===k&&c==g;if(this._isBlockElement(d)||this._hasTagFrom(d,this._tableContainers))for(;d.hasChildNodes();)c==d.childNodes.length&&c--,d=d.childNodes[c],c=0;e.setStart(d,c);d=this._getClosestBlock(d,"start",e);(c=s.getBlockAncestor(d,/li/i,this.editor.editNode).blockNode)&&c!==d&&(d=c);k=e.endContainer;g=e.endOffset;if(this._isBlockElement(k)||this._hasTagFrom(k,this._tableContainers))for(;k.hasChildNodes();)g==
k.childNodes.length&&g--,k=k.childNodes[g],g=k.hasChildNodes()?k.childNodes.length:3==k.nodeType&&k.nodeValue?k.nodeValue.length:0;e.setEnd(k,g);k=this._getClosestBlock(k,"end",e);(c=s.getBlockAncestor(k,/li/i,this.editor.editNode).blockNode)&&c!==k&&(k=c);c=s.getSelection(this.editor.window,!0);c.removeAllRanges();c.addRange(e);c=s.getCommonAncestor(d,k);d=this._changeStateOfBlocks(d,k,c,a,b,e);f&&(k=e.startContainer,g=e.startOffset,e.setEnd(k,g),c=s.getSelection(this.editor.window,!0),c.removeAllRanges(),
c.addRange(e));return d}}},_isBlockElement:function(a){if(!a||1!=a.nodeType)return!1;a=h.get(a,"display");return"block"==a||"list-item"==a||"table-cell"==a},_isInlineOrTextElement:function(a){return!this._isBlockElement(a)&&(1==a.nodeType||3==a.nodeType||8==a.nodeType)},_isElement:function(a){return a&&(1==a.nodeType||3==a.nodeType)},_isBlockWithText:function(a){return a!==this.editor.editNode&&this._hasTagFrom(a,this._lineTextArray)},_getBlockAncestor:function(a){for(;a.parentNode&&!this._isBlockElement(a);)a=
a.parentNode;return a},_getClosestBlock:function(a,b,c){if(this._isBlockElement(a))return a;var f=a.parentNode,e,d,k=!1;for(removeOffset=!1;;){for(var g=a,k=!1;;)if(this._isInlineOrTextElement(g)&&(e=g,d||(d=g)),g=g.previousSibling)if(this._isBlockElement(g)||this._hasTagFrom(g,this._blockContainers)||this._hasTag(g,"BR")){k=!0;break}else{if(3==g.nodeType&&3==g.nextSibling.nodeType&&(g.nextSibling.nodeValue=g.nodeValue+g.nextSibling.nodeValue,"start"==b&&g===c.startContainer?c.setStart(g.nextSibling,
0):"end"==b&&(g===c.endContainer||g.nextSibling===c.endContainer)&&c.setEnd(g.nextSibling,g.nextSibling.nodeValue.length),g=g.nextSibling,g.parentNode.removeChild(g.previousSibling),!g.previousSibling))break}else break;for(g=a;;)if(this._isInlineOrTextElement(g)&&(e||(e=g),d=g),g=g.nextSibling)if(this._isBlockElement(g)||this._hasTagFrom(g,this._blockContainers)){k=!0;break}else if(this._hasTag(g,"BR")&&g.nextSibling&&!this._isBlockElement(g.nextSibling)&&!this._hasTagFrom(g.nextSibling,this._blockContainers)){d=
g;k=!0;break}else{if(3==g.nodeType&&3==g.previousSibling.nodeType&&(g.previousSibling.nodeValue+=g.nodeValue,"start"==b&&g===c.startContainer?c.setStart(g.previousSibling,0):"end"==b&&(g===c.endContainer||g.previousSibling===c.endContainer)&&c.setEnd(g.previousSibling,g.previousSibling.nodeValue.length),g=g.previousSibling,g.parentNode.removeChild(g.nextSibling),!g.nextSibling))break}else break;if(k||this._isBlockElement(f)&&!this._isBlockWithText(f)&&e){a=c?c.startOffset:0;var k=c?c.endOffset:0,
g=c?c.startContainer:null,h=c?c.endContainer:null,f=this._repackInlineElements(e,d,f);b=f["start"==b?0:f.length-1];c&&(b&&e===g&&this._hasTag(e,"BR"))&&(g=b,a=0,d===e&&(h=g,k=0));c&&(c.setStart(g,a),c.setEnd(h,k));return b}if(this._isBlockElement(f))return f;a=f;removeOffset=!0;f=f.parentNode;e=d=null}},_changeStateOfBlocks:function(a,b,c,f,e,d){var k=[];if(a===this.editor.editNode){if(!a.hasChildNodes())return;this._isInlineOrTextElement(a.firstChild)&&this._rebuildBlock(a);a=this._getClosestBlock(a.firstChild,
"start",null)}if(b===this.editor.editNode){if(!b.hasChildNodes())return;this._isInlineOrTextElement(b.lastChild)&&this._rebuildBlock(b);b=this._getClosestBlock(b.lastChild,"end",null)}var g=d?d.startOffset:0,h=d?d.endOffset:0,m=d?d.startContainer:null,l=d?d.endContainer:null;a=this._collectNodes(a,b,c,d,k,m,g,l,h,f);k={nodes:k,groups:a.groups,cells:a.cells};f=f.toString();switch(f){case "mirror":case "ltr":case "rtl":case "left":case "right":case "center":case "explicitdir":this._execDirAndAlignment(k,
f,e);break;case "preparelists":this._prepareLists(k,e);break;case "insertorderedlist":case "insertunorderedlist":this._execInsertLists(k);break;case "prepareoutdent":this._prepareOutdent(k);break;case "prepareindent":this._prepareIndent(k);break;case "indent":this._execIndent(k);break;case "outdent":this._execOutdent(k);break;case "normalizeindent":this._execNormalizedIndent(k);break;case "normalizeoutdent":this._execNormalizedOutdent(k);break;case "prepareformat":this._prepareFormat(k,e);break;case "formatblock":this._execFormatBlocks(k,
e)}d&&(d.setStart(m,g),d.setEnd(l,h),sel=s.getSelection(this.editor.window,!0),sel.removeAllRanges(),sel.addRange(d),this.editor.onDisplayChanged());return k},_collectNodes:function(a,b,c,f,e,d,k,g,h,l){f=a.parentNode;g=[];var n,r=[],q=[],t=[],u=this.editor.editNode;d=p.hitch(this,function(b){e.push(b);var c=this.editor.selection.getParentOfType(b,["TD"]);if(u!==c||m("webkit")&&("prepareformat"===l||"preparelists"===l))q.length&&r.push(q),q=[],u!=c&&(u=c)&&t.push(u);q.push(b)});for(this._rebuildBlock(f);;){if(this._hasTagFrom(a,
this._tableContainers)){if(a.firstChild){f=a;a=a.firstChild;continue}}else if(this._isBlockElement(a)){if((k=s.getBlockAncestor(a,/li/i,this.editor.editNode).blockNode)&&k!==a){a=k;f=a.parentNode;continue}if(!this._hasTag(a,"LI")&&a.firstChild&&(this._rebuildBlock(a),this._isBlockElement(a.firstChild)||this._hasTagFrom(a.firstChild,this._tableContainers))){f=a;a=a.firstChild;continue}this._hasTagFrom(a,this._lineTextArray)&&d(a)}else if(this._isInlineOrTextElement(a)&&!this._hasTagFrom(a.parentNode,
this._tableContainers)){for(g=a;a;){k=a.nextSibling;if(this._isInlineOrTextElement(a)){if(n=a,this._hasTag(a,"BR")&&!(this._isBlockElement(f)&&a===f.lastChild)){g=this._repackInlineElements(g,n,f);a=g[g.length-1];for(h=0;h<g.length;h++)d(g[h]);g=n=null;k&&this._isInlineOrTextElement(k)&&(g=k)}}else if(this._isBlockElement(a))break;a=k}if(!g)continue;g=this._repackInlineElements(g,n,f);a=g[g.length-1];for(h=0;h<g.length;h++)d(g[h])}if(a===b)break;if(a.nextSibling)a=a.nextSibling;else if(f!==c){for(;!f.nextSibling&&
!(a=f,f=a.parentNode,f===c););if(f!==c&&f.nextSibling)a=f.nextSibling,f=f.parentNode;else break}else break}q.length&&(m("webkit")||u?r.push(q):r.unshift(q));return{groups:r,cells:t}},_execDirAndAlignment:function(a,b,c){switch(b){case "mirror":case "ltr":case "rtl":q.forEach(a.nodes,function(c){var a=h.getComputedStyle(c),d=a.direction,k="mirror"!=b?b:"ltr"==d?"rtl":"ltr",g=a.textAlign,n=isNaN(parseInt(a.marginLeft))?0:parseInt(a.marginLeft),a=isNaN(parseInt(a.marginRight))?0:parseInt(a.marginRight);
l.remove(c,"dir");l.remove(c,"align");h.set(c,{direction:k,textAlign:""});if(!this._hasTag(c,"CENTER"))if(0<=g.indexOf("center")&&h.set(c,"textAlign","center"),this._hasTag(c,"LI")){this._refineLIMargins(c);var n="rtl"===d?a:n,a=0,p=c.parentNode;if(d!=h.get(p,"direction")){for(;p!==this.editor.editNode;)this._hasTagFrom(p,["OL","UL"])&&a++,p=p.parentNode;n-=this._getMargins(a)}d="rtl"==k?"marginRight":"marginLeft";a=h.get(c,d);a=isNaN(a)?0:parseInt(a);h.set(c,d,""+(a+n)+"px");m("webkit")?0>g.indexOf("center")&&
h.set(c,"textAlign","rtl"==k?"right":"left"):c.firstChild&&c.firstChild.tagName&&this._hasTagFrom(c.firstChild,this._lineStyledTextArray)&&(a=h.getComputedStyle(c),g=this._refineAlignment(a.direction,a.textAlign),m("mozilla")?h.set(c.firstChild,{textAlign:g}):h.set(c.firstChild,{direction:k,textAlign:g}))}else"rtl"==k&&0!=n?h.set(c,{marginLeft:"",marginRight:""+n+"px"}):"ltr"==k&&0!=a&&h.set(c,{marginRight:"",marginLeft:""+a+"px"})},this);r("table",this.editor.editNode).forEach(function(c,e,d){e=
b;"mirror"===b&&(e="ltr"===h.get(c,"direction")?"rtl":"ltr");d=r("td",c);for(var k=!1,g=!1,l=0;l<a.cells.length;l++)if(!k&&d[0]===a.cells[l])k=!0;else if(d[d.length-1]===a.cells[l]){g=!0;break}if(k&&g){h.set(c,"direction",e);for(l=0;l<d.length;l++)h.set(d[l],"direction",e)}},this);break;case "left":case "right":case "center":q.forEach(a.nodes,function(c){if(!this._hasTag(c,"CENTER")&&(l.remove(c,"align"),h.set(c,"textAlign",b),this._hasTag(c,"LI")&&c.firstChild&&c.firstChild.tagName&&this._hasTagFrom(c.firstChild,
this._lineStyledTextArray))){var a=h.getComputedStyle(c),a=this._refineAlignment(a.direction,a.textAlign);h.set(c.firstChild,"textAlign",a)}},this);break;case "explicitdir":q.forEach(a.nodes,function(b){var c=h.getComputedStyle(b).direction;l.remove(b,"dir");h.set(b,{direction:c})},this)}},_prepareLists:function(a,b){q.forEach(a.nodes,function(c,a,e){if(m("mozilla")||m("webkit")){m("mozilla")&&(a=this._getParentFrom(c,["TD"]))&&0==r("div[tempRole]",a).length&&n.create("div",{innerHTML:"\x3cspan tempRole\x3d'true'\x3e"+
this.bogusHtmlContent+"\x3c/span",tempRole:"true"},a);a=this._tag(c);var d;if(m("webkit")&&this._hasTagFrom(c,this._lineStyledTextArray)||this._hasTag(c,"LI")&&this._hasStyledTextLineTag(c.firstChild)){d=this._hasTag(c,"LI")?this._tag(c.firstChild):a;if(this._hasTag(c,"LI")){for(;c.firstChild.lastChild;)n.place(c.firstChild.lastChild,c.firstChild,"after");c.removeChild(c.firstChild)}d=n.create("span",{innerHTML:this.bogusHtmlContent,bogusFormat:d},c,"first")}if(m("webkit")||!("DIV"!=a&&"P"!=a&&"LI"!=
a))if(m("webkit")&&(this._isListTypeChanged(c,b)&&c===c.parentNode.lastChild)&&n.create("li",{tempRole:"true"},c,"after"),!("LI"==a&&c.firstChild&&c.firstChild.tagName)||!this._hasTagFrom(c.firstChild,this._lineStyledTextArray)){var k=h.getComputedStyle(c);e=k.direction;var k=k.textAlign,k=this._refineAlignment(e,k),g=this._getLIIndent(c),g=0==g?"":""+g+"px";m("webkit")&&"LI"==a&&h.set(c,"textAlign","");c=d?c.firstChild:n.create("span",{innerHTML:this.bogusHtmlContent},c,"first");l.set(c,"bogusDir",
e);""!=k&&l.set(c,"bogusAlign",k);g&&l.set(c,"bogusMargin",g)}}else if(m("ie")&&this._hasTag(c,"LI")&&(h.getComputedStyle(c),h.set(c,"marginRight",""),h.set(c,"marginLeft",""),1==this._getLILevel(c)&&!this._isListTypeChanged(c,cmd)&&(c.firstChild&&this._hasTagFrom(c.firstChild,["P","PRE"])&&n.create("span",{bogusIEFormat:this._tag(c.firstChild)},c.firstChild,"first"),this._hasTag(c.firstChild,"PRE")))){for(d=n.create("p",null,c.firstChild,"after");c.firstChild.firstChild;)n.place(c.firstChild.firstChild,
d,"last");d.style.cssText=c.style.cssText;c.removeChild(c.firstChild)}},this);m("webkit")&&r("table",this.editor.editNode).forEach(function(b,a,e){(a=b.nextSibling)&&this._hasTagFrom(a,["UL","OL"])&&n.create("UL",{tempRole:"true"},b,"after")},this)},_execInsertLists:function(a){q.forEach(a.nodes,function(b,c){if(this._hasTag(b,"LI")){if(b.firstChild&&b.firstChild.tagName&&this._hasTagFrom(b.firstChild,this._lineStyledTextArray)){var a=h.getComputedStyle(b.firstChild),e=this._refineAlignment(a.direction,
a.textAlign);h.set(b,{direction:a.direction,textAlign:e});var d=this._getIntStyleValue(b,"marginLeft")+this._getIntStyleValue(b.firstChild,"marginLeft"),k=this._getIntStyleValue(b,"marginRight")+this._getIntStyleValue(b.firstChild,"marginRight");h.set(b,{marginLeft:d?""+d+"px":"",marginRight:k?""+k+"px":""});h.set(b.firstChild,{direction:"",textAlign:""});m("mozilla")||h.set(b.firstChild,{marginLeft:"",marginRight:""})}for(;1<b.childNodes.length&&3==b.lastChild.nodeType&&b.lastChild.previousSibling&&
3==b.lastChild.previousSibling.nodeType&&""==p.trim(b.lastChild.nodeValue);)b.removeChild(b.lastChild);if(m("safari")&&(this._hasTag(b.firstChild,"SPAN")&&A.contains(b.firstChild,"Apple-style-span"))&&(d=b.firstChild,this._hasTag(d.firstChild,"SPAN")&&l.has(d.firstChild,"bogusFormat"))){for(;d.lastChild;)n.place(d.lastChild,d,"after");b.removeChild(d)}}else if(this._hasTag(b,"DIV")&&0==b.childNodes.length){b.parentNode.removeChild(b);return}if(m("ie")){if(this._hasTag(b,"P")&&"DIV"==this.blockMode.toUpperCase()){if(this._hasTag(b.firstChild,
"SPAN")&&l.has(b.firstChild,"bogusIEFormat")){"PRE"===l.get(b.firstChild,"bogusIEFormat").toUpperCase()?(d=n.create("pre",{innerHTML:b.innerHTML},b,"before"),d.style.cssText=b.style.cssText,d.removeChild(d.firstChild),b.parentNode.removeChild(b)):b.removeChild(b.firstChild);return}d=n.create("div");d.style.cssText=b.style.cssText;for(b.parentNode.insertBefore(d,b);b.firstChild;)d.appendChild(b.firstChild);b.parentNode.removeChild(b)}if(!this._hasTag(b,"LI"))return;this._refineLIMargins(b);d=b.firstChild;
if(!this._hasTag(d,"DIV")||d!==b.lastChild)return;var a=h.getComputedStyle(d),g=a.direction,e=a.textAlign;h.getComputedStyle(b);h.set(b,"direction",g);e=this._refineAlignment(g,e);for(h.set(b,"textAlign",e);d.firstChild;)b.insertBefore(d.firstChild,d);b.removeChild(d)}else if(!this._hasTag(b.firstChild,"SPAN")){this._hasTag(b,"LI")&&(this._refineLIMargins(b),m("mozilla")&&this._hasStyledTextLineTag(b.firstChild)&&this._recountLIMargins(b));return}var q=!1,x=d=!1,k=0;l.has(b.firstChild,"bogusDir")&&
(q=!0,g=l.get(b.firstChild,"bogusDir"),h.set(b,"direction",g));if(l.has(b.firstChild,"bogusAlign")&&(x=q=!0,e=l.get(b.firstChild,"bogusAlign"),h.set(b,"textAlign",e),a=b.firstChild.nextSibling,this._hasTag(a,"SPAN")&&h.get(a,"textAlign")===e&&(h.set(a,"textAlign",""),""==a.style.cssText))){for(;a.lastChild;)n.place(a.lastChild,a,"after");b.removeChild(a)}l.has(b.firstChild,"bogusMargin")&&(d=q=!0,k=parseInt(l.get(b.firstChild,"bogusMargin")),this._hasTag(b,"LI")||(a="rtl"===h.get(b,"direction")?"marginRight":
"marginLeft",e=this._getIntStyleValue(b,a)+k,h.set(b,a,0==e?"":""+e+"px")));if(l.has(b.firstChild,"bogusFormat")){q=!1;l.remove(b.firstChild,"bogusDir");if(b.firstChild.nextSibling&&this._hasTag(b.firstChild.nextSibling,"SPAN")){for(var e=b.firstChild.style.cssText.trim().split(";"),g=b.firstChild.nextSibling.style.cssText.trim().split(";"),r=0;r<e.length;r++)if(e[r])for(a=0;a<g.length;a++)if(e[r].trim()==g[a].trim()){a=e[r].trim().split(":")[0];h.set(b.firstChild.nextSibling,a,"");break}if(""===
b.firstChild.nextSibling.style.cssText){for(;b.firstChild.nextSibling.firstChild;)n.place(b.firstChild.nextSibling.firstChild,b.firstChild.nextSibling,"after");b.removeChild(b.firstChild.nextSibling)}}a=l.get(b.firstChild,"bogusFormat");for(e=n.create(a,null,b.firstChild,"after");e.nextSibling;)n.place(e.nextSibling,e,"last");b.removeChild(b.firstChild);m("webkit")&&this._hasTag(b,"LI")&&(g=b.parentNode.parentNode,this._hasTag(g,a)&&l.set(g,"tempRole","true"));1==b.childNodes.length&&!this._hasTag(b,
"TD")&&(!m("mozilla")&&!this._hasTag(b,"LI")?(e.style.cssText=b.style.cssText,l.set(b,"tempRole","true")):this._hasTag(b,"LI")||(e.style.cssText=b.style.cssText,n.place(e,b,"after"),l.set(b,"tempRole","true")))}q&&b.removeChild(b.firstChild);this._hasTag(b,"LI")&&(m("webkit")&&(!x&&"center"!=h.get(b,"textAlign"))&&h.set(b,"textAlign","rtl"==h.get(b,"direction")?"right":"left"),m("safari")&&this._hasTag(b,"DIV")&&(b.innerHTML=b.nextSibling.innerHTML,b.parentNode.removeChild(b.nextSibling)),q=b.parentNode.parentNode,
q!==this.editor.editNode&&this._hasTag(q,"DIV")&&1==q.childNodes.length&&(q.parentNode.insertBefore(b.parentNode,q),q.parentNode.removeChild(q)),this._refineLIMargins(b),d&&this._recountLIMargins(b,k))},this);m("mozilla")?r("*[tempRole]",this.editor.editNode).forEach(function(b,a,f){if(this._hasTag(b,"SPAN")){if(l.get(b.parentNode,"tempRole"))return;if(this._hasTag(b.parentNode,"LI")){b.parentNode.parentNode.removeChild(b.parentNode);return}}b.parentNode.removeChild(b)},this):m("webkit")&&r("*[tempRole]",
this.editor.editNode).forEach(function(b,a,f){if(!this._hasTag(b,"LI")&&!this._hasTag(b,"UL")){for(;b.lastChild;)n.place(b.lastChild,b,"after");b.parentNode.removeChild(b)}},this)},_execNormalizedIndent:function(a){q.forEach(a.nodes,function(b){var a="rtl"===h.get(b,"direction")?"marginRight":"marginLeft",f=h.get(b,a),f=isNaN(f)?0:parseInt(f);h.set(b,a,""+(f+this._indentBy)+"px")},this)},_execNormalizedOutdent:function(a){q.forEach(a.nodes,function(b){var a="rtl"===h.get(b,"direction")?"marginRight":
"marginLeft",f=h.get(b,a),f=isNaN(f)?0:parseInt(f),e=0;if("LI"===b.tagName.toUpperCase()){var d=0,k=b.parentNode;if(h.get(b,"direction")!=h.get(k,"direction")){for(;k!==this.editor.editNode;)this._hasTagFrom(k,["OL","UL"])&&d++,k=k.parentNode;e=this._getMargins(d)}}f>=this._indentBy+e&&h.set(b,a,f==this._indentBy?"":""+(f-this._indentBy)+"px")},this)},_prepareIndent:function(a){q.forEach(a.nodes,function(b){if(m("mozilla")){var a=this._getParentFrom(b,["TD"]);a&&0==r("div[tempRole]",a).length&&n.create("div",
{innerHTML:this.bogusHtmlContent,tempRole:"true"},a);this._hasTag(b,"LI")&&(a=this._getLIIndent(b),l.set(b,"tempIndent",a))}if(m("webkit")&&this._hasTag(b,"LI")&&this._hasStyledTextLineTag(b.firstChild)){for(a=this._tag(b.firstChild);b.firstChild.lastChild;)n.place(b.firstChild.lastChild,b.firstChild,"after");b.removeChild(b.firstChild);n.create("span",{innerHTML:this.bogusHtmlContent,bogusFormat:a},b,"first")}},this)},_prepareOutdent:function(a){q.forEach(a.nodes,function(b){if(m("mozilla")||m("webkit")){if(m("mozilla")){var a=
this._getParentFrom(b,["TD"]);a&&0==r("div[tempRole]",a).length&&n.create("div",{innerHTML:this.bogusHtmlContent,tempRole:"true"},a)}a=this._tag(b);if(m("mozilla")&&"LI"!==a)return;var f=null;if(m("webkit")&&this._hasTag(b,"LI")&&this._hasStyledTextLineTag(b.firstChild)){for(var a=this._tag(b.firstChild),e=b.firstChild;e.lastChild;)n.place(e.lastChild,e,"after");b.removeChild(b.firstChild);f=n.create("span",{innerHTML:this.bogusHtmlContent,bogusFormat:a},b,"first")}if(b.firstChild&&b.firstChild.tagName&&
this._hasTagFrom(b.firstChild,this._lineStyledTextArray)){m("mozilla")&&(b.firstChild.style.cssText=b.style.cssText,a="rtl"===h.get(b,"direction")?"marginRight":"marginLeft",e=this._getLIIndent(b),0<e&&h.set(b.firstChild,a,""+e+"px"));return}var d=h.getComputedStyle(b),e=d.direction,d=d.textAlign,d=this._refineAlignment(e,d);m("webkit")&&"LI"==a&&h.set(b,"textAlign","");a=f?b.firstChild:n.create("span",{innerHTML:this.bogusHtmlContent},b,"first");l.set(a,"bogusDir",e);""!=d&&l.set(a,"bogusAlign",
d);m("mozilla")&&(e=this._getLIIndent(b),l.set(a,"bogusIndent",e))}if(m("ie")&&"LI"==b.tagName.toUpperCase()&&(h.set(b,"marginLeft",""),h.set(b,"marginRight",""),1==this._getLILevel(b)&&(b.firstChild&&this._hasTagFrom(b.firstChild,["P","PRE"])&&n.create("span",{bogusIEFormat:this._tag(b.firstChild)},b.firstChild,"first"),this._hasTag(b.firstChild,"PRE")))){for(a=n.create("p",null,b.firstChild,"after");b.firstChild.firstChild;)n.place(b.firstChild.firstChild,a,"last");a.style.cssText=b.style.cssText;
b.removeChild(b.firstChild)}},this)},_execIndent:function(a){q.forEach(a.nodes,function(b){m("mozilla")||h.set(b,"margin","");if(this._hasTag(b,"LI")){var a=0;m("mozilla")&&l.has(b,"tempIndent")&&(a=parseInt(l.get(b,"tempIndent")),l.remove(b,"tempIndent"));this._refineLIMargins(b);m("mozilla")&&this._recountLIMargins(b,a)}if(l.has(b.firstChild,"bogusFormat")){a=l.get(b.firstChild,"bogusFormat");for(a=n.create(a,null,b.firstChild,"after");a.nextSibling;)n.place(a.nextSibling,a,"last");b.removeChild(b.firstChild)}if(m("ie")||
m("webkit"))for(b=b.parentNode;b!==this.editor.editNode;){b=s.getBlockAncestor(b,/blockquote/i,this.editor.editNode).blockNode;if(!b)break;l.has(b,"dir")&&l.remove(b,"dir");h.set(b,"marginLeft","");h.set(b,"marginRight","");h.set(b,"margin","");b=b.parentNode}},this);m("mozilla")&&(r("div[tempRole]",this.editor.editNode).forEach(function(a,c,f){a.parentNode.removeChild(a)}),r("ul,ol",this.editor.editNode).forEach(function(a,c,f){h.set(a,"marginLeft","");h.set(a,"marginRight","")}))},_execOutdent:function(a){q.forEach(a.nodes,
function(a){if(m("mozilla")||m("webkit")){if(!this._hasTag(a.firstChild,"SPAN")){this._hasTag(a,"LI")&&(this._refineLIMargins(a),m("mozilla")&&this._hasStyledTextLineTag(a.firstChild)&&(this._recountLIMargins(a),a.firstChild.style.cssText=""));return}var c=!1,f=!1,e=0;if(l.has(a.firstChild,"bogusDir")){var c=!0,d=l.get(a.firstChild,"bogusDir");h.set(a,"direction",d)}l.has(a.firstChild,"bogusAlign")&&(c=!0,d=l.get(a.firstChild,"bogusAlign"),h.set(a,"textAlign",d));if(l.has(a.firstChild,"bogusIndent")&&
(c=!0,e=parseInt(l.get(a.firstChild,"bogusIndent")),!this._hasTag(a,"LI"))){var d="rtl"===h.get(a,"direction")?"marginRight":"marginLeft",k=""+(this._getIntStyleValue(a,d)+e)+"px";h.set(a,d,k)}if(l.has(a.firstChild,"bogusFormat")){c=!0;d=l.get(a.firstChild,"bogusFormat");for(d=n.create(d,null,a.firstChild,"after");d.nextSibling;)n.place(d.nextSibling,d,"last");this._hasTag(a,"LI")||(d.style.cssText=a.style.cssText,f=!0)}if(c&&(a.removeChild(a.firstChild),f)){for(;a.lastChild;)n.place(a.lastChild,
a,"after");l.set(a,"tempRole","true")}m("webkit")&&(this._hasTag(a,"LI")&&"center"!=h.get(a,"textAlign"))&&h.set(a,"textAlign","rtl"==h.get(a,"direction")?"right":"left");m("mozilla")&&this._hasTag(a,"LI")&&(c=a.parentNode.parentNode,c!==this.editor.editNode&&this._hasTag(c,"DIV")&&1==c.childNodes.length&&(c.parentNode.insertBefore(a.parentNode,c),c.parentNode.removeChild(c)))}if(m("ie")&&this._hasTag(a,"P")&&"DIV"==this.blockMode.toUpperCase()){if(this._hasTag(a.firstChild,"SPAN")&&l.has(a.firstChild,
"bogusIEFormat")){"PRE"===l.get(a.firstChild,"bogusIEFormat").toUpperCase()?(e=n.create("pre",{innerHTML:a.innerHTML},a,"before"),e.style.cssText=a.style.cssText,e.removeChild(e.firstChild),a.parentNode.removeChild(a)):a.removeChild(a.firstChild);return}c=n.create("div");c.style.cssText=a.style.cssText;for(a.parentNode.insertBefore(c,a);a.firstChild;)c.appendChild(a.firstChild);a.parentNode.removeChild(a)}this._hasTag(a,"LI")&&(this._refineLIMargins(a),m("mozilla")&&this._recountLIMargins(a,e))},
this);(m("mozilla")||m("webkit"))&&r("div[tempRole]",this.editor.editNode).forEach(function(a,c,f){a.parentNode.removeChild(a)})},_prepareFormat:function(a,b){q.forEach(a.nodes,function(a){if(m("mozilla")&&this._hasTag(a,"LI")){if(a.firstChild&&!this._isBlockElement(a.firstChild)){var f=a.ownerDocument.createElement(b),e=a.firstChild;for(a.insertBefore(f,a.firstChild);e;)f.appendChild(e),e=e.nextSibling}f=this._getLIIndent(a);l.set(a,"tempIndent",f)}if(m("webkit")){var d;if(this._hasTag(a,"LI")){if(this._hasStyledTextLineTag(a.firstChild)){for(;a.firstChild.lastChild;)n.place(a.firstChild.lastChild,
a.firstChild,"after");a.removeChild(a.firstChild)}d=n.create("span",{innerHTML:this.bogusHtmlContent,bogusFormat:b},a,"first")}e=h.getComputedStyle(a);f=e.direction;e=e.textAlign;e=this._refineAlignment(f,e);a=d?a.firstChild:n.create("span",{innerHTML:this.bogusHtmlContent},a,"first");l.set(a,"bogusDir",f);""!=e&&l.set(a,"bogusAlign",e)}},this)},_execFormatBlocks:function(a,b){q.forEach(a.nodes,function(a){if(this._hasTagFrom(a,this._lineTextArray)){if(this._hasTag(a.parentNode,"DIV")&&a.parentNode!==
this.editor.editNode)for(;a.parentNode.lastChild&&(3==a.parentNode.lastChild.nodeType&&""==p.trim(a.parentNode.lastChild.nodeValue)||this._hasTag(a.parentNode.lastChild,"BR"));)a.parentNode.removeChild(a.parentNode.lastChild);if(this._hasTag(a.parentNode,"DIV")&&a.parentNode!==this.editor.editNode&&1==a.parentNode.childNodes.length){var f=a.parentNode,e=h.getComputedStyle(f),d=this._refineAlignment(e.direction,e.textAlign);h.set(a,{direction:e.direction,textAlign:d});d="rtl"===e.direction?"marginRight":
"marginLeft";e=parseInt(h.get(f,d));0!=e&&!isNan(e)&&h.set(a,d,e);f.parentNode.insertBefore(a,f);f.parentNode.removeChild(f)}}if(this._hasTag(a,"LI")){f=0;l.has(a,"tempIndent")&&(f=parseInt(l.get(a,"tempIndent")),l.remove(a,"tempIndent"));this._refineLIMargins(a);for(f&&this._recountLIMargins(a,f);1<a.childNodes.length&&3==a.lastChild.nodeType&&""==p.trim(a.lastChild.nodeValue);)a.removeChild(a.lastChild);if(this._hasTagFrom(a.firstChild,this._lineStyledTextArray))e=h.getComputedStyle(a),d=this._refineAlignment(e.direction,
e.textAlign),!m("mozilla")&&(!m("ie")||!this._hasTag(a,"LI"))&&h.set(a.firstChild,{direction:e.direction,textAlign:d});else if(this._hasTag(a.firstChild,"DIV")){for(f=a.firstChild;f.firstChild;)a.insertBefore(f.firstChild,f);a.removeChild(f)}if(m("ie")&&!this._hasTag(a.firstChild,"P")&&"\x3cp\x3e"===b){f=n.create("p");for(d=this._hasTagFrom(f.nextSibling,this._lineStyledTextArray)?f.nextSibling:a;d.firstChild;)n.place(d.firstChild,f,"last");n.place(f,a,"first");d!==a&&a.removeChild(d)}}if(m("webkit")){if(this._hasTag(a,
"DIV")){if(l.has(a,"tempRole"))return;if(this._hasTag(a.previousSibling,"LI")){for(;a.firstChild;)n.place(a.firstChild,a.previousSibling,"last");l.set(a,"tempRole",!0);a=a.previousSibling}}f=!1;l.has(a.firstChild,"bogusDir")&&(f=!0,d=l.get(a.firstChild,"bogusDir"),h.set(a,"direction",d));l.has(a.firstChild,"bogusAlign")&&(f=!0,d=l.get(a.firstChild,"bogusAlign"),h.set(a,"textAlign",d));if(l.has(a.firstChild,"bogusFormat")){var f=!0,k=l.get(a.firstChild,"bogusFormat");if("DIV"!==k.toUpperCase())for(d=
n.create(k,null,a.firstChild,"after");d.nextSibling;)n.place(d.nextSibling,d,"last");else d=a;if(m("safari")&&this._hasTag(a.nextSibling,"DIV")){for(;a.nextSibling.firstChild;)n.place(a.nextSibling.firstChild,d,"last");l.set(a.nextSibling,"tempRole","true")}}f&&a.removeChild(a.firstChild);k&&this._hasTag(a,"LI")&&(a=a.parentNode.parentNode,this._hasTag(a,k)&&l.set(a,"tempRole","true"))}},this);m("webkit")&&r("*[tempRole]",this.editor.editNode).forEach(function(a,b,e){for(;a.lastChild;)n.place(a.lastChild,
a,"after");a.parentNode.removeChild(a)},this)},_rebuildBlock:function(a){for(var b=a.firstChild,c,f,e=!1;b;){if(this._isInlineOrTextElement(b)&&!this._hasTagFrom(b,this._tableContainers))e=!this._hasTagFrom(a,this._lineTextArray),c||(c=b),f=b;else if(this._isBlockElement(b)||this._hasTagFrom(b,this._tableContainers))c&&(this._repackInlineElements(c,f,a),c=null),e=!0;b=b.nextSibling}e&&c&&this._repackInlineElements(c,f,a)},_repackInlineElements:function(a,b,c){var f=[],e=c.ownerDocument.createElement(this.blockMode),
d,k=a.previousSibling&&1==a.previousSibling.nodeType?a.previousSibling.style.cssText:c.style.cssText,g=c===this.editor.editNode;f.push(e);a=c.replaceChild(e,a);n.place(a,e,"after");for(g?h.set(e,"direction",h.get(this.editor.editNode,"direction")):e.style.cssText=k;a;){var l=a.nextSibling;if(this._isInlineOrTextElement(a)){this._hasTag(a,"BR")&&a!==b&&(d=c.ownerDocument.createElement(this.blockMode),f.push(d),a=c.replaceChild(d,a),n.place(a,d,"after"),g?h.set(d,"direction",h.get(this.editor.editNode,
"direction")):d.style.cssText=k);if((this._hasTag(a,"BR")||8==a.nodeType)&&!e.hasChildNodes())e.innerHTML=this.bogusHtmlContent;this._hasTag(a,"BR")&&m("ie")?a.parentNode.removeChild(a):8!=a.nodeType?e.appendChild(a):a.parentNode.removeChild(a);3==a.nodeType&&(a.previousSibling&&3==a.previousSibling.nodeType)&&(a.previousSibling.nodeValue+=a.nodeValue,a.parentNode.removeChild(a));d&&(e=d,d=null)}if(a===b)break;a=l}return f},_preFilterNewLines:function(a){a=a.split(/(<\/?pre.*>)/i);for(var b=!1,c=
0;c<a.length;c++)0>a[c].search(/<\/?pre/i)&&!b?a[c]=a[c].replace(/\n/g,"").replace(/\t+/g,"\u00a0").replace(/^\s+/,"\u00a0").replace(/\xA0\xA0+$/,""):0<=a[c].search(/<\/?pre/i)&&(b=!b);return a.join("")},_refineAlignment:function(a,b){return b=0<=b.indexOf("left")&&"rtl"==a?"left":0<=b.indexOf("right")&&"ltr"==a?"right":0<=b.indexOf("center")?"center":""},_refineLIMargins:function(a){var b=h.get(a,"direction"),c=h.get(a.parentNode,"direction"),f=0,e=a.parentNode;for(m("webkit")&&(c=h.get(this.editor.editNode,
"direction"));e!==this.editor.editNode;)this._hasTagFrom(e,["OL","UL"])&&f++,e=e.parentNode;h.set(a,"marginRight","");h.set(a,"marginLeft","");e="rtl"==b?"marginRight":"marginLeft";f=""+this._getMargins(f)+"px";b!=c&&h.set(a,e,f)},_getMargins:function(a){if(0==a)return 0;var b=35;m("mozilla")?b=45:m("ie")&&(b=25);return b+40*(a-1)},_recountLIMargins:function(a,b){var c=h.get(a,"direction"),f=h.get(a.parentNode,"direction"),e="rtl"==c?"marginRight":"marginLeft",d=h.get(a,e),k=(isNaN(parseInt(d))?0:
parseInt(d))+(b?b:0);a.firstChild&&1==a.firstChild.nodeType&&(d=h.get(a.firstChild,e),k+=isNaN(parseInt(d))?0:parseInt(d),h.set(a.firstChild,{marginLeft:"",marginRight:""}));c!=f&&(k-=this._getMargins(this._getLILevel(a)));if(d=this._getListMargins(a))for(var g=0;g<d/40;g++){var l=n.create(this._tag(a.parentNode),null,a,"before");n.place(a,l,"last")}c!=f&&(k+=this._getMargins(this._getLILevel(a)));k&&h.set(a,e,""+k+"px")},_getLILevel:function(a){a=a.parentNode;for(var b=0;this._hasTagFrom(a,["UL",
"OL"]);)b++,a=a.parentNode;return b},_getLIIndent:function(a){var b=a.parentNode,c=h.get(a,"direction"),f=h.get(b,"direction"),b=this._getIntStyleValue(a,"rtl"===c?"marginRight":"marginLeft");a=c===f?0:this._getMargins(this._getLILevel(a));return b-a},_getListMargins:function(a){a=a.parentNode;for(var b,c=0;this._hasTagFrom(a,["UL","OL"]);)b="rtl"==h.get(a,"direction")?"marginRight":"marginLeft",b=h.get(a,b),c+=isNaN(parseInt(b))?0:parseInt(b),a=a.parentNode;return c},_tag:function(a){return a&&a.tagName&&
a.tagName.toUpperCase()},_hasTag:function(a,b){return a&&b&&a.tagName&&a.tagName.toUpperCase()===b.toUpperCase()},_hasStyledTextLineTag:function(a){return this._hasTagFrom(a,this._lineStyledTextArray)},_hasTagFrom:function(a,b){return a&&b&&a.tagName&&0<=q.indexOf(b,a.tagName.toUpperCase())},_getParentFrom:function(a,b){if(!a||!b||!b.length)return null;for(var c=a;c!==this.editor.editNode;){if(this._hasTagFrom(c,b))return c;c=c.parentNode}return null},_isSimpleInfo:function(a){return!a||2>a.groups.length},
_isListTypeChanged:function(a,b){if(!this._hasTag(a,"LI"))return!1;var c=a.parentNode;return this._hasTag(c,"UL")&&"insertorderedlist"===b||this._hasTag(c,"OL")&&"insertunorderedlist"===b},_getIntStyleValue:function(a,b){var c=parseInt(h.get(a,b));return isNaN(c)?0:c},_mergeLists:function(){var a=s.getSelection(this.editor.window),b=a&&0<a.rangeCount;if(b)var c=a.getRangeAt(0).cloneRange(),f=c.startContainer,e=c.startOffset,d=c.endContainer,h=c.endOffset;var g=!1;r("ul,ol",this.editor.editNode).forEach(function(a,
b,c){if(l.has(a,"tempRole"))a.parentNode.removeChild(a);else for(b=a.nextSibling;this._hasTag(b,this._tag(a));){for(;b.firstChild;)n.place(b.firstChild,a,"last"),g=!0;l.set(b,"tempRole","true");b=b.nextSibling}},this);if(b&&g){a.removeAllRanges();try{c.setStart(f,e),c.setEnd(d,h),a.addRange(c)}catch(m){}}},_cleanLists:function(){m("webkit")&&(r("table",this.editor.editNode).forEach(function(a,b,c){a=a.nextSibling;this._hasTag(a,"UL")&&"true"===l.get(a,"tempRole")&&a.parentNode.removeChild(a)},this),
r("li[tempRole]",this.editor.editNode).forEach(function(a,b,c){1==a.parentNode.childNodes.length?a.parentNode.parentNode.removeChild(a.parentNode):a.parentNode.removeChild(a)}));var a=s.getSelection(this.editor.window),b=a&&0<a.rangeCount;if(b)var c=a.getRangeAt(0).cloneRange(),f=c.startContainer,e=c.startOffset,d=c.endContainer,h=c.endOffset;var g=!1;r("span[bogusDir]",this.editor.editNode).forEach(function(a,b,c){c=b=a.firstChild;if(1==b.nodeType)for(;b;)c=b.nextSibling,n.place(b,a,"after"),g=!0,
b=c;a.parentNode.removeChild(a)},this);if(b&&g){a.removeAllRanges();try{c.setStart(f,e),c.setEnd(d,h),a.addRange(c)}catch(p){}}}});v.registry.bidiSupport=v.registry.bidisupport=function(a){return new y({})};return y});
//# sourceMappingURL=BidiSupport.js.map