//>>built
define("dojox/charting/plot2d/Spider","dojo/_base/lang dojo/_base/declare dojo/_base/connect dojo/_base/array dojo/dom-geometry dojo/_base/fx dojo/fx dojo/sniff ./Base ./_PlotEvents ./common ../axis2d/common dojox/gfx dojox/gfx/matrix dojox/gfx/fx dojox/lang/functional dojox/lang/utils dojo/fx/easing".split(" "),function(B,U,I,J,P,K,V,L,W,X,Q,R,C,Y,aa,S,T,Z){return U("dojox.charting.plot2d.Spider",[W,X],{defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:-10,labelStyle:"default",htmlLabels:!0,
startAngle:-90,divisions:3,axisColor:"",axisWidth:0,spiderColor:"",spiderWidth:0,seriesWidth:0,seriesFillAlpha:0.2,spiderOrigin:0.16,markerSize:3,spiderType:"polygon",animationType:Z.backOut,animate:null,axisTickFont:"",axisTickFontColor:"",axisFont:"",axisFontColor:""},optionalParams:{radius:0,font:"",fontColor:""},constructor:function(a,e){this.opt=B.clone(this.defaultParams);T.updateWithObject(this.opt,e);T.updateWithPattern(this.opt,e,this.optionalParams);this.dyn=[];this.datas={};this.labelKey=
[];this.oldSeriePoints={};this.animate=null===this.opt.animate?{}:this.opt.animate;this.animations={}},clear:function(){this.inherited(arguments);this.dyn=[];this.axes=[];this.datas={};this.labelKey=[];this.oldSeriePoints={};this.animations={};return this},setAxis:function(a){a&&(void 0!=a.opt.min&&(this.datas[a.name].min=a.opt.min),void 0!=a.opt.max&&(this.datas[a.name].max=a.opt.max));return this},addSeries:function(a){this.series.push(a);for(var e in a.data){var c=a.data[e],h=this.datas[e];h?(h.vlist.push(c),
h.min=Math.min(h.min,c),h.max=Math.max(h.max,c)):(h="__"+e,this.axes.push(h),this[h]=e,this.datas[e]={min:c,max:c,vlist:[c]})}if(0>=this.labelKey.length)for(e in a.data)this.labelKey.push(e);return this},getSeriesStats:function(){return Q.collectSimpleStats(this.series)},render:function(a,e){if(!this.dirty)return this;this.dirty=!1;this.cleanGroup();var c=this.group,h=this.chart.theme;this.resetEvents();if(!this.series||!this.series.length)return this;var b=this.opt,f=h.axis,d=(a.width-e.l-e.r)/2,
k=(a.height-e.t-e.b)/2,l=Math.min(d,k),r=b.font||f.majorTick&&f.majorTick.font||f.tick&&f.tick.font||"normal normal normal 7pt Tahoma",p=b.axisFont||f.tick&&f.tick.titleFont||"normal normal normal 11pt Tahoma",v=b.axisTickFontColor||f.majorTick&&f.majorTick.fontColor||f.tick&&f.tick.fontColor||"silver",N=b.axisFontColor||f.tick&&f.tick.titleFontColor||"black",x=b.axisColor||f.tick&&f.tick.axisColor||"silver",m=b.spiderColor||f.tick&&f.tick.spiderColor||"silver",$=b.axisWidth||f.stroke&&f.stroke.width||
2,y=b.spiderWidth||f.stroke&&f.stroke.width||2,f=b.seriesWidth||f.stroke&&f.stroke.width||2,s=C.normalizedLength(C.splitFontString(p).size),E=Y._degToRad(b.startAngle),B,t,M,u,q,z,w=b.spiderOrigin,D=3<=b.divisions?b.divisions:3,I=b.markerSize,K=b.spiderType,L=b.animationType,g=-10>b.labelOffset?b.labelOffset:-10,n;b.labels&&(l=J.map(this.series,function(a){return a.name},this),l=S.foldl1(S.map(l,function(a){return C._base._getTextBox(a,{font:h.series.font}).w},this),"Math.max(a, b)")/2,l=Math.min(d-
2*l,k-s)+g,B=l-g);"radius"in b&&(l=b.radius,B=l-g);l/=1.2;d={cx:e.l+d,cy:e.t+k,r:l};for(k=this.series.length-1;0<=k;k--)if(n=this.series[k],!this.dirty&&!n.dirty)h.skip();else if(n.cleanGroup(),g=n.data,null!==g&&(s=this._getObjectLength(g),!t||0>=t.length))if(t=[],M=[],z=[],this._buildPoints(t,s,d,l,E,!0,a),this._buildPoints(M,s,d,l*w,E,!0,a),this._buildPoints(z,s,d,B,E,!1,a),2<D){u=[];q=[];for(g=0;g<D-2;g++)u[g]=[],this._buildPoints(u[g],s,d,l*(w+(1-w)*(g+1)/(D-1)),E,!0,a),q[g]=l*(w+(1-w)*(g+1)/
(D-1))}s=c.createGroup();x={color:x,width:$};k={color:m,width:y};for(g=t.length-1;0<=g;--g)m=t[g],y={x:m.x+0.2*(m.x-d.cx),y:m.y+0.2*(m.y-d.cy)},m={x:m.x+0.2*(m.x-d.cx)/2,y:m.y+0.2*(m.y-d.cy)/2},s.createLine({x1:d.cx,y1:d.cy,x2:y.x,y2:y.y}).setStroke(x),this._drawArrow(s,y,m,x);s=c.createGroup();for(g=z.length-1;0<=g;--g)m=z[g],y=C._base._getTextBox(this.labelKey[g],{font:p}).w||0,x=this.opt.htmlLabels&&"vml"!=C.renderer?"html":"gfx",m=R.createText[x](this.chart,s,!P.isBodyLtr()&&"html"==x?m.x+y-a.width:
m.x,m.y,"middle",this.labelKey[g],p,N),this.opt.htmlLabels&&this.htmlElements.push(m);p=c.createGroup();if("polygon"==K){if(p.createPolyline(t).setStroke(k),p.createPolyline(M).setStroke(k),0<u.length)for(g=u.length-1;0<=g;--g)p.createPolyline(u[g]).setStroke(k)}else if(p.createCircle({cx:d.cx,cy:d.cy,r:l}).setStroke(k),p.createCircle({cx:d.cx,cy:d.cy,r:l*w}).setStroke(k),0<q.length)for(g=q.length-1;0<=g;--g)p.createCircle({cx:d.cx,cy:d.cy,r:q[g]}).setStroke(k);s=this._getObjectLength(this.datas);
N=c.createGroup();u=0;for(var F in this.datas){q=this.datas[F];t=q.min;q=q.max;q-=t;p=E+2*Math.PI*u/s;for(k=0;k<D;k++)z=t+q*k/(D-1),m=this._getCoordinate(d,l*(w+(1-w)*k/(D-1)),p,a),z=this._getLabel(z),y=C._base._getTextBox(z,{font:r}).w||0,x=this.opt.htmlLabels&&"vml"!=C.renderer?"html":"gfx",this.opt.htmlLabels&&this.htmlElements.push(R.createText[x](this.chart,N,!P.isBodyLtr()&&"html"==x?m.x+y-a.width:m.x,m.y,"start",z,r,v));u++}this.chart.seriesShapes={};for(k=this.series.length-1;0<=k;k--)if(n=
this.series[k],g=n.data,null!==g){var r=h.next("spider",[b,n]),G=C.normalizeColor(r.series.fill),r={color:r.series.fill,width:f};G.a=b.seriesFillAlpha;n.dyn={fill:G,stroke:r};if(!n.hidden){var A=[],H=[];u=0;for(F in g)q=this.datas[F],t=q.min,q=q.max,q-=t,v=g[F],p=E+2*Math.PI*u/s,m=this._getCoordinate(d,l*(w+(1-w)*(v-t)/q),p,a),A.push(m),H.push({sname:n.name,key:F,data:v}),u++;A[A.length]=A[0];H[H.length]=H[0];var v=this._getBoundary(A),O=n.group,r=this._createSeriesEntry(O,this.oldSeriePoints[n.name]||
M,A,G,r,l,w,I,L);this.chart.seriesShapes[n.name]=r;this.oldSeriePoints[n.name]=A;this._connectEvents({element:"spider_poly",index:k,id:"spider_poly_"+n.name,run:n,plot:this,shape:r.poly,parent:O,brect:v,cx:d.cx,cy:d.cy,cr:l,f:G,s:c});this._connectEvents({element:"spider_plot",index:k,id:"spider_plot_"+n.name,run:n,plot:this,shape:n.group});J.forEach(r.circles,function(a,b){this._connectEvents({element:"spider_circle",index:b,id:"spider_circle_"+n.name+b,run:n,plot:this,shape:a,parent:O,tdata:H[b],
cx:A[b].x,cy:A[b].y,f:G,s:c})},this)}}return this},_createSeriesEntry:function(a,e,c,h,b,f,d,k,l){f=this.animate?e:c;var r=a.createPolyline(f).setFill(h).setStroke(b),p=[];for(d=0;d<f.length;d++){var v=f[d],v=a.createCircle({cx:v.x,cy:v.y,r:k}).setFill(h).setStroke(b);p.push(v)}this.animate&&(h=J.map(c,function(a,b){var c=new K.Animation(B.delegate({duration:1E3,easing:l,curve:[e[b].y,a.y]},this.animate)),d=p[b];I.connect(c,"onAnimate",function(a){var c=r.getShape();c.points[b].y=a;r.setShape(c);
c=d.getShape();c.cy=a;d.setShape(c)});return c},this),c=J.map(c,function(a,b){var c=new K.Animation(B.delegate({duration:1E3,easing:l,curve:[e[b].x,a.x]},this.animate)),d=p[b];I.connect(c,"onAnimate",function(a){var c=r.getShape();c.points[b].x=a;r.setShape(c);c=d.getShape();c.cx=a;d.setShape(c)});return c},this),V.combine(h.concat(c)).play());return{group:a,poly:r,circles:p}},plotEvent:function(a){"spider_plot"==a.element&&"onmouseover"==a.type&&!L("ie")&&a.shape.moveToFront()},tooltipFunc:function(a){return"spider_circle"==
a.element?a.tdata.sname+"\x3cbr/\x3e"+a.tdata.key+"\x3cbr/\x3e"+a.tdata.data:null},_getBoundary:function(a){for(var e=a[0].x,c=a[0].x,h=a[0].y,b=a[0].y,f=0;f<a.length;f++)var d=a[f],e=Math.max(d.x,e),h=Math.max(d.y,h),c=Math.min(d.x,c),b=Math.min(d.y,b);return{x:c,y:b,width:e-c,height:h-b}},_drawArrow:function(a,e,c,h){var b=Math.sqrt(Math.pow(c.x-e.x,2)+Math.pow(c.y-e.y,2)),f=(c.y-e.y)/b,d=(c.x-e.x)/b;a.createPolyline([e,{x:c.x+b/3*-f,y:c.y+b/3*d},{x:c.x+b/3*f,y:c.y+b/3*-d}]).setFill(h.color).setStroke(h)},
_buildPoints:function(a,e,c,h,b,f,d){for(var k=0;k<e;k++)a.push(this._getCoordinate(c,h,b+2*Math.PI*k/e,d));f&&a.push(this._getCoordinate(c,h,b+2*Math.PI,d))},_getCoordinate:function(a,e,c,h){var b=a.cx+e*Math.cos(c);L("dojo-bidi")&&(this.chart.isRightToLeft()&&h)&&(b=h.width-b);return{x:b,y:a.cy+e*Math.sin(c)}},_getObjectLength:function(a){var e=0;if(B.isObject(a))for(var c in a)e++;return e},_getLabel:function(a){return Q.getLabel(a,this.opt.fixed,this.opt.precision)}})});
//# sourceMappingURL=Spider.js.map