//>>built
define("dgrid/extensions/Pagination","../_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on dojo/query dojo/string dojo/has put-selector/put dojo/i18n!./nls/pagination dojo/_base/sniff xstyle/css!../css/extensions/Pagination.css".split(" "),function(v,w,x,q,m,s,t,r,d,y){function z(b){b.noDataNode?(d(b.noDataNode,"!"),delete b.noDataNode):b.cleanup();b.contentNode.innerHTML=""}function u(b){if(b.loadingNode)d(b.loadingNode,"!"),delete b.loadingNode;else if(b._oldPageNodes){for(var c in b._oldPageNodes)b.removeRow(b._oldPageNodes[c]);
delete b._oldPageNodes;b._oldPageObserver&&(b._oldPageObserver.cancel(),b._numObservers--,delete b._oldPageObserver)}delete b._isLoading}return w(v,{rowsPerPage:10,pagingTextBox:!1,previousNextArrows:!0,firstLastArrows:!1,pagingLinks:2,pageSizeOptions:[],showLoadingMessage:!0,i18nPagination:y,showFooter:!0,_currentPage:1,_total:0,buildRendering:function(){this.inherited(arguments);var b=this,c=this.paginationNode=d(this.footerNode,"div.dgrid-pagination"),a=this.paginationStatusNode=d(c,"div.dgrid-status"),
k=this.pageSizeOptions,h=this.i18nPagination;a.tabIndex=0;if(k.length){var g=d(c,"select.dgrid-page-size"),e;for(e=0;e<k.length;e++)d(g,"option",k[e],{value:k[e],selected:this.rowsPerPage===k[e]});this._listeners.push(m(g,"change",function(){b.rowsPerPage=+g.value;b.gotoPage(1)}))}a.innerHTML=t.substitute(h.status,{start:1,end:1,total:0});c=this.paginationNavigationNode=d(c,"div.dgrid-navigation");this.firstLastArrows&&(a=this.paginationFirstNode=d(c,"span.dgrid-first.dgrid-page-link","\u00ab"),a.setAttribute("aria-label",
h.gotoFirst),a.tabIndex=0);this.previousNextArrows&&(a=this.paginationPreviousNode=d(c,"span.dgrid-previous.dgrid-page-link","\u2039"),a.setAttribute("aria-label",h.gotoPrev),a.tabIndex=0);this.paginationLinksNode=d(c,"span.dgrid-pagination-links");this.previousNextArrows&&(a=this.paginationNextNode=d(c,"span.dgrid-next.dgrid-page-link","\u203a"),a.setAttribute("aria-label",h.gotoNext),a.tabIndex=0);this.firstLastArrows&&(a=this.paginationLastNode=d(c,"span.dgrid-last.dgrid-page-link","\u00bb"),a.setAttribute("aria-label",
h.gotoLast),a.tabIndex=0);this._listeners.push(m(c,".dgrid-page-link:click,.dgrid-page-link:keydown",function(a){if(!("keydown"===a.type&&13!==a.keyCode)){a=this.className;var c,d;b._isLoading||-1<a.indexOf("dgrid-page-disabled")||(c=b._currentPage,d=Math.ceil(b._total/b.rowsPerPage),this===b.paginationPreviousNode?b.gotoPage(c-1):this===b.paginationNextNode?b.gotoPage(c+1):this===b.paginationFirstNode?b.gotoPage(1):this===b.paginationLastNode?b.gotoPage(d):"dgrid-page-link"===a&&b.gotoPage(+this.innerHTML,
!0))}}))},destroy:function(){this.inherited(arguments);this._pagingTextBoxHandle&&this._pagingTextBoxHandle.remove()},_updateNavigation:function(b){function c(c){var e;a.pagingTextBox&&c==g&&1<f?(e=d(h,"input.dgrid-page-input[type\x3dtext][value\x3d$]",g),e.setAttribute("aria-label",k.jumpPage),a._pagingTextBoxHandle=m(e,"change",function(){var b=+this.value;!isNaN(b)&&(0<b&&b<=f)&&a.gotoPage(+this.value,!0)})):(e=d(h,"span"+(c==g?".dgrid-page-disabled":"")+".dgrid-page-link",c),e.setAttribute("aria-label",
k.gotoPage),e.tabIndex=0);c==g&&b&&e.focus()}var a=this,k=this.i18nPagination,h=this.paginationLinksNode,g=this._currentPage,e=this.pagingLinks,l=this.paginationNavigationNode,f=Math.ceil(this._total/this.rowsPerPage),n=this._pagingTextBoxHandle;n&&n.remove();h.innerHTML="";s(".dgrid-first, .dgrid-previous",l).forEach(function(a){d(a,(1==g?".":"!")+"dgrid-page-disabled")});s(".dgrid-last, .dgrid-next",l).forEach(function(a){d(a,(g>=f?".":"!")+"dgrid-page-disabled")});if(e&&0<f){c(1);l=g-e;for(2<l?
d(h,"span.dgrid-page-skip","..."):l=2;l<Math.min(g+e+1,f);l++)c(l);g+e+1<f&&d(h,"span.dgrid-page-skip","...");1<f&&c(f)}else a.pagingTextBox&&c(g)},refresh:function(){var b=this;this.inherited(arguments);if(this.store)return this.gotoPage(1).then(function(c){setTimeout(function(){m.emit(b.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:b,results:c})},0);return c})},_onNotification:function(b){b.length!==this._rowsOnPage&&this.gotoPage(this._currentPage)},renderArray:function(b,c){var a=
this,d=this.inherited(arguments);this._lastCollection=null;c||(this._topLevelRequest&&(this._topLevelRequest.cancel(),delete this._topLevelRequest),"function"===typeof b.cancel&&(this._topLevelRequest=b),q.when(b,function(){a._topLevelRequest&&delete a._topLevelRequest}));return d},insertRow:function(){var b=this._oldPageNodes,c=this.inherited(arguments);b&&c===b[c.id]&&delete b[c.id];return c},gotoPage:function(b,c){var a=this,k=new q;this._trackError(function(){var h=a.rowsPerPage,g=(b-1)*h,e=x.mixin(a.get("queryOptions"),
{start:g,count:h}),l,f=a.contentNode,n,p,m;if(a.showLoadingMessage)z(a),n=a.loadingNode=d(f,"div.dgrid-loading"),n.innerHTML=a.loadingMessage;else{a._oldPageNodes=n={};f=f.children;p=0;for(m=f.length;p<m;p++)n[f[p].id]=f[p];a._oldPageObserver=a.observers.pop()}a._isLoading=!0;l=a.store.query(a.query,e);q.when(a.renderArray(l,null,e),function(e){u(a);a.scrollTo({y:0});q.when(l.total,function(f){f||(a.noDataNode&&(d(a.noDataNode,"!"),delete a.noDataNode),a.noDataNode=d(a.contentNode,"div.dgrid-no-data"),
a.noDataNode.innerHTML=a.noDataMessage);a.paginationStatusNode.innerHTML=t.substitute(a.i18nPagination.status,{start:Math.min(g+1,f),end:Math.min(f,g+h),total:f});a._total=f;a._currentPage=b;a._rowsOnPage=e.length;a._updateNavigation(c)});(7>r("ie")||r("ie")&&r("quirks"))&&a.resize();k.resolve(l)},function(b){u(a);k.reject(b)});return k.promise})||k.reject();return k.promise}})});
//@ sourceMappingURL=Pagination.js.map