//>>built
define("dojox/mobile/Slider","dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/_base/window dojo/sniff dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/keys dojo/touch dijit/_WidgetBase dijit/form/_FormValueMixin".split(" "),function(t,x,y,l,v,m,c,d,w,n,g,p,z,A){return y("dojox.mobile.Slider",[z,A],{value:0,min:0,max:100,step:1,baseClass:"mblSlider",flip:!1,orientation:"auto",halo:"8pt",buildRendering:function(){if(!this.templateString){this.focusNode=
this.domNode=d.create("div",{});this.valueNode=d.create("input",this.srcNodeRef&&this.srcNodeRef.name?{type:"hidden",name:this.srcNodeRef.name}:{type:"hidden"},this.domNode,"last");var b=d.create("div",{style:{position:"relative",height:"100%",width:"100%"}},this.domNode,"last");this.progressBar=d.create("div",{style:{position:"absolute"},"class":"mblSliderProgressBar"},b,"last");this.touchBox=d.create("div",{style:{position:"absolute"},"class":"mblSliderTouchBox"},b,"last");this.handle=d.create("div",
{style:{position:"absolute"},"class":"mblSliderHandle"},b,"last");this.handle.setAttribute("role","slider");this.handle.setAttribute("tabindex",0)}this.inherited(arguments);"undefined"!=typeof this.domNode.style.msTouchAction&&(this.domNode.style.msTouchAction="none")},_setMinAttr:function(b){this.handle.setAttribute("aria-valuemin",b);this._set("min",b)},_setMaxAttr:function(b){this.handle.setAttribute("aria-valuemax",b);this._set("max",b)},_setValueAttr:function(b,d){b=Math.max(Math.min(b,this.max),
this.min);this.valueNode.value=b;this.inherited(arguments);if(this._started){var h=100*(b-this.min)/(this.max-this.min);!0===d?(c.add(this.handle,"mblSliderTransition"),c.add(this.progressBar,"mblSliderTransition")):(c.remove(this.handle,"mblSliderTransition"),c.remove(this.progressBar,"mblSliderTransition"));n.set(this.handle,this._attrs.handleLeft,(this._reversed?100-h:h)+"%");n.set(this.progressBar,this._attrs.width,h+"%");this.handle.setAttribute("aria-valuenow",b)}},postCreate:function(){function b(a){function b(a){d=
g?a[this._attrs.pageX]:a.touches?a.touches[0][this._attrs.pageX]:a[this._attrs.clientX];h=d-s;h=Math.min(Math.max(h,0),q);a=this.step?(this.max-this.min)/this.step:q;if(1>=a||Infinity==a)a=q;var c=Math.round(h*a/q);k=(this.max-this.min)*c/a;k=this._reversed?this.max-k:this.min+k}a.target.focus();a.preventDefault();var g="mousedown"==a.type,f=w.position(r,!1),c=m("ie")||6<m("trident")?1:n.get(v.body(),"zoom")||1;isNaN(c)&&(c=1);var e=m("ie")||6<m("trident")?1:n.get(r,"zoom")||1;isNaN(e)&&(e=1);var s=
f[this._attrs.x]*e*c+w.docScroll()[this._attrs.x],q=f[this._attrs.w]*e*c;l.hitch(this,b)(a);a.target==this.touchBox&&this.set("value",k,!0);t.forEach(u,x.disconnect);a=v.doc.documentElement;var u=[this.connect(a,p.move,function(a){a.preventDefault();l.hitch(this,b)(a);this.set("value",k,!1)}),this.connect(a,p.release,function(a){a.preventDefault();t.forEach(u,l.hitch(this,"disconnect"));u=[];this.set("value",this.value,!0)})]}this.inherited(arguments);var d,h,k,r=this.domNode;"auto"==this.orientation&&
(this.orientation=r.offsetHeight<=r.offsetWidth?"H":"V");c.add(this.domNode,t.map(this.baseClass.split(" "),l.hitch(this,function(a){return a+this.orientation})));var f="V"!=this.orientation,s=f?this.isLeftToRight():!1,e=!!this.flip;this._reversed=!(f&&(s&&!e||!s&&e)||!f&&e);this._attrs=f?{x:"x",w:"w",l:"l",r:"r",pageX:"pageX",clientX:"clientX",handleLeft:"left",left:this._reversed?"right":"left",width:"width"}:{x:"y",w:"h",l:"t",r:"b",pageX:"pageY",clientX:"clientY",handleLeft:"top",left:this._reversed?
"bottom":"top",width:"height"};this.progressBar.style[this._attrs.left]="0px";this.connect(this.touchBox,p.press,b);this.connect(this.handle,p.press,b);this.connect(this.domNode,"onkeypress",function(a){if(!this.disabled&&!this.readOnly&&!a.altKey&&!a.ctrlKey&&!a.metaKey){var b=this.step,c=1;switch(a.keyCode){case g.HOME:b=this.min;break;case g.END:b=this.max;break;case g.RIGHT_ARROW:c=-1;case g.LEFT_ARROW:b=this.value+c*(e&&f?b:-b);break;case g.DOWN_ARROW:c=-1;case g.UP_ARROW:b=this.value+c*(!e||
f?b:-b);break;default:return}a.preventDefault();this._setValueAttr(b,!1)}});this.connect(this.domNode,"onkeyup",function(a){!this.disabled&&(!this.readOnly&&!a.altKey&&!a.ctrlKey&&!a.metaKey)&&this._setValueAttr(this.value,!0)});this.startup();this.set("value",this.value)}})});
//# sourceMappingURL=Slider.js.map