//>>built
define("dojox/html/ext-dojo/style","dojo/_base/kernel dojo/dom-style dojo/_base/lang dojo/_base/html dojo/_base/sniff dojo/_base/window dojo/dom dojo/dom-construct dojo/dom-style dojo/dom-attr".split(" "),function(N,P,B,x,G,L,H,M,C,O){N.experimental("dojox.html.ext-dojo.style");B.getObject("dojox.html.ext-dojo.style",!0);var I=B.getObject("dojox.html");B.mixin(I["ext-dojo"].style,{supportsTransform:!0,_toPx:function(n){var p=x.style,l=this._conversion;if("number"===typeof n)return n+"px";if(-1!=n.toLowerCase().indexOf("px"))return n;
!l.parentNode&&M.place(l,L.body());p(l,"margin",n);return p(l,"margin")},init:function(){var n=L.doc.documentElement.style,p=I["ext-dojo"].style,l=C.get,b=C.set;C.get=function(b,c){var f="transformOrigin"==c;return"transform"==c?p.getTransform(b):f?p.getTransformOrigin(b):l.apply(this,arguments)};C.set=function(c,f,l){var n="transform"==f,x="transformOrigin"==f,A=H.byId(c);return n?p.setTransform(A,l,!0):x?p.setTransformOrigin(A,l):b.apply(this,arguments)};for(var f=0,c=["WebkitT","MozT","OT","msT",
"t"];f<c.length;f++)"undefined"!==typeof n[c[f]+"ransform"]&&(this.tPropertyName=c[f]+"ransform"),"undefined"!==typeof n[c[f]+"ransformOrigin"]&&(this.toPropertyName=c[f]+"ransformOrigin");this.tPropertyName?(this.setTransform=function(c,f){return b(c,this.tPropertyName,f)},this.getTransform=function(b){return l(b,this.tPropertyName)}):G("ie")&&(this.setTransform=this._setTransformFilter,this.getTransform=this._getTransformFilter);this.toPropertyName?(this.setTransformOrigin=function(c,f){return b(c,
this.toPropertyName,f)},this.getTransformOrigin=function(b){return l(b,this.toPropertyName)}):G("ie")?(this.setTransformOrigin=this._setTransformOriginFilter,this.getTransformOrigin=this._getTransformOriginFilter):this.supportsTransform=!1;this._conversion=M.create("div",{style:{position:"absolute",top:"-100px",left:"-100px",fontSize:0,width:"0",backgroundPosition:"50% 50%"}})},_notSupported:function(){},_setTransformOriginFilter:function(n,p){for(var l=B.trim(p).replace(" top"," 0").replace("left ",
"0 ").replace(" center","50%").replace("center ","50% ").replace(" bottom"," 100%").replace("right ","100% ").replace(/\s+/," ").split(" "),b=H.byId(n),f=this.getTransform(b),c=!0,h=0;h<l.length;h++)c=c&&/^0|(\d+(%|px|pt|in|pc|mm|cm))$/.test(l[h]),-1==l[h].indexOf("%")&&(l[h]=this._toPx(l[h]));if(!c||!l.length||2<l.length)return p;x.attr(b,"dojo-transform-origin",l.join(" "));f&&this.setTransform(n,f);return p},_getTransformOriginFilter:function(n){return x.attr(n,"dojo-transform-origin")||"50% 50%"},
_setTransformFilter:function(n,p){var l=p.replace(/\s/g,""),b=H.byId(n),f=l.split(")"),c=1,h=1,l=O.has,t=x.attr,r=Math.PI,B=Math.cos,C=Math.sin,A=Math.tan,q=Math.max,u=Math.min,D=Math.abs,E=r/180,F=r/200,d="",d="",d=[],v=0,z=0,y=0,J=0,s=0,m=0,c=0,c=1,g=h=0,e=1,w=0,k=0,a=[c,h,g,e,w,k],z=!1,r=x.style,K="absolute"==r(b,"position")?"absolute":"relative",s=r(b,"width")+r(b,"paddingLeft")+r(b,"paddingRight"),v=r(b,"height")+r(b,"paddingTop")+r(b,"paddingBottom"),y=this._toPx;!l(b,"dojo-transform-origin")&&
this.setTransformOrigin(b,"50% 50%");m=0;for(J=f.length;m<J;m++){d=(d=f[m].match(/matrix|rotate|scaleX|scaleY|scale|skewX|skewY|skew|translateX|translateY|translate/))?d[0]:"";switch(d){case "matrix":d=f[m].replace(/matrix\(|\)/g,"");k=d.split(",");c=a[0]*k[0]+a[1]*k[2];h=a[0]*k[1]+a[1]*k[3];g=a[2]*k[0]+a[3]*k[2];e=a[2]*k[1]+a[3]*k[3];w=a[4]+k[4];k=a[5]+k[5];break;case "rotate":d=f[m].replace(/rotate\(|\)/g,"");c=-1!=d.indexOf("deg")?E:-1!=d.indexOf("grad")?F:1;c*=parseFloat(d);e=C(c);d=B(c);c=a[0]*
d+a[1]*e;h=-a[0]*e+a[1]*d;g=a[2]*d+a[3]*e;e=-a[2]*e+a[3]*d;break;case "skewX":d=f[m].replace(/skewX\(|\)/g,"");c=-1!=d.indexOf("deg")?E:-1!=d.indexOf("grad")?F:1;e=A(parseFloat(d)*c);c=a[0];h=a[0]*e+a[1];g=a[2];e=a[2]*e+a[3];break;case "skewY":d=f[m].replace(/skewY\(|\)/g,"");c=-1!=d.indexOf("deg")?E:-1!=d.indexOf("grad")?F:1;e=A(parseFloat(d)*c);c=a[0]+a[1]*e;h=a[1];g=a[2]+a[3]*e;e=a[3];break;case "skew":d=f[m].replace(/skew\(|\)/g,"");g=d.split(",");g[1]=g[1]||"0";c=-1!=g[0].indexOf("deg")?E:-1!=
g[0].indexOf("grad")?F:1;h=-1!=g[1].indexOf("deg")?E:-1!=g[1].indexOf("grad")?F:1;e=A(parseFloat(g[0])*c);g=A(parseFloat(g[1])*h);c=a[0]+a[1]*g;h=a[0]*e+a[1];g=a[2]+a[3]*g;e=a[2]*e+a[3];break;case "scaleX":d=parseFloat(f[m].replace(/scaleX\(|\)/g,""))||1;c=a[0]*d;h=a[1];g=a[2]*d;e=a[3];break;case "scaleY":d=parseFloat(f[m].replace(/scaleY\(|\)/g,""))||1;c=a[0];h=a[1]*d;g=a[2];e=a[3]*d;break;case "scale":d=f[m].replace(/scale\(|\)/g,"");e=d.split(",");e[1]=e[1]||e[0];c=a[0]*e[0];h=a[1]*e[1];g=a[2]*
e[0];e=a[3]*e[1];break;case "translateX":d=parseInt(f[m].replace(/translateX\(|\)/g,""))||1;c=a[0];h=a[1];g=a[2];e=a[3];(w=y(d))&&t(b,"dojo-transform-matrix-tx",w);break;case "translateY":d=parseInt(f[m].replace(/translateY\(|\)/g,""))||1;c=a[0];h=a[1];g=a[2];e=a[3];(k=y(d))&&t(b,"dojo-transform-matrix-ty",k);break;case "translate":d=f[m].replace(/translate\(|\)/g,""),c=a[0],h=a[1],g=a[2],e=a[3],k=d.split(","),k[0]=parseInt(y(k[0]))||0,k[1]=parseInt(y(k[1]))||0,w=k[0],k=k[1],w&&t(b,"dojo-transform-matrix-tx",
w),k&&t(b,"dojo-transform-matrix-ty",k)}a=[c,h,g,e,w,k]}f=u(s*c+v*h,u(u(s*c,v*h),0));u=u(s*g+v*e,u(u(s*g,v*e),0));y=-f;J=-u;8>G("ie")?(b.style.zoom="1","absolute"!=K&&(u=r(n.parentNode,"width"),f=D(s*c),D=D(v*h),q=q(f+D,q(q(D,f),0)),y-=(q-s)/2-(u>q?0:(q-u)/2))):8==G("ie")&&"auto"==r(b,"zIndex")&&(b.style.zIndex="0");try{z=!!b.filters.item("DXImageTransform.Microsoft.Matrix")}catch(I){z=!1}z?(b.filters.item("DXImageTransform.Microsoft.Matrix").M11=c,b.filters.item("DXImageTransform.Microsoft.Matrix").M12=
h,b.filters.item("DXImageTransform.Microsoft.Matrix").M21=g,b.filters.item("DXImageTransform.Microsoft.Matrix").M22=e,b.filters.item("DXImageTransform.Microsoft.Matrix").filterType="bilinear",b.filters.item("DXImageTransform.Microsoft.Matrix").Dx=0,b.filters.item("DXImageTransform.Microsoft.Matrix").Dy=0,b.filters.item("DXImageTransform.Microsoft.Matrix").sizingMethod="auto expand"):b.style.filter+=" progid:DXImageTransform.Microsoft.Matrix(M11\x3d"+c+",M12\x3d"+h+",M21\x3d"+g+",M22\x3d"+e+",FilterType\x3d'bilinear',Dx\x3d0,Dy\x3d0,sizingMethod\x3d'auto expand')";
w=parseInt(t(b,"dojo-transform-matrix-tx")||"0");k=parseInt(t(b,"dojo-transform-matrix-ty")||"0");q=t(b,"dojo-transform-origin").split(" ");for(m=0;2>m;m++)q[m]=q[m]||"50%";s=-1!=q[0].toString().indexOf("%")?0.01*s*parseInt(q[0]):q[0];m=-1!=q[1].toString().indexOf("%")?0.01*v*parseInt(q[1]):q[1];l(b,"dojo-startX")?v=parseInt(t(b,"dojo-startX")):(v=parseInt(r(b,"left")),t(b,"dojo-startX","absolute"==K?v:"0"));l(b,"dojo-startY")?z=parseInt(t(b,"dojo-startY")):(z=parseInt(r(b,"top")),t(b,"dojo-startY",
"absolute"==K?z:"0"));r(b,{position:K,left:v-parseInt(y)+parseInt(s)-((parseInt(s)-w)*c+(parseInt(m)-k)*h)+"px",top:z-parseInt(J)+parseInt(m)-((parseInt(s)-w)*g+(parseInt(m)-k)*e)+"px"});return p},_getTransformFilter:function(n){try{var p=H.byId(n).filters.item(0);return"matrix("+p.M11+", "+p.M12+", "+p.M21+", "+p.M22+", "+(x.attr(n,"dojo-transform-tx")||"0")+", "+(x.attr(n,"dojo-transform-ty")||"0")+")"}catch(l){return"matrix(1, 0, 0, 1, 0, 0)"}},setTransform:function(){this._notSupported()},setTransformOrigin:function(){this._notSupported()}});
I["ext-dojo"].style.init();return x.style});
//# sourceMappingURL=style.js.map