/**
 * Copyright (C) 2017 Infinite Automation Software. All rights reserved.
 *
 */
package com.serotonin.m2m2.db.upgrade;

import java.util.HashMap;
import java.util.Map;

import com.serotonin.m2m2.db.DatabaseProxy;

/**
 * Add ID to UserComments Table with Indexes
 * 
 * 
 * @author Terry Packer
 */
public class Upgrade14 extends DBUpgrade{
	
	/* (non-Javadoc)
	 * @see com.serotonin.m2m2.db.upgrade.DBUpgrade#upgrade()
	 */
	@Override
	protected void upgrade() throws Exception {
	    // Run the script.
        Map<String, String[]> scripts = new HashMap<>();
        scripts.put(DatabaseProxy.DatabaseType.DERBY.name(), derbyScript);
        scripts.put(DatabaseProxy.DatabaseType.MYSQL.name(), mysqlScript);
        scripts.put(DatabaseProxy.DatabaseType.MSSQL.name(), mssqlScript);
        scripts.put(DatabaseProxy.DatabaseType.H2.name(), h2Script);
        runScript(scripts);
	}

	/* (non-Javadoc)
	 * @see com.serotonin.m2m2.db.upgrade.DBUpgrade#getNewSchemaVersion()
	 */
	@Override
	protected String getNewSchemaVersion() {
		return "15";
	}
	
	private final String[] mssqlScript = {
			"ALTER TABLE userComments ADD COLUMN id INT;", 
			"ALTER TABLE userComments ADD PRIMARY KEY(id);",
			"ALTER TABLE userComments ALTER COLUMN id INT NOT NULL;"			
	    };
	private final String[] derbyScript = {
	    	"ALTER TABLE userComments ADD COLUMN id INT NOT NULL generated by default as identity (start with 1, increment by 1);",
	    };
	private final String[] mysqlScript = {
			"ALTER TABLE userComments ADD id int NOT NULL AUTO_INCREMENT primary key FIRST;"
	    };
	private final String[] h2Script = {
			"ALTER TABLE userComments ADD COLUMN id INT NOT NULL auto_increment;",
	    };
	
}
