//>>built
define("dgrid-0.4/Editor","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/on dojo/has dojo/query ./Grid put-selector/put dojo/_base/sniff".split(" "),function(s,p,q,l,r,t,u,m){return s(null,{constructor:function(){this._editorInstances={};this._editorColumnListeners=[];this._editorsPendingStartup=[]},postCreate:function(){var a=this;this.inherited(arguments);this.on(".dgrid-input:focusin",function(){a._focusedEditorCell=a.cell(this)});this._editorFocusoutHandle=l.pausable(this.domNode,".dgrid-input:focusout",
function(){a._focusedEditorCell=null});this._listeners.push(this._editorFocusoutHandle)},insertRow:function(){var a=this.inherited(arguments),b=this.row(a),c=this._previouslyFocusedEditorCell;c&&c.row.id===b.id&&this.edit(this.cell(b,c.column.id));return a},removeRow:function(a){var b=this,c=this._focusedEditorCell;c&&c.row.id===this.row(a).id&&(this._previouslyFocusedEditorCell=c,this._editorFocusoutHandle.pause(),setTimeout(function(){b._editorFocusoutHandle.resume();b._previouslyFocusedEditorCell=
null},0));for(c=this._alwaysOnWidgetColumns.length;c--;){var d=this.cell(a,this._alwaysOnWidgetColumns[c].id).element;if(d=d&&(d.contents||d).widget)this._editorFocusoutHandle.pause(),d.destroyRecursive()}return this.inherited(arguments)},renderArray:function(){var a=this.inherited(arguments);a.length?this._startupPendingEditors():this._editorsPendingStartup=[];return a},_onNotification:function(){this.inherited(arguments);this._startupPendingEditors()},_destroyColumns:function(){this._editorStructureCleanup();
this.inherited(arguments)},_editorStructureCleanup:function(){var a=this._editorInstances,b=this._editorColumnListeners;this._editTimer&&clearTimeout(this._editTimer);for(var c in a){var d=a[c];d.domNode&&d.destroyRecursive()}this._editorInstances={};for(a=b.length;a--;)b[a].remove();this._editorColumnListeners=[];this._editorsPendingStartup=[]},_configColumns:function(){var a=this.inherited(arguments);this._alwaysOnWidgetColumns=[];for(var b=0,c=a.length;b<c;b++)a[b].editor&&this._configureEditorColumn(a[b]);
return a},_configureEditorColumn:function(a){var b=this,c=a.renderCell||this._defaultRenderCell,d=a.editOn,g="string"!==typeof a.editor;d?this._editorInstances[a.id]=this._createSharedEditor(a,c):g&&this._alwaysOnWidgetColumns.push(a);a.renderCell=d?function(k,g,h,e){(!e||!e.alreadyHooked)&&b._editorColumnListeners.push(l(h,d,function(){b._activeOptions=e;b.edit(this)}));return c.call(a,k,g,h,e)}:function(d,f,h,e){if(!a.canEdit||a.canEdit(d,f))d=b._createEditor(a),b._showEditor(d,a,h,f),h[g?"widget":
"input"]=d;else return c.call(a,d,f,h,e)}},edit:function(a){function b(a){c._activeCell=g;c._showEditor(e,d,g,h);c._editTimer=setTimeout(function(){e.focus&&e.focus();d._editorBlurHandle&&d._editorBlurHandle.resume();c._editTimer=null;a.resolve(e)},0)}var c=this,d,g,k,f,h,e,l;a.column||(a=this.cell(a));if(!a||!a.element)return null;d=a.column;f=d.field;g=a.element.contents||a.element;if(e=this._editorInstances[d.id]){if(this._activeCell!==g){var n=a.row;h=(k=this.dirty&&this.dirty[n.id])&&f in k?
k[f]:d.get?d.get(n.data):n.data[f];if(!d.canEdit||d.canEdit(a.row.data,h))return l=new q,a=e.domNode||e,a.offsetWidth?(a.blur(),setTimeout(function(){b(l)},0)):b(l),l.promise}}else if(d.editor&&(e=g.widget||g.input))return l=new q,e.focus&&e.focus(),l.resolve(e),l.promise;return null},_showEditor:function(a,b,c,d){var g=a.domNode;g||this._updateInputValue(a,d);c.innerHTML="";m(c,".dgrid-cell-editing");m(c,a.domNode||a);g&&!b.editOn?this._editorsPendingStartup.push([a,b,c,d]):this._startupEditor(a,
b,c,d)},_startupEditor:function(a,b,c,d){a.domNode&&(a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",d),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=d;this._activeCell&&(this._activeValue=d,l.emit(c,"dgrid-editor-show",{grid:this,cell:this.cell(c),column:b,editor:a,bubbles:!0,cancelable:!1}))},_startupPendingEditors:function(){for(var a=this._editorsPendingStartup,b=a.length;b--;)this._startupEditor.apply(this,a[b]);this._editorsPendingStartup=[]},_handleEditorChange:function(a,
b){var c=a.target;"_dgridLastValue"in c&&-1<c.className.indexOf("dgrid-input")&&this._updatePropertyFromEditor(b||this.cell(c).column,c,a)},_createEditor:function(a){var b=a.editor,c=a.editOn,d=this,g="string"!==typeof b&&b,k,f;k=a.editorArgs||{};"function"===typeof k&&(k=k.call(this,a));g?(f=new g(k),g=f.focusNode||f.domNode,g.className+=" dgrid-input",f.on(c?"blur":"change",function(){f._dgridIgnoreChange||d._updatePropertyFromEditor(a,this,{type:"widget"})})):(this._hasInputListener||(this._hasInputListener=
!0,this.on("change",function(a){d._handleEditorChange(a)})),f=g=m(("textarea"===b?"textarea":"input[type\x3d"+b+"]")+".dgrid-input",p.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},k)),9>r("ie")&&("radio"===b||"checkbox"===b?this._editorColumnListeners.push(l(f,"click",function(b){d._handleEditorChange(b,a)})):this._editorColumnListeners.push(l(f,"change",function(b){d._handleEditorChange(b,a)}))));if(a.autoSelect){var h=f.focusNode||f;h.select&&l(h,"focus",function(){setTimeout(function(){h.select()},
0)})}return f},_createSharedEditor:function(a){function b(){var a=d._activeCell;f.blur();"function"===typeof d.focus&&setTimeout(function(){d.focus(a)},g&&9>r("ie")?15:0)}var c=this._createEditor(a),d=this,g=c.domNode,k=c.domNode||c,f=c.focusNode||k,h=g?function(){c.set("value",c._dgridLastValue)}:function(){d._updateInputValue(c,c._dgridLastValue);d._updatePropertyFromEditor(a,c)};this._editorColumnListeners.push(l(f,"keydown",function(e){e=e.keyCode||e.which;27===e?(h(),d._activeValue=c._dgridLastValue,
b()):13===e&&!1!==a.dismissOnEnter&&b()}));(a._editorBlurHandle=l.pausable(c,"blur",function(){var b=k.parentNode,g=b.children.length-1,f={alreadyHooked:!0},h=d.cell(k);l.emit(h.element,"dgrid-editor-hide",{grid:d,cell:h,column:a,editor:c,bubbles:!0,cancelable:!1});a._editorBlurHandle.pause();b.removeChild(k);if(h.row){for(m(h.element,"!dgrid-cell-editing");g--;)m(b.firstChild,"!");u.appendIfNode(b,a.renderCell(h.row.data,d._activeValue,b,d._activeOptions?p.delegate(f,d._activeOptions):f))}d._focusedEditorCell=
d._activeCell=d._activeValue=d._activeOptions=null})).pause();this._editorColumnListeners.push(a._editorBlurHandle);return c},_updatePropertyFromEditor:function(a,b,c){var d;if(!b.isValid||b.isValid())if(c=this._updateProperty((b.domNode||b).parentNode,this._activeCell?this._activeValue:b._dgridLastValue,this._retrieveEditorValue(a,b),c),this._activeCell?this._activeValue=c:b._dgridLastValue=c,"radio"===b.type&&b.name&&!a.editOn&&a.field)for(d in c=this.row(b),t("input[type\x3dradio][name\x3d"+b.name+
"]",this.contentNode).forEach(function(c){var d=this.row(c);c!==b&&c._dgridLastValue&&(c._dgridLastValue=!1,this.updateDirty?this.updateDirty(d.id,a.field,!1):d.data[a.field]=!1)},this),this.dirty)c.id.toString()!==d&&this.dirty[d][a.field]&&this.updateDirty(d,a.field,!1)},_updateProperty:function(a,b,c,d){var g=this;if((b&&b.valueOf())!==(c&&c.valueOf())){var k=this.cell(a),f=k.row,h=k.column;a=k.element;if(h.field&&f)if(k={grid:this,cell:k,oldValue:b,value:c,bubbles:!0,cancelable:!0},d&&d.type&&
(k.parentType=d.type),l.emit(a,"dgrid-datachange",k))this.updateDirty?(this.updateDirty(f.id,h.field,c),h.autoSave&&setTimeout(function(){g._trackError("save")},0)):f.data[h.field]=c;else{var e;(e=a.widget)?(e._dgridIgnoreChange=!0,e.set("value",b),setTimeout(function(){e._dgridIgnoreChange=!1},0)):(e=a.input)&&this._updateInputValue(e,b);return b}}return c},_updateInputValue:function(a,b){a.value=b;if("radio"===a.type||"checkbox"===a.type)a.checked=a.defaultChecked=!!b},_retrieveEditorValue:function(a,
b){return"function"===typeof b.get?this._convertEditorValue(b.get("value")):this._convertEditorValue(b["checkbox"===b.type||"radio"===b.type?"checked":"value"])},_convertEditorValue:function(a,b){if("number"===typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"===typeof b)a="true"===a?!0:"false"===a?!1:a;else if(b instanceof Date){var c=new Date(a);a=isNaN(c.getTime())?a:c}return a}})});
//# sourceMappingURL=Editor.js.map