//>>built
define("dgrid-0.4/List","dojo/_base/declare dojo/on dojo/has ./util/misc xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),function(r,n,e,k,v,d){function s(a,b){d(document.body,a,".dgrid-scrollbar-measure");var c=a["offset"+b]-a["client"+b];a.className="";a.parentNode&&document.body.removeChild(a);return c}function p(a){var b=a?"."+a.replace(t,"."):"";this._class&&(b="!"+this._class.replace(t,"!")+b);d(this.domNode,b);this._class=a}function u(){return this._class}
v("mozilla","touch");e.add("pointer",function(a){return"PointerEvent"in a?"pointer":"MSPointerEvent"in a?"MSPointer":!1});var h,q;e.add("dom-scrollbar-width",function(a,b,c){return s(c,"Width")});e.add("dom-scrollbar-height",function(a,b,c){return s(c,"Height")});e.add("dom-rtl-scrollbar-left",function(a,b,c){a=d("div");d(document.body,c,".dgrid-scrollbar-measure[dir\x3drtl]");d(c,a);b=!!e("ie")||!!e("trident")||a.offsetLeft>=e("dom-scrollbar-width");c.className="";c.parentNode&&document.body.removeChild(c);
d(a,"!");c.removeAttribute("dir");return b});var w=0,t=/ +/g,x=function(){this._started&&this.resize()};return r(null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,cleanAddedRules:!0,addUiClasses:!0,highlightDuration:250,postscript:function(a,b){var c=this;(this._Row=function(a,b,c){this.id=a;this.data=b;this.element=c}).prototype.remove=function(){c.removeRow(this.element)};b&&(this.srcNodeRef=b=b.nodeType?b:document.getElementById(b));this.create(a,b)},listType:"list",create:function(a,
b){var c=this.domNode=b||d("div"),l;a&&(this.params=a,r.safeMixin(this,a),l=a["class"]||a.className||c.className);this.sort=this.sort||[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=c.id=c.id||this.id||"dgrid_"+w++;this.buildRendering();l&&p.call(this,l);this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this.addUiClasses,c=this,l,g,m,f;f=this.isRTL="rtl"===(document.body.dir||
document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";d(a,"[role\x3dgrid].dgrid.dgrid-"+this.listType+(b?".ui-widget":""));l=this.headerNode=d(a,"div.dgrid-header.dgrid-header-row"+(b?".ui-widget-header":"")+(this.showHeader?"":".dgrid-header-hidden"));g=this.bodyNode=d(a,"div.dgrid-scroller");e("ff")&&(g.tabIndex=-1);this.headerScrollNode=d(a,"div.dgrid-header.dgrid-header-scroll.dgrid-scrollbar-width"+(b?".ui-widget-header":""));m=this.footerNode=d("div.dgrid-footer"+
(this.showFooter?"":".dgrid-footer-hidden"));d(a,m);f&&(a.className+=" dgrid-rtl"+(e("dom-rtl-scrollbar-left")?" dgrid-rtl-swap":""));n(g,"scroll",function(b){c.showHeader&&(l.scrollLeft=b.scrollLeft||g.scrollLeft);b.stopPropagation();n.emit(a,"scroll",{scrollTarget:g})});this.configStructure();this.renderHeader();this.contentNode=this.touchNode=d(this.bodyNode,"div.dgrid-content"+(b?".ui-widget-content":""));this._listeners.push(this._resizeHandle=n(window,"resize",k.throttleDelayed(x,this)))},postCreate:function(){},
startup:function(){this._started||(this.inherited(arguments),this._started=!0,this.resize(),this.set("sort",this.sort))},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.footerNode,b=this.showFooter?b.offsetHeight:0;this.headerScrollNode.style.height=a.style.marginTop=this.headerNode.offsetHeight+"px";a.style.marginBottom=b+"px";h||(h=e("dom-scrollbar-width"),q=e("dom-scrollbar-height"),e("ie")&&(h++,q++),k.addCssRule(".dgrid-scrollbar-width","width: "+h+"px"),k.addCssRule(".dgrid-scrollbar-height",
"height: "+q+"px"),17!==h&&(k.addCssRule(".dgrid-header-row","right: "+h+"px"),k.addCssRule(".dgrid-rtl-swap .dgrid-header-row","left: "+h+"px")))},addCssRule:function(a,b){var c=k.addCssRule(a,b);this.cleanAddedRules&&this._listeners.push(c);return c},on:function(a,b){var c=n(this.domNode,a,b);e("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){for(var a in this._rowIdToObject)if(this._rowIdToObject[a]!==this.columns){var b=document.getElementById(a);b&&this.removeRow(b,
!0)}},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();this._listeners=null}this._started=!1;this.cleanup();d(this.domNode,"!")},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},highlightRow:function(a,b){a=a.element||a;d(a,".dgrid-highlight"+(this.addUiClasses?".ui-state-highlight":""));setTimeout(function(){d(a,"!dgrid-highlight!ui-state-highlight")},b||this.highlightDuration)},
adjustRowIndices:function(a){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(this.maintainOddEven&&-1<(a.className+" ").indexOf("dgrid-row ")&&d(a,"."+(1===b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0===b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++);while((a=a.nextSibling)&&a.rowIndex!==b)}},renderArray:function(a,b,c){c=c||{};var d=c.start||0,g=document.createDocumentFragment(),m=[],f=0,e=a.length;b||(this._lastCollection=a);for(;f<e;)m[f]=this.insertRow(a[f],g,null,d++,c),f++;if((a=b?b.parentNode:
this.contentNode)&&a.parentNode&&(a!==this.contentNode||e))a.insertBefore(g,b||null),e&&this.adjustRowIndices(m[e-1]);return m},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,d,g){var e=this.id+"-row-"+(this.collection&&this.collection.getIdentity?this.collection.getIdentity(a):this._autoId++),f=document.getElementById(e),h=f&&f.previousSibling;f&&(f===c&&(c=(c.connected||c).nextSibling),this.removeRow(f));f=this.renderRow(a,g);f.className=(f.className||"")+" dgrid-row "+(1===d%2?"dgrid-row-odd":
"dgrid-row-even")+(this.addUiClasses?" ui-state-default":"");this._rowIdToObject[f.id=e]=a;b.insertBefore(f,c||null);f.rowIndex=d;h&&h.rowIndex!==f.rowIndex-1&&this.adjustRowIndices(h);return f},renderRow:function(a){return d("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||d(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+
5),b,a);a=a.parentNode}while(a&&a!==this.domNode)}else return"object"===typeof a?b=this.collection.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,d){var g,e;e=g=a.element;b=b||1;do if(a=g[0>b?"previousSibling":"nextSibling"]){do if((g=a)&&-1<(g.className+" ").indexOf(c+" ")){e=g;b+=0>b?1:-1;break}while(a=(!d||!g.hidden)&&g[0>b?"lastChild":"firstChild"])}else if(g=
g.parentNode,!g||g===this.bodyNode||g===this.headerNode)break;while(b);return e},up:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:function(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)},getScrollPosition:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},
get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:u,_setClass:p,_getClassName:u,_setClassName:p,_setSort:function(a,b){this.sort="string"!==typeof a?a:[{property:a,
descending:b}];this._applySort()},_applySort:function(){this.refresh();if(this._lastCollection){var a=this.sort;if(a&&0<a.length){var b=a[0].property,c=!!a[0].descending;this._lastCollection.sort(function(a,d){var e=a[b],f=d[b];void 0===e&&(e="");void 0===f&&(f="");return e===f?0:e>f!==c?1:-1})}this.renderArray(this._lastCollection)}},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=a;d(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},
_setShowFooter:function(a){this.showFooter=a;d(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})});
//# sourceMappingURL=List.js.map