//>>built
define("dgrid-0.4/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/on dojo/when ./util/misc put-selector/put".split(" "),function(C,D,E,F,w,t,u,p){return E([C,D],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:0,pagingMethod:"debounce",pagingDelay:u.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;w(this.bodyNode,"scroll",u[this.pagingMethod](function(g){c._processScroll(g)},
null,this.pagingDelay))},renderQuery:function(c,g){var h=this,l=g&&g.container||this.contentNode,a={query:c,count:0},k,q=this.preload,f={node:p(l,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:a};f.node.style.height="0";a.node=k=p(l,"div.dgrid-preload");a.previous=f;k.rowIndex=this.minRowsPerPage;q?((a.next=q.next)&&k.offsetTop>=q.node.offsetTop?a.previous=q:(a.next=q,a.previous=q.previous),a.previous.next=a,a.next.previous=a):this.preload=a;var b=p(k,"-div.dgrid-loading");p(b,"div.dgrid-below").innerHTML=
this.loadingMessage;g=F.mixin({start:0,count:this.minRowsPerPage},"level"in c?{queryLevel:c.level}:null);return this._trackError(function(){var f=c(g);return h.renderQueryResults(f,k,g).then(function(c){return t(f.totalLength,function(f){var l=c.length,n=k.parentNode,d=h.noDataNode;h._rows&&(h._rows.min=0,h._rows.max=l===f?Infinity:l-1);p(b,"!");"queryLevel"in g||(h._total=f);0===f&&(d&&(p(d,"!"),delete h.noDataNode),h.noDataNode=d=p("div.dgrid-no-data"),n.insertBefore(d,h._getFirstRowSibling(n)),
d.innerHTML=h.noDataMessage);for(d=n=0;d<l;d++)n+=h._calcRowHeight(c[d]);l&&n&&(h.rowHeight=n/l);f-=l;a.count=f;k.rowIndex=l;f?k.style.height=Math.min(f*h.rowHeight,h.maxEmptySpace)+"px":k.style.display="none";h._previousScrollPosition&&(h.scrollTo(h._previousScrollPosition),delete h._previousScrollPosition);return t(h._processScroll()).then(function(){return c})})}).otherwise(function(a){p(b,"!");throw a;})})},refresh:function(c){var g=this,h=c&&c.keepScrollPosition;"undefined"===typeof h&&(h=this.keepScrollPosition);
h&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this._renderedCollection)return this.renderQuery(function(c){return g._renderedCollection.fetchRange({start:c.start,end:c.start+c.count})}).then(function(){setTimeout(function(){w.emit(g.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:g})},0)})},resize:function(){this.inherited(arguments);this._processScroll()},cleanup:function(){this.inherited(arguments);this.preload=null},renderQueryResults:function(c){var g=
this.inherited(arguments),h=this._renderedCollection;h&&h.releaseRange&&t(g,function(g){g[0]&&!g[0].parentNode.tagName&&t(c.totalLength,function(){h.releaseRange(g[0].rowIndex,g[g.length-1].rowIndex+1)})});return g},_getFirstRowSibling:function(c){return c.lastChild},_calcRowHeight:function(c){var g=c.nextSibling;return g&&!/\bdgrid-preload\b/.test(g.className)?g.offsetTop-c.offsetTop:c.offsetHeight},lastScrollTop:0,_processScroll:function(c){function g(b,c,d,f){var g=a.farOffRemoval,e=b.node;if(c>
2*g){for(var k,l=e[d],m=0,n=0,s=[],q=l&&l.rowIndex,r;k=l;){var t=a._calcRowHeight(k);if(m+t+g>c||0>l.className.indexOf("dgrid-row")&&0>l.className.indexOf("dgrid-loading"))break;l=k[d];m+=t;n+=k.count||1;a.removeRow(k,!0);s.push(k);"rowIndex"in k&&(r=k.rowIndex)}a._renderedCollection.releaseRange&&("number"===typeof q&&"number"===typeof r)&&(f?a._renderedCollection.releaseRange(r,q+1):a._renderedCollection.releaseRange(q,r+1),a._rows[f?"max":"min"]=r,a._rows.max>=a._total-1&&(a._rows.max=Infinity));
b.count+=n;f?(e.rowIndex-=n,h(b)):e.style.height=e.offsetHeight+m+"px";var u=p("div",s);setTimeout(function(){p(u,"!")},1)}}function h(b,c){b.node.style.height=Math.min(b.count*a.rowHeight,c?Infinity:a.maxEmptySpace)+"px"}function l(a,b){do a=b?a.next:a.previous;while(a&&!a.node.offsetWidth);return a}var a=this,k=a.bodyNode;c=c&&c.scrollTop||this.getScrollPosition().y;var k=k.offsetHeight+c,q,f,b=a.preload,w=a.lastScrollTop,y=a.bufferRows*a.rowHeight,u=y-a.rowHeight,B,n=!0;for(a.lastScrollTop=c;b&&
!b.node.offsetWidth;)b=b.previous;for(;b&&b!==q;){q=a.preload;a.preload=b;f=b.node;var d=f.offsetTop;if(k+1+u<d)b=l(b,n=!1);else if(c-1-u>d+f.offsetHeight)b=l(b,n=!0);else{var d=((f.rowIndex?c-y:k)-d)/a.rowHeight,e=(k-c+2*y)/a.rowHeight,r=Math.max(Math.min((c-w)*a.rowHeight,a.maxRowsPerPage/2),a.maxRowsPerPage/-2),e=e+Math.min(Math.abs(r),10);0===f.rowIndex&&(d-=e);d=Math.max(d,0);10>d&&(0<d&&e+d<a.maxRowsPerPage)&&(e+=Math.max(0,d),d=0);e=Math.min(Math.max(e,a.minRowsPerPage),a.maxRowsPerPage,b.count);
if(0===e)b=l(b,n);else{var e=Math.ceil(e),d=Math.min(Math.floor(d),b.count-e),m={};b.count-=e;var s=f,x,r=a.queryRowsOverlap,z=(0<f.rowIndex||f.offsetTop>c)&&b;if(z){var v=b.previous;v&&(g(v,c-(v.node.offsetTop+v.node.offsetHeight),"nextSibling"),0<d&&v.node===f.previousSibling?(d=Math.min(b.count,d),b.previous.count+=d,h(b.previous,!0),f.rowIndex+=d,r=0):e+=d,b.count-=d);m.start=f.rowIndex-r;m.count=Math.min(e+r,a.maxRowsPerPage);f.rowIndex=m.start+m.count}else b.next&&(g(b.next,b.next.node.offsetTop-
k,"previousSibling",!0),s=f.nextSibling,s===b.next.node?(b.next.count+=b.count-d,b.next.node.rowIndex=d+e,h(b.next),b.count=d,r=0):x=!0),m.start=b.count,m.count=Math.min(e+r,a.maxRowsPerPage);x&&(s&&s.offsetWidth)&&(x=s.offsetTop);h(b);"level"in b.query&&(m.queryLevel=b.query.level);if("queryLevel"in m||!(m.start>a._total||0>m.count)){var A=p(s,"-div.dgrid-loading[style\x3dheight:"+e*a.rowHeight+"px]");p(A,"div.dgrid-"+(z?"below":"above")).innerHTML=a.loadingMessage;A.count=e;a._trackError(function(){(function(c,
d,f){var g=b.query(m);B=a.renderQueryResults(g,c,m).then(function(b){var e=a._rows;e&&(!("queryLevel"in m)&&b.length)&&(d?(e.max<=e.min&&(e.min=b[0].rowIndex),e.max=b[b.length-1].rowIndex):(e.max<=e.min&&(e.max=b[b.length-1].rowIndex),e.min=b[0].rowIndex));s=c.nextSibling;p(c,"!");f&&(s&&s.offsetWidth)&&(e=a.getScrollPosition(),a.scrollTo({x:e.x,y:e.y+s.offsetTop-f,preserveMomentum:!0}));t(g.totalLength,function(b){"queryLevel"in m||(a._total=b,a._rows&&a._rows.max>=a._total-1&&(a._rows.max=Infinity));
d&&(d.count=b-d.node.rowIndex,h(d))});a._processScroll();return b},function(a){p(c,"!");throw a;})})(A,z,x)});b=b.previous}}}}return B}})});
//# sourceMappingURL=OnDemandList.js.map