//>>built
define("dgrid-0.4/Tree","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/aspect dojo/on dojo/query dojo/when ./util/has-css3 ./Grid dojo/has!touch?./util/touch put-selector/put".split(" "),function(u,v,w,A,x,s,y,t,B,m,g){return u(null,{collapseOnRefresh:!1,enableTreeTransitions:!0,treeIndentWidth:9,constructor:function(){this._treeColumnListeners=[]},shouldExpand:function(a,c,b){return b},expand:function(a,c,b){if(this._treeColumn){var e=this,f=a.element?a:this.row(a),z=!!this._expanded[f.id],
q=t("transitionend"),r;a=f.element;a=-1<a.className.indexOf("dgrid-expando-icon")?a:s(".dgrid-expando-icon",a)[0];b=b||!this.enableTreeTransitions;if(a&&a.mayHaveChildren&&(b||c!==z)){var k=void 0===c?!this._expanded[f.id]:c;g(a,".ui-icon-triangle-1-"+(k?"se":"e")+"!ui-icon-triangle-1-"+(k?"e":"se"));g(f.element,(k?".":"!")+"dgrid-row-expanded");c=f.element;var d=c.connected,h,l,p={};if(!d){var d=p.container=c.connected=g(c,"+div.dgrid-tree-container"),n=function(a){var b=e._renderedCollection.getChildren(f.data);
e.sort&&(b=b.sort(e.sort));b.track&&e.shouldTrackCollection&&(d._rows=a.rows=[],b=b.track(),d._handles=[b.tracking,e._observeCollection(b,d,a)]);return"start"in a?b.fetchRange({start:a.start,end:a.start+a.count}):b.fetch()};"level"in a&&(n.level=a.level);if(this.renderQuery)r=this.renderQuery(n,p);else{var m=g(d,"div");r=this._trackError(function(){return e.renderQueryResults(n(p),m,v.mixin({rows:p.rows},"level"in n?{queryLevel:n.level}:null)).then(function(a){g(m,"!");return a})})}if(q&&!b)x.once(d,
q,this._onTreeTransitionEnd);else this._onTreeTransitionEnd.call(d)}d.hidden=!k;h=d.style;!q||b?(h.display=k?"block":"none",h.height=""):(k?(h.display="block",l=d.scrollHeight,h.height="0px"):(g(d,".dgrid-tree-resetting"),h.height=d.scrollHeight+"px"),setTimeout(function(){g(d,"!dgrid-tree-resetting");h.height=k?l?l+"px":"auto":"0px"},0));k?this._expanded[f.id]=!0:delete this._expanded[f.id]}return y(r)}},_configColumns:function(){var a=this.inherited(arguments);this._expanded={};for(var c=0,b=a.length;c<
b;c++)if(a[c].renderExpando){this._configureTreeColumn(a[c]);break}return a},insertRow:function(){var a=this.inherited(arguments),c=this.row(a);this.shouldExpand(c,this._currentLevel,this._expanded[c.id])&&this.expand(a,!0,!0);return a},removeRow:function(a,c){var b=a.connected,e={};b&&(b._handles&&(w.forEach(b._handles,function(a){a.remove()}),delete b._handles),b._rows&&(e.rows=b._rows),s("\x3e.dgrid-row",b).forEach(function(a){this.removeRow(a,!0,e)},this),b._rows&&(b._rows.length=0,delete b._rows),
c||g(b,"!"));this.inherited(arguments)},cleanup:function(){this.inherited(arguments);this.collapseOnRefresh&&(this._expanded={})},_destroyColumns:function(){for(var a=this._treeColumnListeners,c=a.length;c--;)a[c].remove();this._treeColumnListeners=[];this._treeColumn=null},_calcRowHeight:function(a){var c=a.connected;return this.inherited(arguments)+(c?c.offsetHeight:0)},_configureTreeColumn:function(a){var c=a.renderCell||this._defaultRenderCell,b;this._treeColumn=a;var e=this,f=".dgrid-content .dgrid-column-"+
a.id;if(!e.collection)throw Error("dgrid Tree mixin requires a collection to operate.");"function"!==typeof a.renderExpando&&(a.renderExpando=this._defaultRenderExpando);this._treeColumnListeners.push(this.on(a.expandOn||".dgrid-expando-icon:click,"+f+":dblclick,"+f+":keydown",function(a){var c=e.row(a);(!e.collection.mayHaveChildren||e.collection.mayHaveChildren(c.data))&&(("keydown"!==a.type||32===a.keyCode)&&!("dblclick"===a.type&&b&&1<b.count&&c.id===b.id&&-1<a.target.className.indexOf("dgrid-expando-icon")))&&
e.expand(c);-1<a.target.className.indexOf("dgrid-expando-icon")&&(b&&b.id===e.row(a).id?b.count++:b={id:e.row(a).id,count:1})}));t("touch")&&this._treeColumnListeners.push(this.on(m.selector(f,m.dbltap),function(){e.expand(this)}));a.renderCell=function(b,e,f,k){var d=a.grid,h=Number(k&&k.queryLevel)+1,l=!d.collection.mayHaveChildren||d.collection.mayHaveChildren(b),h=d._currentLevel=isNaN(h)?0:h,d=a.renderExpando(h,l,d._expanded[d.collection.getIdentity(b)],b);d.level=h;d.mayHaveChildren=l;(b=c.call(a,
b,e,f,k))&&b.nodeType?(g(f,d),g(f,b)):f.insertBefore(d,f.firstChild)}},_defaultRenderExpando:function(a,c,b){var e=this.grid.isRTL?"right":"left",f=".dgrid-expando-icon";c&&(f+=".ui-icon.ui-icon-triangle-1-"+(b?"se":"e"));a=g("div"+f+"[style\x3dmargin-"+e+": "+a*this.grid.treeIndentWidth+"px; float: "+e+"]");a.innerHTML="\x26nbsp;";return a},_onTreeTransitionEnd:function(a){var c=this,b=this.style.height;b&&(this.style.display="0px"===b?"none":"block");a&&(g(this,".dgrid-tree-resetting"),setTimeout(function(){g(c,
"!dgrid-tree-resetting")},0));this.style.height=""}})});
//# sourceMappingURL=Tree.js.map